### ISSUE TITLE
SETTING NOT WORKING

### ISSUE THREAD

**Issue by mizisahaja** [PokeBotPub/PokeBot-Android#10]
please fix for XIAOMI NOTE 3 - SETTING not working , always crash ,thanks

**Comment by PokeBotPub** [comment]
Can you try update Google Player Services?
Update link :  https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en

**Comment by mizisahaja** [comment]
i already update new latest version of google play service , hope u will
fix it
