### ISSUE TITLE
Create one bot for ingress

### ISSUE THREAD

**Issue by GGlaucon** [PokeBotPub/PokeBot-Android#111]
hello friend, you could create a bot that hack the Ingress portals too right, it would be of great help ... what do you think ???
Thanks!!!

**Comment by MbokJamu** [comment]
If you bot ingress, yo will reported by community, because ingress have log that display to all player.

**Comment by macinmn** [comment]
mmm.. not true.  portal hacking is 100% anonymous.   only capturing, upgrading, and attacking are shown in chat feed to other players.   don't personally really see the need for an inventory collection bot though.
