### ISSUE TITLE
Always Flee 

### ISSUE THREAD

**Issue by eshinozaki** [PokeBotPub/PokeBot-Android#114]

**Comment by boyracer71** [comment]
Same for me too pokemon always flee....pokestops collect as normal but no pokemon please help

**Comment by eshinozaki** [comment]
Are you capturing a pokemon after you use pokebot?

**Comment by boyracer71** [comment]
No they flee even in game now

Sent from Yahoo Mail on Android 
 
  On Thu, 29 Sep, 2016 at 10:57, eshinozaki<notifications@github.com> wrote:   
Are you capturing a pokemon after you use pokebot?

**Comment by dswtech** [comment]
Too many catch pokemon on 24 hours, rest your account for about 24 hours and play again

**Comment by cbittar** [comment]
that is like the softban for pokestops just stop the game bot for a couple of hours and up again 

in the case that the pokemon flee at the same time the pokestops are softban,  well that is 12 hours stop playing lol
