### ISSUE TITLE
Toggle to Transfer pokemon based on their " IV " 

### ISSUE THREAD

**Issue by svedkaabsinthe** [PokeBotPub/PokeBot-Android#121]
Toggle to Transfer pokemon based on their " IV " instead of CP .

Example , transfer pokemons if " IV " is below ( 1 - 100 ) \* able to set on our own *

**Comment by Tumerlan** [comment]
Or better make option "prefer IV over CP".
When bot catches a poke, it shows its IV. So make use it in transfer settings.

Otherwise bot is great!

**Comment by jyce50** [comment]
I had not seen that it was already asked and I agree IV is more important.

**Comment by Hiena1972** [comment]
Big like for this proposal.
