### ISSUE TITLE
GitHub can access my google account?

### ISSUE THREAD

**Issue by ariezilectrik** [PokeBotPub/PokeBot-Android#127]
Why you do  this? I  know because i check my security setting and my google account "automatically" download random game from playstore and give rating without my permission?

**Comment by PokeBotPub** [comment]
If you'r select login with Google+ account, pokebot is get access for pokemongo account.

**Comment by ariezilectrik** [comment]
Is pokebot know my password (google) if i login with Google+?. Please answer?
