### ISSUE TITLE
Why no usable pokestops

### ISSUE THREAD

**Issue by jouni88** [PokeBotPub/PokeBot-Android#130]
Why this dont find any pokestops or pokemons only use egg

**Comment by arthur1128** [comment]
Niantic has recently disabled access to their previous API, effectively disabling all bots, trackers, etc.

Since the new API has yet to be cracked by anyone, there is not a known fix yet

**Comment by cbittar** [comment]
Nothing we just have to wait hopefully the amazing team here come with a solution fast

Best luck dev team
