### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by kingster1999** [PokeBotPub/PokeBot-Android#134]
In on the bot and start it but it showsno pokestop in fact that place has many pokestop there

**Comment by jouni88** [comment]
Its update incoming i dont know when but dont try more try again about 5hours

**Comment by macinmn** [comment]
jesus christ people, do you not read at all???

**Comment by PokeBotPub** [comment]
Hi guys,
We still working on new version. We really very busy in real life.
PokemonGO is shutdown 0.35 api support. 
All bots and scanners down.
We will find new way for bots.

**Comment by macinmn** [comment]
great news Dev team,  my comment above was not directed at you if you thought it was.  it was directed at the people posting the same 'its broken' comment repeatedly when so many other threads already.

**Comment by jouni88** [comment]
Good luck team we all love this you work so much keep this alive forever 😄😄😄
