### ISSUE TITLE
Anyone know other bots

### ISSUE THREAD

**Issue by jouni88** [PokeBotPub/PokeBot-Android#138]
I really need botvfor this time when thid id no working thank you i will use this when fixed

**Comment by arthur1128** [comment]
http://adf.ly/1eiajO

**Comment by watkinz88** [comment]
Is that for mobile or pc?

**Comment by ariezilectrik** [comment]
For mobile? Nope. While waiting Pokebot new version release, why don't you discover pokemon in the real world and gotta catch em all?

**Comment by watkinz88** [comment]
Ive caught them all before i discovered a bot for mobile use anf also got to 32 without it but with a busy work life and newborn its hard to get out but yea ive done the hard part of the game :)

**Comment by jouni88** [comment]
I live in countryside in finland no much pokestops 😭
