### ISSUE TITLE
updating date

### ISSUE THREAD

**Issue by SalmanKing** [PokeBotPub/PokeBot-Android#140]
Are u going to update

**Comment by SalmanKing** [comment]
pokebot  going to be update or not 
If yes pls tell us the date

**Comment by ariezilectrik** [comment]
Not only pokebot, all bot are down. Because niantic change their API. So, before new API hacked bot can't be used.

**Comment by jouni88** [comment]
Yep i know its boring to wait but waiting will rewarded👍
