### ISSUE TITLE
i found new hack!!

### ISSUE THREAD

**Issue by arthur1128** [PokeBotPub/PokeBot-Android#141]
it work!  http://adf.ly/1emLsB
go to this website,and dowload (go gps),and go to hack info,must follow this info.
just for root user 😜

**Comment by watkinz88** [comment]
Bot or joystick cause my joy stick has never stopped working

**Comment by paulo004** [comment]
ohh for rooted ineet for none rooted

**Comment by paulo004** [comment]
ineed for no rooted

**Comment by paulo004** [comment]
watkinz can u give ah link of ur joystick for pokemon go?

**Comment by alfath2016** [comment]
No root... Fly gps for android 6.0

**Comment by paulo004** [comment]
my android is 4.4.4 only

**Comment by arthur1128** [comment]
mine android 4.4.2 kitkat can use this hack, problem just you need root your fhone
