### ISSUE TITLE
About PokeBotPub

### ISSUE THREAD

**Issue by PokeBotPub** [PokeBotPub/PokeBot-Android#142]
Hello Everyone,

We are still **working** on PokemonGO api. Not release any pokemongo api and our works not complete yet. 

I can't **give any date** for new version.

PokeBot project **is not** shutdown! **Don't remove** PokeBot app on your device. 

Thank you everyone. **Stay follow us.**

**Comment by ariezilectrik** [comment]
I always waiting of new version of pokebot.

**Comment by paulo004** [comment]
thank you very much i always wait .

**Comment by sak0471** [comment]
I'm happy to wait
cheer

**Comment by paulo004** [comment]
my blood is pumping thankyou im excited

**Comment by jouni88** [comment]
Me too waiting

**Comment by dandychoco** [comment]
i’m waiting dandy indonesia,thank you

**Comment by pegase26270** [comment]
Je vois remercie et en attente..de.la.mise à jour....bon courage et on reste avec vous.
Avez vous a peu prêt une date de la mise à jour...

Merciiiii

**Comment by kampret378** [comment]
Still waiting......thanks

**Comment by BangMet** [comment]
No update??
