### ISSUE TITLE
Mise à jour pokebot

### ISSUE THREAD

**Issue by pegase26270** [PokeBotPub/PokeBot-Android#143]
Bonjour un gros soutient à l'équipe pour trouver une solution pour que cela remarche.....

Merci à vous et en espérant que la version 19 marche bientôt

**Comment by ariezilectrik** [comment]
English please.

**Comment by jouni88** [comment]
Yup please speak english is cant use google translate

**Comment by paulo004** [comment]
english plssss

**Comment by paulo004** [comment]
hello a big support for a team to find a solution that works agin por...
thank you to you and hoping the version 19 running soon

**Comment by paulo004** [comment]
thats the translate of what he saying

**Comment by pegase26270** [comment]
hi all still not found solutions? it will be our Christmas present
