### ISSUE TITLE
Any closer to update?

### ISSUE THREAD

**Issue by watkinz88** [PokeBotPub/PokeBot-Android#147]
,?

**Comment by ariezilectrik** [comment]
Not yet. Almost 1 month since the last version release 1.0.18 on 22 september 2016 :(

**Comment by watkinz88** [comment]
Shame no other bots i know of run on mobiles :(

**Comment by BangMet** [comment]
Hello still don't have any updates? ?

**Comment by watkinz88** [comment]
Hello can you just let us know what's going on id like to donate and so would others only if not is coming back?

**Comment by ariezilectrik** [comment]
Hi Scott, why don't you use bots run on dekstop?

**Comment by emoglo** [comment]
Hello! know you a working bot on pc?
