### ISSUE TITLE
A glimmer of hope...

### ISSUE THREAD

**Issue by poorbroker1** [PokeBotPub/PokeBot-Android#148]
Fastpoke has had some success at breaking the new api the locater is now partialy working is said it will be fully up and running by Monday....hopefully that means well for us.............

**Comment by paulo004** [comment]
thanks for the info sir .. still waiting

**Comment by watkinz88** [comment]
Until the person who owns pokebot replys to what he's up to and still wants to update pokebot I wouldn't hold your breath it working again

**Comment by ariezilectrik** [comment]
1. The developer is busy in real life.
2. Niantic implemented new security in every update.

**Comment by BangMet** [comment]
Developer busy in real life? Ohh.. my..

**Comment by PokeBotPub** [comment]
Still working, we never leave this project. Update is soon. But can't give any date.

**Comment by ariezilectrik** [comment]
FastPokemap, PokeWhere, Pokemesh and all scanner is down again anyway.

**Comment by BangMet** [comment]
Pls.. do something pokebot..

**Comment by pegase26270** [comment]
Please....lol

**Comment by watkinz88** [comment]
Fastpokemap is working for me today they did stop it to try to stop servers overloading but thats always going to happen  when ita the only and best map app working.

**Comment by davido1034** [comment]
When will we get it pls.

**Comment by BangMet** [comment]
Pls all 3rdparty Radar already On..  Pokebot??

**Comment by ariezilectrik** [comment]
Be patient. If you don't, use other bots.

**Comment by BangMet** [comment]
Other Bots? What?
