### ISSUE TITLE
no hope

### ISSUE THREAD

**Issue by SalmanKing** [PokeBotPub/PokeBot-Android#149]
I think pokemon go devloper are high skilled then our poke bot team that's why more then a month  and comes out with nothing

**Comment by ariezilectrik** [comment]
Maybe this time to you step outside and discover pokemon in the real world, looks like the motto of Pokemon Go :)

**Comment by pegase26270** [comment]
this means that there is no hope of having a new version?

**Comment by Grandadi** [comment]
there is already a bot working.... it's named poke farmer but is private (you have to pay to use it)..... its just matter of time

**Comment by ariezilectrik** [comment]
But pokefarmer run in PC.

**Comment by watkinz88** [comment]
Poke farmer is also not working just checked it's online status and forums. All bots will be back when FPM release or API spills for tom someone..

**Comment by ariezilectrik** [comment]
Why all bots and scanner developers are dependent t

**Comment by ariezilectrik** [comment]
..dependent to Fast Poke Map?
