### ISSUE TITLE
Egg distance left typo and evolving misleading text

### ISSUE THREAD

**Issue by SuperSandro2000** [PokeBotPub/PokeBot-Android#15]
If the bot starts it prints that my eggs have 0 km left but in reality they have 0 km of 5 or 2 km and after a while it prints a similar line with left instead of already walked. 
If the bot tries to evolve a Pokemon it sometimes prints that the Pokemon was evolved for 500 (500 what?) and right in the next line that the evolve failed. It's almost always happening with Weedles.

**Comment by PokeBotPub** [comment]
I know, egg walking function have a bug. It will fix this week. :+1:
