### ISSUE TITLE
bot working, but...

### ISSUE THREAD

**Issue by watcht** [PokeBotPub/PokeBot-Android#151]
The bot "Pokefarmer" is working with POGO 0.43 But you have to pay to use it. I think it's the only bot working but I think that news free bots are coming. We trust in pokebot :) to come back to boting some day. 

For old version of pokefarmer someone cracked it and maybe crack it again. I think that developers like pokebot will make a free bot to use :+1:  and I really hope it :) and thank you to the developers for all the work that you make :+1:

**Comment by watkinz88** [comment]
Need one for mobiles and tablets people who have not got pcs

**Comment by watcht** [comment]
That's true, but the important is that they have the new API... Is a good new, because someone did reverse engineering to PoGo... maybe a new update of pokebot is close .

**Comment by BangMet** [comment]
Hope so.. pokebot best ever

**Comment by watkinz88** [comment]
Heard FPM have released new api so dunno how long it will take to use for bots

**Comment by BangMet** [comment]
Still waiting..
