### ISSUE TITLE
Who is missed Pokebot?

### ISSUE THREAD

**Issue by PokeBotPub** [PokeBotPub/PokeBot-Android#152]
Hello everyone,

We will release new version in few days. :+1:

<img src="http://i.imgur.com/XNuC8V0.png"/>

**Comment by alelast** [comment]
Great, we are exited ;)

**Comment by ariezilectrik** [comment]
Me. Thank you so much *brother hug*

**Comment by zc3721** [comment]
cooooool

ariezilectrik <notifications@github.com>于2016年11月6日周日 16:10写道：

**Comment by paulo004** [comment]
thankyou . the wait is over mwah

**Comment by lomatosiono** [comment]
Omg ! Thanks you developers :D

**Comment by BangMet** [comment]
Yeahhh.. Go Go.. Pokebot

**Comment by watcht** [comment]
YEAH!!!! is the best news !!!!! go go go go :)

**Comment by watkinz88** [comment]
Oh damnnnnn yea!!!you should charge for your bot or get some donations...

**Comment by poorbroker1** [comment]
Yess.cant wait...see like I said a glimmer of hope.....

**Comment by jouni88** [comment]
Wow at least but better it come now than ever

**Comment by paulo004** [comment]
the pokemon go is update again

**Comment by ariezilectrik** [comment]
Map Scanner "FastPokeMap" is shutdown forever.

**Comment by Wetterhex88** [comment]
Pokefarmer is still working.......

**Comment by sak0471** [comment]
I'm waiting thank you very much for your hard work

**Comment by pegase26270** [comment]
Merciiiiiii

**Comment by EkoWijonarko** [comment]
Im so happy for it. 
This my best bot for android.
I can till this level because you.
Thanks so much.
Your app its so amazing.

**Comment by BangMet** [comment]
Counting day

**Comment by EkoWijonarko** [comment]
When the poke bot will release?
I'm so happy to use tje bot.
I think it's the best bot andro number 1.

Pada tanggal 9 Nov 2016 20.19, "BangMet" <notifications@github.com> menulis:

**Comment by BangMet** [comment]
Still waiting.. fuhhh..

**Comment by dandychoco** [comment]
Softband pokemon capture ,capture flee not unband
