### ISSUE TITLE
Much praise and thanks to the devs

### ISSUE THREAD

**Issue by poorbroker1** [PokeBotPub/PokeBot-Android#156]
Love the new features..auto walk is amazing...always wanted this feature....

**Comment by iiMrTrainer** [comment]
what new features? auto walk? what are you talking about sir

**Comment by lucho-cl** [comment]
loved too! gj guys

**Comment by paulo004** [comment]
thankyou somuch admin for this the waits finaly over

**Comment by watkinz88** [comment]
Mine stops catching pokemon 6 mins into it weird its not captcha checked everything
