### ISSUE TITLE
Doesnt catch all pokemon

### ISSUE THREAD

**Issue by watkinz88** [PokeBotPub/PokeBot-Android#159]
Noticed it will stop catching pokemon while hitting stops instead for 5 mins then decides to catch 2-3 then pokestops for 5 mins repeats i logged in game to check and there loads of spawns og pokemon but bot doesnt catch. Any solution?

**Comment by ariezilectrik** [comment]
Are you using normal mode or auto solve captcha?

**Comment by watkinz88** [comment]
Why would captcha have anything to do with it pokestops are working fine but catching pokemon aint?

**Comment by watkinz88** [comment]
Yes im using normal mode but surely doesnt cause it not to catch pokemon ive logged ibto game a few time and i havent had captcha screen

**Comment by SerialKillaZ** [comment]
This is happening to me aswell. Im using auto solve captcha.

**Comment by BangMet** [comment]
Me too..
