### ISSUE TITLE
Please add an option NOT to transfer Pokémon with an IV of 100

### ISSUE THREAD

**Issue by DrakeLyon** [PokeBotPub/PokeBot-Android#161]
I was very saddened to notice a good collection of my duplicate IV 100 Pokémon went missing when I used this. I know I could've just turned the transfer feature off, but a bot isn't very good if it doesn't transfer Pokémon for the candies. Also, if you can add a feature to automatically favorite Pokémon with IV 100 that would make everything a lot easier. Thanks again for such a great app! I'm glad to see that something still works and is being developed.

**Comment by shellclear** [comment]
I think will be bettter if ad an option to transfer pokemon based its IV, so if IV less than x or greater than x transfer.

**Comment by SerialKillaZ** [comment]
^^this

**Comment by lucho-cl** [comment]
good idea :P

**Comment by T9090** [comment]
need it :)

**Comment by officiallytook** [comment]
This should have been first implement of apk...no one cares for CP
