### ISSUE TITLE
1.0.21 API

### ISSUE THREAD

**Issue by shamoel11** [PokeBotPub/PokeBot-Android#164]
Hey guys I would like to know if pokebot version 1.0.21 is safe to use on 0.45.0pokemonGo or if it is updated to the api in 0.45.0.  thanks

**Comment by watkinz88** [comment]
Yes it is safe.

**Comment by shamoel11** [comment]
So it uses the api which is on version 0.45.0 and is their a discord channel or other place to chat

**Comment by watkinz88** [comment]
Yea API is for the newest update. No other channels sorry I'm using it on 10 accounts not even a warning or softban just shame it ain't picking up all Pokémon catches a few here and there.
