### ISSUE TITLE
Bot Not Evolving

### ISSUE THREAD

**Issue by dswtech** [PokeBotPub/PokeBot-Android#165]
I think new version not evolving pokemon. I've used lucky egg and many pidgey, but none of them evolved. I've wait for 10 minutes and nothing happen

**Comment by BangMet** [comment]
Bot not catch pokemon.. why?? Just spin d pokestop.. AnyOne?

**Comment by watkinz88** [comment]
My bot is working ok the only problem is it's not catching many Pokemon only 5 at a time every 5 mins which is weird. Mine are evolving fine have you put the Pokemon you want to evolve in setting to evolce

**Comment by dswtech** [comment]
@watkinz88 yes, pidgey is listed by default right ?

**Comment by macinmn** [comment]
confirm no evolve in 1.0.21 (also, not consuming of Lucky Egg when selected)

**Comment by cire27rn** [comment]
yes! mine too not evolving
