### ISSUE TITLE
PokeBot doesn't stop

### ISSUE THREAD

**Issue by DrakeLyon** [PokeBotPub/PokeBot-Android#168]
PokeBot doesn't stop running when I hit the stop button. It just keeps saying "Stopping bot" or something. I'm running this app on the Verizon Galaxy S7.

**Comment by watkinz88** [comment]
It does stop it's just crashing when you press stop while it's following it's code to do its next move. I noticed if I press stop after its hit a pokestop it works properly.

**Comment by DrakeLyon** [comment]
Oh, still a small bug I guess lol. Hope it gets fixed sometime

**Comment by inetwiz** [comment]
Me too
