### ISSUE TITLE
Cannot detect pokestops nearby

### ISSUE THREAD

**Issue by a07272** [PokeBotPub/PokeBot-Android#17]
When the bot executes task for a while, it ends up with "no usable PokeStops found in your area". You can press stop then start, bot will find the pokestop again, or enter the setting, change the location a little then save, it will run. 

Can you change the condition check when it detects "no usable pokestops found in your area", let the bot keep on moving with walking speed instead of stop there.

**Comment by SuperSandro2000** [comment]
I think a better option would be to add entry in the settings section for the search radius.

**Comment by PokeBotPub** [comment]
We will add randomize walking, when no usable pokestops found in area. :+1:
