### ISSUE TITLE
pokebot 1.0.21

### ISSUE THREAD

**Issue by ufolcy** [PokeBotPub/PokeBot-Android#170]
hi admin:

i just used the bot 2 days but i found the bot can't capture any pokemon anymore now. but it's ok to get material from pokestop. can pokebot help check?

thanks!

**Comment by ufolcy** [comment]
i check original pokemon app/journal and it shows pokemon run away during i used pokebot's capture function. could pokebot team help check the issue?

thanks!

**Comment by ufolcy** [comment]
update:

it seems my account is locked by niantic. i only use bot about 3 hours each day but niantic may think my xp is not reasonable to increase. i suggest you all guys dont' use the bot too long.

**Comment by watkinz88** [comment]
Used it on all 10 account since update all 6 hours each no ban all leveling up you must have collected 2000 pokestops or pokemon botting to long. No such thing as a exp limit sorry.

**Comment by ufolcy** [comment]
hi watkinz,

do you suggest i don't use the bot and don't play normal pokemon and into pokestop for a while(maybe several days?)? do you know how long i will be banned?

thanks

**Comment by watkinz88** [comment]
It has happened to me first time I used bots got to learn ways around bans I bot 6 hours only then leave it for 12 hours then bot another 6 hours and so on that's how u don't get banned but it's normally only 12 hour ban. Make sure your not botting in say new York then logging into real game to we're you live and hitting a pokestop catching pokemon hitting gym or evolving pokemon cause that's a instant ban to!normally takes 3-4 hours before you can play back were u live. Make a few accounts and take it in turns botting it's more enjoyable can have more high levels to throw on gyms.

**Comment by ufolcy** [comment]
i am unlocked now and take me about 8 hours to unlock. so it means we can't use the bot for too long but i need to say the bot app is really good to add fun for pokemon. the safe way is we only use bot near our living area and don't jump to too far area and control the xp quantity increase everyday. 

enjoy!

**Comment by watkinz88** [comment]
There is no exp ban lol and I bot is Australia on all my account for 6 hours a day gaining 500k on all no ban I also live in united kingdom. Bot less then 6 hours and you won't get a ban simple.
