### ISSUE TITLE
Why does buddy not gain candies for walking?

### ISSUE THREAD

**Issue by poorbroker1** [PokeBotPub/PokeBot-Android#171]
After using bot for 1 hr no longer on my accounts and I log into my game it always says buddy found 1 candy but no more why is this

**Comment by poorbroker1** [comment]
Besides this having no problems at all....would like to see a timer built in that one could set and bot would shit down after such set time...so as to avoid suspicion..

**Comment by aquibzafar** [comment]
Buddy not gaining candies also
