### ISSUE TITLE
Hatching Eggs 

### ISSUE THREAD

**Issue by alelast** [PokeBotPub/PokeBot-Android#172]

**Comment by alelast** [comment]
I don't see Pokemon that are from eggs

**Comment by watkinz88** [comment]
Yea it's a bummer hatch 18 eggs while on bot never know or find out what's been hatched or even if they get transferred or kept.

**Comment by cbittar** [comment]
I know what happens on the log of the game lol

**Comment by SerialKillaZ** [comment]
Doesn't tell me what pokemon hatched from egg. Would be nice to see what hatched!

**Comment by aquibzafar** [comment]
There should  be a Hatched pokemon list ?
