### ISSUE TITLE
PokeBot can't exit app with back button

### ISSUE THREAD

**Issue by DrakeLyon** [PokeBotPub/PokeBot-Android#173]
On the Galaxy S7 I'm unable to exit the app unless I use the task manager to clear out of it. Not a big issue, but a small bug you may want to fix in the future.

**Comment by ariezilectrik** [comment]
It's not bug.

**Comment by DrakeLyon** [comment]
Oh it's not? Is it just intended for us to hit the home button to back out?

**Comment by ariezilectrik** [comment]
Yes, because the application running in background. If you want to close the application hit the stop button and then tap back button.
