### ISSUE TITLE
Transferring pokemon from low IV

### ISSUE THREAD

**Issue by Agronopolos** [PokeBotPub/PokeBot-Android#176]
Hi, guys
Would not it be nice to have the option of transferring the pokemons repeated based on the low IV, rather than the Low CP?

**Comment by ufolcy** [comment]
yes, i also think the feature is very important rather than just transferring low CP.

**Comment by DrakeLyon** [comment]
I agree! I look forward to this becoming a feature if the developer agrees :)

**Comment by Matteo561** [comment]
also agree!!
