### ISSUE TITLE
it is normal??

### ISSUE THREAD

**Issue by Grandadi** [PokeBotPub/PokeBot-Android#177]
Hi everyone its suppose to be like this??, or it should send you to the bot when you are done with the captcha?

![pokebot](https://cloud.githubusercontent.com/assets/22277539/20240744/1799f03c-a8ff-11e6-9173-89e256a752f8.jpg)

**Comment by Grandadi** [comment]
because it stay like this for ever and i have to redo the captcha every single time

**Comment by ariezilectrik** [comment]
Donate for $10 and you can get auto solve captcha.

**Comment by Grandadi** [comment]
@ariezilectrik so the only answer to bot with pokebot as we usually do before all this api shit, is paying 10 usd per month??

**Comment by ariezilectrik** [comment]
Yes. You should appreciate for hard working the developer.

**Comment by watkinz88** [comment]
It's a one off payment not per a month lol
