### ISSUE TITLE
Patch 1.0.9

### ISSUE THREAD

**Issue by lowmack** [PokeBotPub/PokeBot-Android#18]
*I would like to clarify that the bot keeps recycling Poke-balls even ultra balls.
please put an adjuster on Settings on how many items it can keep on balls or throw all potions away option.( I have 500 items storage but wont get filled since it recycles all)
*Bot is walking too fast and will make Incense useless, Keeps getting ban in poke-stop collection, Pass by Pokemon nearby, and I keeps getting lost until it cant detect poke stops even when it is near one.
Please put option on how fast you can walk in 1 second( like 5 feet per 1 seconds)
*It hordes Revive item. (we only need 20)
*If you can also Please make a route marker so it wont aimlessly go run around and getting confused and possibly pass trough some Poke Lure areas to Maximize catching Pokemon.
Thanks hope you add them on your next patch.

**Comment by SuperSandro2000** [comment]
I need to agree to all your points sadly. I love the bot because it is the only one so far on Android that can run on its own over night and keeps the device on.

**Comment by PokeBotPub** [comment]
Advanced Settings feature is come this week. Thank you :+1:
