### ISSUE TITLE
"Pokemon failed" 

### ISSUE THREAD

**Issue by ryanbks8000x** [PokeBotPub/PokeBot-Android#184]
What does it mean? It will attempt catch, then say fail, other times, it will say the more obvious one "pokemon flee". But i wanna know why it says pokemon failed. In the midst of it saying that it does still catch pokemon then. Ive just never seen it before

**Comment by SerialKillaZ** [comment]
Just failed to catch. I think like the ball missed.

**Comment by BangMet** [comment]
Always failed to capture rare pokemon..
