### ISSUE TITLE
Pokebot transfer

### ISSUE THREAD

**Issue by jutzo** [PokeBotPub/PokeBot-Android#185]
Pokebot not transfering pokemons in the newest version...

**Comment by SerialKillaZ** [comment]
Yep same for me. Needs fixing im stopping using until this is fixed.

**Comment by PokeBotPub** [comment]
Fixed.

**Comment by andradafa** [comment]
i have error with transfering pokemon, like i have pinsir cp200 on storage and bot get pinsir cp900. bot always transfering newest and high pokemon. I hope this fixed.
