### ISSUE TITLE
failed when catch pokemon

### ISSUE THREAD

**Issue by kakaknight12** [PokeBotPub/PokeBot-Android#187]
Sometime notice "pokemon failed "
I open again.And 5-10 minute notice "pokemon failed"sorry my Eng

**Comment by kakaknight12** [comment]
The ball in my bag still many

**Comment by BangMet** [comment]
Same issue.. not capture  rare pokemon & always Failed to capture

**Comment by paulo004** [comment]
me . i have no encounter any rare pokemon .. snorlax .lapras . gyarados . dragonite i also catch is very common plsss fix admin
