### ISSUE TITLE
IV "Not to Transfer" setting not working

### ISSUE THREAD

**Issue by DrakeLyon** [PokeBotPub/PokeBot-Android#188]
I noticed this as soon as I got another Kingler it transfered my Kingler with IV 100. It isn't prioritizing IV over CP. I hope this gets fixed soon.

Thanks again for adding the feature though! :)

**Comment by kakaknight12** [comment]
Iv tranfer work for me

**Comment by Matteo561** [comment]
Also not working for me.

**Comment by kakaknight12** [comment]
Be sure you check auto tranfer and save.I setup tranfer  iv<90

**Comment by DrakeLyon** [comment]
I have mine set to IV<100 but it still transfers my Pokémon at IV 100 for some reason. The check box is checked too.

**Comment by SerialKillaZ** [comment]
Seems to be working fine for me IV<95
