### ISSUE TITLE
hard to catch pokemon that CP>1000 

### ISSUE THREAD

**Issue by ufolcy** [PokeBotPub/PokeBot-Android#191]
hi developer,

i found new version 1.0.25 is hard to capture pokemon, CP>1000. the success rate is less than 10%.
1.0.22/23 has no this problem. do you modify algorithms for catching? i think it's a big issue for all since we often try to capture rare pokemon like snorlax, dragonite but bot much often failed to capture. 

could you help check the issue and fix it?

thanks so much!

**Comment by BangMet** [comment]
Me too hard to capture Rare pokemon always failed..  plss do something..

**Comment by Khan-Noor** [comment]
Where u set location in pokebot

**Comment by paulo004** [comment]
me i canot encounter any rare pokemon . snorlax lapras dragonite gyarados . i allso catch is very common thats all nothing rare

**Comment by aquibzafar** [comment]
A pokesniper shouid be built in it and the map should be another type . The present map is way confusing .
