### ISSUE TITLE
Farming without walk

### ISSUE THREAD

**Issue by inetwiz** [PokeBotPub/PokeBot-Android#192]
Hi, that is possible to add an option that allow us farm without walk? I have a spot with 6 Pokestop in range, that some times all 6 are lured.

**Comment by BangMet** [comment]
Something happen on pokebot..

**Comment by inetwiz** [comment]
Uh?

**Comment by officiallytook** [comment]
Asking for a stay at coordinates feature, no walk, just stand catch and spin lured stops

**Comment by inetwiz** [comment]
Yes.. good for, lure partes and some special events

**Comment by Girt97** [comment]
👍

**Comment by officiallytook** [comment]
Longer delay between catches too, noticed rarer Pokemon take a few extra minutes to spawn
