### ISSUE TITLE
MAP issue - jump automatically from country to country - dont catch any pokemon

### ISSUE THREAD

**Issue by xamel** [PokeBotPub/PokeBot-Android#195]
The Bot jump in the MAP from point to point and dont catch any pokemon :-(
Maybe the bot jump from country to country .... really bad

**Comment by mitch-gh** [comment]
Experienced this bug as well. I hope its not jumping from country to country because it will raise a red flag in Niantic's system.

**Comment by kakaknight12** [comment]
Same error 5-10minute jump point to point and noticed "pokemon failed"when catching.

**Comment by mitch-gh** [comment]
Should we stop from using the bot for a while? Please give us a heads up. Bot is working but it keeps on teleporting not even sure if my character is travelling from country to country. If it does this is a big problem!

**Comment by xamel** [comment]
I have stoped the bot, if you go to the MAP, then you can see, that the bot jumped to another country, that is on my bot

**Comment by PokeBotPub** [comment]
Fixed!
