### ISSUE TITLE
Favorit transfered

### ISSUE THREAD

**Issue by Wetterhex88** [PokeBotPub/PokeBot-Android#196]
Pokebot transfered favorit Pokémons. Is it possible to change this issue?

**Comment by ufolcy** [comment]
yes, i also found the issue from 1.0.18

**Comment by Wetterhex88** [comment]
Pokebot also always transfers two pokemon

**Comment by ufolcy** [comment]
the issue is also found from 1.0.18 to now and transfer older two pokemon even the newest pokemon CP is lower than old ones from poke bags.

**Comment by PokeBotPub** [comment]
Fixed!
