### ISSUE TITLE
3 out of 7 accounts suspended

### ISSUE THREAD

**Issue by poorbroker1** [PokeBotPub/PokeBot-Android#199]
I have had 3 accounts suspended.only use the bot on each account for 1hr 30 mins a day.about 15 mins from my house on the local college campus.any clues on how long the suspension could/will last..

**Comment by emoglo** [comment]
Suspended too

**Comment by scottjerbi** [comment]
ive got suspended too , is it a permanent ban or just a suspension im really confused

**Comment by poorbroker1** [comment]
Not sure if its permanent or not hope not because those where my main accounts have one other really good account but have not logged into it afraid it will be banned also

**Comment by scottjerbi** [comment]
i see, mine was the only one i had , i just made another one in case the other was perma banned ! i hope not really

**Comment by poorbroker1** [comment]
Is this suspension from the map jumping from place to place while using the bot I noticed it was doing that but was not to concerned at the time..

**Comment by scottjerbi** [comment]
yeah i noticed it too, i dont know maybe , but the devs said that they fixed it in the latest versions , from my opinion maybe the suspension is due the continiuously "pokemon flee ban" that lasts from one hour to three...i really need answers right now

**Comment by scottjerbi** [comment]
anyways just let me know if its not perma ban bro

**Comment by scottjerbi** [comment]
anyways just let me know if its not perma ban bro

**Comment by poorbroker1** [comment]
Will do keep me informed also please

**Comment by scottjerbi** [comment]
okey 😊

**Comment by alelast** [comment]
<a href="http://it.tinypic.com?ref=acvs4h" target="_blank"><img src="http://i66.tinypic.com/acvs4h.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by alelast** [comment]
Me too..
I hope it's a temporary ban

**Comment by scottjerbi** [comment]
lets hope yes. it sucks..

**Comment by PokeBotPub** [comment]
We are working on anti-ban algorithm. You are can follow us on discord channel. https://discord.gg/WcMFfUZ

**Comment by scottjerbi** [comment]
thank you that will be much apreciated, my friends told earlier that niantic is doing ban wave again..

**Comment by shieldmanju** [comment]
@PokeBotPub, thank you again for your efforts!

Other forums and reporting same issues.

Got my best account banned. Sent a plea to lift ban hope they reconsider *crosses fingers XD

**Comment by scottjerbi** [comment]
lol i did that too..

**Comment by ufolcy** [comment]
i check poke help center and they have three kind of penalty and most serious is terminate. i guess "suspend" is temporary.

i also got suspend banned. :-(

**Comment by xamel** [comment]
i also got suspend banned 2 accounts ;-(

**Comment by ufolcy** [comment]
test

**Comment by paulo004** [comment]
me my acc . is ok . after the pokebot update untill now my acc is not ban ill use 24 ours a day

**Comment by scottjerbi** [comment]
anyone got their accout back?

**Comment by xamel** [comment]
no, wiht a hard ban, you get the account not back .... nevermore

**Comment by Khan-Noor** [comment]
I am using from last 3 day regular without stop from level 1 to 24 now it becomes 25 level now 
Location India (pokebot)

**Comment by scottjerbi** [comment]
and u dont get the pokemon flee ban for using it that long @khannoor
