### ISSUE TITLE
Account suspended only temp

### ISSUE THREAD

**Issue by poorbroker1** [PokeBotPub/PokeBot-Android#200]
Recieved this from the game after I submitted a request for a review..

Google+
Calendar
Web
more
Primary
Thanks for contacting Pokémon GO Support [#23321263]
P
Pokémon GO
to me
43 minutes agoDetails
##- Please type your reply above this line -##
Trainer,

We have received your appeal. Our goal is to provide a fair, fun and legitimate game experience for everyone. Use of any other third-party software or app, including but not limited to scripts/apps, applications used to falsify your location, emulators, modified or unofficial software and/or accessing Pokémon GO clients or backends in an unauthorized manner is considered cheating.

We are reviewing all account termination appeals. If our system determines that your account was terminated in error, we will send an email to confirm that your account has been reinstated.

If you have not received an email stating your account was terminated, but are experiencing login issues or map loading errors it may just be a temporary server issue. Please try to login again in a few hours.

-NianticOps

Read the third paragraph.so no email would seem to mean that it's only an temporary ban...

**Comment by ufolcy** [comment]
It means niantic will take effort to review your account, your account is still locked.

**Comment by kakaknight12** [comment]
I used take care and my acc still live.Not ban for me.
don't jump so far just one country

**Comment by emoglo** [comment]
No received email and always suspended. The time is stopped at Niantic!
