### ISSUE TITLE
delay action settings

### ISSUE THREAD

**Issue by 1arry** [PokeBotPub/PokeBot-Android#202]
Does this setting really work?
set it to 5000+ ms but still capture/transfer in like one second.
higher chance to get banned if it does not work.

**Comment by aquibzafar** [comment]
Delay timing doesn't work

**Comment by NaeNezu** [comment]
Not like " human ".

**Comment by 1arry** [comment]
for "Use" triggered actions, they should be in a serial queue with reasonable delay.
