### ISSUE TITLE
POKEMON TRANSFER FAIL

### ISSUE THREAD

**Issue by NaeNezu** [PokeBotPub/PokeBot-Android#203]
I have started POGO so many times. But it seems like the bot didnt transfer any of my pokemon. I have to login to my POGO to delete myself. Transfer pokemon menu seems like not functioning. 
( using new update ).

**Comment by paulo004** [comment]
for me its ok for transfering pokemon . and i dont need to open my pogo to delete .

**Comment by aquibzafar** [comment]
Manual transfer option needed

**Comment by paulo004** [comment]
thats exactly manual transfer .

**Comment by paulo004** [comment]
hey guys . where did you catch rare?in your country? can u tell me?

**Comment by aquibzafar** [comment]
Yess the automatic transfer is also working great

**Comment by nastrognola** [comment]
my account still suspended

**Comment by kakaknight12** [comment]
Still jump point to point and catch pokemon failed
