### ISSUE TITLE
pokemon flee or failed again...

### ISSUE THREAD

**Issue by scottjerbi** [PokeBotPub/PokeBot-Android#207]
on version 1.26 almost everything worked just fine ...im gratefull for all the work and effort the pokebot team did , but it seems every update that comes brings a new issue....

**Comment by kakaknight12** [comment]
same here.And now poketop and pokemon not found in area.Please fix

**Comment by scottjerbi** [comment]
i can collect pokestops but the pokemons flees, it was an hour ago it should be unbanned in 2 hours
