### ISSUE TITLE
permanent ban

### ISSUE THREAD

**Issue by aquibzafar** [PokeBotPub/PokeBot-Android#208]
Few account had been permanently banned . Niantic had somehow spotted out the bot users

**Comment by scottjerbi** [comment]
is it a ban wave or what?

**Comment by aquibzafar** [comment]
Some how niantic is able to detect bot ids . Even when they are not running the bot .

**Comment by cire27rn** [comment]
mine too but i did not use this. pc botter here

**Comment by kakaknight12** [comment]
just setup slow and your acc will be safe.

**Comment by aquibzafar** [comment]
Slow setup is not working
