### ISSUE TITLE
Needs to capture more Pokemon

### ISSUE THREAD

**Issue by namekwarrior** [PokeBotPub/PokeBot-Android#21]
Sir, can you make the bot capture more pokemon? Because i already put the speed at the lowest and yet it's not capturing more pokemon. The bot only loot poke stops and bypasses the pokemon nearby. Btw this update is good but the pokemon capture rate needs to be increase. Thank you.

**Comment by SuperSandro2000** [comment]
Poke capture rate is quit low because Pokemons are rarer compared to poke stops.
For example in my city I can find 5 or more poke stops before I even find a Pokemon to capture with the vanilla app.
