### ISSUE TITLE
1.0.27 crash alot

### ISSUE THREAD

**Issue by dswtech** [PokeBotPub/PokeBot-Android#211]
After update to 1.0.27. Pokebot crash after some times

**Comment by scottjerbi** [comment]
yes a lot of issues...need fixes

**Comment by Matteo561** [comment]
Yes this and a lot of other issues.

**Comment by ufolcy** [comment]
pokestop is hard to anti soft-ban...
bot can't see all around pokemon near trainer and catch them, always catch few ones.
bot always find out very far pokestop to anti soft-ban and take much time

**Comment by scottjerbi** [comment]
i noticed that the bot catches few pokemons now and a lot of pokestop farming ?? damn,  what is this ?

**Comment by nastrognola** [comment]
aarghh..my acc still suspended..whyyyyy
