### ISSUE TITLE
No Pokemons captured on v.028

### ISSUE THREAD

**Issue by johnfocht** [PokeBotPub/PokeBot-Android#213]
Where are pokemon? None caught since today. Just some pokestop gives px..

**Comment by ufolcy** [comment]
it's a warning from niantic. you catch too many pokes in short time.

**Comment by kakaknight12** [comment]
just security of Niatic.Waiting few hour and you will be catch

**Comment by johnfocht** [comment]
Hmm. Good to know. How u manage this? Is there any known time limit? Thank you!

**Comment by aquibzafar** [comment]
The catching had started run it again and turn off the ignore Pokémon option .
