### ISSUE TITLE
Settings working - No numbers showing

### ISSUE THREAD

**Issue by Kraker01** [PokeBotPub/PokeBot-Android#22]
Hi,

how can I modify my settings if i don't see numbers? I can only see sliders but it's hard to only use them

**Comment by SuperSandro2000** [comment]
If you hold the slider you can see the numbers. I don't know from which android version that works bit it works on Marshmallow.

**Comment by SuperSandro2000** [comment]
I think it would be cool if we see the number directly and can type them in.
