### ISSUE TITLE
Ohh BanWave :( when you will come? any dates

### ISSUE THREAD

**Issue by ShairaMaex** [PokeBotPub/PokeBot-Android#223]
Having Trouble with this new map :/ otherwise local farming area are great it wont be notice.

**Comment by scottjerbi** [comment]
i heard changing the marker on the map from palce to place get u flagged even if you are in ur local areas is that true ??

**Comment by ShairaMaex** [comment]
Nope it wont give it a few mins so it will not be flagged :)

**Comment by scottjerbi** [comment]
can you be more specific lol thank you..

**Comment by ShairaMaex** [comment]
Give it time to rest like 5mins so u can move to ur specific location. So it will not vlbe flaggedm

**Comment by scottjerbi** [comment]
okey got it thanks
