### ISSUE TITLE
Look everbody..

### ISSUE THREAD

**Issue by poorbroker1** [PokeBotPub/PokeBot-Android#225]
The developers are working on the update as fast as they can quit bitchin that they need to hurry up..appreciate that they even do anything for us they could do it just for themselves and not release it to us so appreciate it and dont bitch..

**Comment by aquibzafar** [comment]
Yeah .!
They've done a lot already . 
I just have people acting as  bosa

**Comment by aquibzafar** [comment]
Boss

**Comment by ShairaMaex** [comment]
Yeah, ive been telling people that to wait not to hurry. The developers on the update. :)
Please appreciate them. What they done for us and the bot community 👍

**Comment by i3ongmeester** [comment]
True that...

**Comment by nastrognola** [comment]
waiting..still waiting..Niantic still suspended my acc..so sad..aarrghhh

**Comment by ShairaMaex** [comment]
@Nastrognola like the one cant get data from server?

**Comment by nastrognola** [comment]
better uninstall & install the new poke apps & register with new google acc..?..any suggestion..?

**Comment by aquibzafar** [comment]
Yess @nastrognola

**Comment by nastrognola** [comment]
omg..lose my bes acc with bes CP poke..btw tq for that suggest friend
