### ISSUE TITLE
 Can we use pokebot or still not?

### ISSUE THREAD

**Issue by jyce50** [PokeBotPub/PokeBot-Android#227]
???

**Comment by BangMet** [comment]
What happend? Pokebot can make our account ban?

**Comment by jyce50** [comment]
We are working on 0.47.1 version. Currently have ban risk, don't use bot!!! Update is soon.

**Comment by AbiDez** [comment]
Friend use the bot, comes Captcha many times...

**Comment by scottjerbi** [comment]
they already said , we have to not use the bot until the next update , crossing fingers ! im sure they are working very hard
