### ISSUE TITLE
Event 23.11-30.11 + Pokebot ^^

### ISSUE THREAD

**Issue by AbiDez** [PokeBotPub/PokeBot-Android#228]
Hi guys, hi DEV team of Pokebot... 
1st to say, great work with your bot... It's a nice tool to... 
Tomorrow starts a new event, double stardust + double XP... 
Theoretical I think it's +4 with lucky egg, that's a great thing... 
I hope the next update is comming soon... 
Have a nice day...

**Comment by LillyWhiteapple** [comment]
I hope so too x3
I think they work really hard :) 
Can't imagine how much work it is making such a great bot :D
But when it doesn't work for the event, its okay too :) 
Don't stress yourself @team :D

**Comment by ShairaMaex** [comment]
Remember developers are giving us a warning . about the ban risk

**Comment by AbiDez** [comment]
Yup... No botting at this time... Ban risk... I love my Acc because botting is a help for me, I play many hours a day in RL... Event is great... Today 80k^^ But it's a long way to 1250000 XP...
