### ISSUE TITLE
Auto CAPTCHA resolve not working, help me

### ISSUE THREAD

**Issue by saldorflorin** [PokeBotPub/PokeBot-Android#229]
No description!

**Comment by xamel** [comment]
NOTICE
We are working on 0.47.1 version. Currently have ban risk, don't use bot!!! Update is soon.

**Comment by saldorflorin** [comment]
OK, thank you.

**Comment by MettaWorldPeece** [comment]
Not sure if you solved it or the ban was only temporary.  I was having CAPTCHA issues but was able to resolve them by opening up my account in Pokemon Go and it filling out their CAPTCHA.  I was up and running in under an hour.
