### ISSUE TITLE
new api implemented

### ISSUE THREAD

**Issue by aquibzafar** [PokeBotPub/PokeBot-Android#230]
Bot is not working

**Comment by scottjerbi** [comment]
its working but the from time to time the captcha pops up

**Comment by aquibzafar** [comment]
Right I saw that 2 captcha in 3 minutes

**Comment by officiallytook** [comment]
"Updated Translations" not sure if it was api...doubt it would be a big fuss everywhere

**Comment by ShairaMaex** [comment]
Guys you. Still use the bot that they already gave us the warning?

**Comment by ShairaMaex** [comment]
If u continue they might tect the bot we are using on and they will shut it down if we continue ang persistent on ur doing.

**Comment by ShairaMaex** [comment]
Detect*

**Comment by officiallytook** [comment]
I'm just checking for updates and was just replying here, stopped using the bot as soon as the problems started, knew something wasn't right

**Comment by ShairaMaex** [comment]
They are people uses the bot this might be the reason the bot will be tear down as the niantic are scannding down these bots

**Comment by officiallytook** [comment]
Exactly, if there is no bot, there is no play for me

**Comment by aquibzafar** [comment]
I got 3 ids bann now working on fourth . I gues niantic doesn't bann you till level 30
