### ISSUE TITLE
to pokebot devs

### ISSUE THREAD

**Issue by scottjerbi** [PokeBotPub/PokeBot-Android#231]
is there a release date for the new version? are the new version coming sooner ? thanks for the good work in advance

**Comment by Buddhdism** [comment]
33

**Comment by Buddhdism** [comment]
5 sc.

**Comment by ShairaMaex** [comment]
There no update yet from the dev :) patience is virtue my friend ❤

**Comment by scottjerbi** [comment]
yeah ur right guess imma keep waiting
