### ISSUE TITLE
Waiting for update

### ISSUE THREAD

**Issue by ZiNT3X** [PokeBotPub/PokeBot-Android#233]
Hi, I bought an automatic captcha to pokébot and now I noticed that not be used to update the threatened ban, so I'm probably not return unused days at the captcha? 
Sorry for my english. Thanks.

**Comment by ShairaMaex** [comment]
We Gave already a warnin for this :) 

Dont use bot Ban risk it was warnin we already established on. 

Please be patience for waiting for the update and we are still working on it :)

**Comment by pokeguy23** [comment]
How about the autocapcha hours runing and iam not using it or only hours go down if u use it thanks

**Comment by ShairaMaex** [comment]
I diddnt encountered that problem yet. Autocap looks doing good. U can set it on the settings :)

**Comment by ShairaMaex** [comment]
I dont know what way Will be the refund. But stay tune for the update :) ty

**Comment by mbar666** [comment]
Kami butuh pokebot

**Comment by mbar666** [comment]
We need pokebot

**Comment by ZiNT3X** [comment]
Ok, no problem i Will wait to update but time is money :P pls do it Fast thx :D

**Comment by ZiNT3X** [comment]
I go translate bot to my lang, idk what to do So im boring but i cant go outside play coz im ill.(: Translate to Czech i Will make this day.

**Comment by ShairaMaex** [comment]
Good , thanks for translating it

**Comment by ZiNT3X** [comment]
traslated and sended
