### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by ahkam067** [PokeBotPub/PokeBot-Android#235]
The problem is that no usable pokestop was found. I am expecting an immediate reply, thank you.

**Comment by ZiNT3X** [comment]
Its maybe problem with Captcha, you can solve it if u start Pokémon Go, and complete captcha.

**Comment by OmnitronSystem** [comment]
Its definitely problem with captcha, i even bought a auto-captcha thing , but it still doesnt work properly, so bot will work until you get auto captcha / manual captch ( it doesnt matter ) notification.

**Comment by ahkam067** [comment]
I solved the problem, the clocks were not taken back in the country I live
in. I got back the clock 1 hour back trouble was many thanks very much good
work

1 Ara 2016 16:19 tarihinde "OmnitronSystem" <notifications@github.com>
yazdı:

**Comment by ahkam067** [comment]
I solved the problem, the clocks were not taken back in the country I live in. I got back the clock 1 hour back trouble was many thanks very much good work

**Comment by OmnitronSystem** [comment]
So you can now run bot for more than lets say 3 hours ?

**Comment by ahkam067** [comment]
Google Translations Dedicated language set in turkish.
Galiba ikimizde farklı problemler den bahsediyor olabiliriz. Dediğini
anlayamadım. Ve şuan senin problemin ile bende ilgileniyorum bende
rahatsızım bu durumdan .

1 Ara 2016 22:20 tarihinde "OmnitronSystem" <notifications@github.com>
yazdı:

**Comment by ArthurPetrilli** [comment]
I have recently noticed that when the bot starts up, it recycles my item inventory, only slightly.  When i hit the pokestops, nothing is collected.  I stop Bot stop and i manually have to delete a bunch of potions so the bot can collect more pokeballs.
