### ISSUE TITLE
Request: add IV to Pokémon name

### ISSUE THREAD

**Issue by Thedotfactor** [PokeBotPub/PokeBot-Android#236]
I don't know if it is possible but it would be great if the IV was automatically added to the Pokémon name after each capture

**Comment by ArthurPetrilli** [comment]
Hey, you are putting the horse behind the cart (counterproductive).  The Dev team can't worry about adding IV next to the pokemon name.  They need to take care of the main issues first!  Updating the bot with the current API 47.1.  It is a matter of time, before my throw away account gets zapped (banned), b/c i am still using the bot which runs on API 45
