### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by peegee1985** [PokeBotPub/PokeBot-Android#238]
Err... Non of the captcha options are working. Ok, im not gonna buy the auto thing bcs its not working either, according to the posts here. But thr manual captcha resolve is not working. I have to log in in game And resolve the captcha There. The bot is not usable this way. Sorry. And yeah...the captcha pops up every 5 minutes. Making this apk Worth uninstalling. And making my account flagged again And again. Ugh.

**Comment by ArthurPetrilli** [comment]
Yesterday, i got a few notifications about manual captcha.  As the bot ran longer, i stopped seeing manual captcha popups, so i checked my bot to see what it had been catching.....nothing!!!!  Stop bot, manual log in, and Hello Captcha check!!!!!  Wash rinse, cycle, REPEAT!!!  Before ending my session yesterday, i logged in manually for final check....no captcha...  The next day, i had this feeling to manual log in first, Hello captcha...Nice to see you soooo early in the morning and i did not even take my bot out for a walk.....what a coincidence!!!!  Someone needs to throw a bone at Niantic's security algorithms!!!!!  Already on top of me and i was just playing manually, first thing in the morning!!!! [used throwaway acct....not main acct until new prog is up and running]
