### ISSUE TITLE
update status and autocaptcha

### ISSUE THREAD

**Issue by pokeguy23** [PokeBotPub/PokeBot-Android#241]
How long more for the update and the sutocaptcha not working i have to close pokebot open pokemon go do the captcha manuly then go back to pokebot works for 15 secons then i get looted no poke stops found pokemon flees then close pokebot again have to open pokemon go to do the captcha thing again please fix fast thanks can get pokeballs too

**Comment by pokeguy23** [comment]
And i only have like 80 hours left u ask not to use the bot hours went down. I was at 400 hours left 4 days ago i dowloaded 1.29.0 it says 80 u should add a future. That the hours only run when runing the bot

**Comment by peegee1985** [comment]
Its simply not working. Wait for update.

**Comment by pokeguy23** [comment]
And i only have like 80 hours left u ask not to use the bot hours went down. I was at 400 hours left 4 days ago i dowloaded 1.29.0 it says 80 u should add a future. That the hours only run when runing the bot
