### ISSUE TITLE
new update 0.49.1

### ISSUE THREAD

**Issue by pokeguy23** [PokeBotPub/PokeBot-Android#245]
Is it safe to use the bot new version out 0.49.1
I havent update my account to 0.49.1 dont want to get ban please let us kno

**Comment by officiallytook** [comment]
I only got when api is not forced update...

So now no not until .47 and then still iffy due to .49 being out now...I believe it was forced too...

So I wouldn't bot til .49 is out

**Comment by ArthurPetrilli** [comment]
I attempted to run the bot this morning at work.  The manual captch popped up like a Bxxch.  In a span of 5-7 minutes.....all i saw was one captcha check after another....I shut the bot down.  I logged in manually and was forced to update to the latest 0.49.1
