### ISSUE TITLE
Google or PTC servers do not respond, check server status.

### ISSUE THREAD

**Issue by iaecengcvl** [PokeBotPub/PokeBot-Android#249]
"Google or PTC servers do not respond, check server status"

Has anyone else gone through this or did they find a solution?

**Comment by pokeguy23** [comment]
That means ur ban did u download 1.30.0

**Comment by OmnitronSystem** [comment]
Try it again, i am getting this error sometimes but only once, second try is without problems...just lick start again and it should work

**Comment by BangMet** [comment]
Your account suspended..  say goodbye.. just make new pogo account..
