### ISSUE TITLE
This project dead or what? 

### ISSUE THREAD

**Issue by peegee1985** [PokeBotPub/PokeBot-Android#264]
Its been a long time since we got something useful from here. Does this silence mean that this app is dead?

**Comment by ShairaMaex** [comment]
Good Day User, The Project is still on going.
but we diddnt have anyluck yet on the current API, We still waiting for the
API to come out. Please be Patience our developers are working on it.

    -SM SHAIREX

**Comment by slapinpickle** [comment]
Good to know you're still on the case

**Comment by BangMet** [comment]
We r still waiting for d good news..

**Comment by DineshSs7** [comment]
Please add gym battle option on bot

**Comment by ShairaMaex** [comment]
Good Day User, We Still dont have any update. they diddnt release yet the
new API. :) S

Sicerly SM, ShairaX

**Comment by peegee1985** [comment]
...for money...really? This is the end.
