### ISSUE TITLE
Monthly Paid for Poke Key?? 

### ISSUE THREAD

**Issue by BangMet** [PokeBotPub/PokeBot-Android#266]
USD10 everymoth? Pls do something.. Pokebot can we used previous version v1.0.30?  Or hav to say goodbye pokebot.. 😢😭

**Comment by ShairaMaex** [comment]
YES, CURRENTLY WERE HAVING THIS FOR THE SAFETY OF THE BOT AND ITS USERS.

**Comment by BangMet** [comment]
Can we use free version pokebot? How?

**Comment by ShairaMaex** [comment]
currently were not giving the free version of it as this moment thank you

**Comment by BangMet** [comment]
Noted.. Just waiting d good news from pokebot free. TQ

**Comment by ShairaMaex** [comment]
Sorry for the inconvenience,

**Comment by slapinpickle** [comment]
Why so high you can get a hash key for a 3rd of that price!

**Comment by ArthurPetrilli** [comment]
Hmmm, can we cancel the subscription when Niantic changes the API again?  I do not like monthly subs!!!!  I rather pay as i go if i am gonna pay for something.

**Comment by ShairaMaex** [comment]
no you cant.
