### ISSUE TITLE
if i pay for the key

### ISSUE THREAD

**Issue by pokeguy23** [PokeBotPub/PokeBot-Android#267]
If i pay for the key will pokebot be safe to use i dont want to get ban ism on level 33 please let us kno thanks

**Comment by ShairaMaex** [comment]
yes it will be safe, but put it on a limit . if ur using to teleort to
places. like giving it a rest. and put it on slow not fast . please any
concern. feel free to reply ty

**Comment by pokeguy23** [comment]
Can give me the opions how to use it like speed distanse hours of play

**Comment by pokeguy23** [comment]
And thanks

**Comment by ShairaMaex** [comment]
YES SURE, ILL  GIVEYOU  A SCREENSHOT OF. THE SETTING . PLEASE GIVE ME UR
EMAIL SO I CAN SEND IT TO YOU. TY

**Comment by pokeguy23** [comment]
Djestilo1@yahoo.com

**Comment by TigerTheDark** [comment]
Hi ShairaMaex , can you pls send me a screenshot of the settings ti my mail? (wool466@gmail.com)
Thank you in advance!
Pokebot4life<3

**Comment by BangMet** [comment]
I need the screenshot setting too.. amiranymedia@gmail.com

**Comment by someonerich** [comment]
Already paid. Need this config screenshit too. Send to papkgotkd@gmail.com

PS:wasnt supposed to be add free after payment?

**Comment by featherpiece** [comment]
Hi. Can you send it also to me.

featherpiece@gmail.com

Thank you
