### ISSUE TITLE
Y pushased the key but

### ISSUE THREAD

**Issue by DanDiscoversYT** [PokeBotPub/PokeBot-Android#269]
Dude fix it y pushased the key and y entered started it and the only thing that farms is eggs and pokestops with eggs no items no nothing just eggs and it doesn't catch pokemon I'm very dissapointed fix it

**Comment by ShairaMaex** [comment]
did u already purchase it?

**Comment by DanDiscoversYT** [comment]
Yes I did

**Comment by DanDiscoversYT** [comment]
Look

**Comment by DanDiscoversYT** [comment]
It's OK it's already working thx
