### ISSUE TITLE
Bug+suggestion

### ISSUE THREAD

**Issue by Stl2egaX** [PokeBotPub/PokeBot-Android#27]
Bug report 1.0.14

- bot won't walk indoor (eg. Shopping mall), it always walk and loot pokestop along road and sometime it freeze when face water edge.
-you can add something to auto-transfer list but you can't delete them!
- auto evolve pokemon button bug alway yes(Fixed)
- Use xxball below catch probability isn't work, when set a value it always reset to 0
- Current pokemon count sometime show 0,1,2 
- Pressing Auto transfer list button on first page resulted to reset all transfer list you have made.
- Player stats is all 0 value, bag too.

Suggestion
- manually create a route for botting
- add a rest at pokestop (or anywhere) option after some period of using
- multi walking speed (eg. Walk at speed 1 for 30sec. then walk at speed 2 for 30sec.)

Thanks for your great work!!

**Comment by Stl2egaX** [comment]
Bug updated!

**Comment by Dominican2013** [comment]
Cant sign in with google account.


[Lorg.apache.http.Header;@400303d 

Error=NeedsBrowser Url=https://accounts.goog|e.com/ signin/continue? sarp=1&scc=1&continue=https:// accounts.goog|e.com/o/ android/auth?hl%3Den_us %26xoauth_disp|ay_name %3DAndroid%ZBLogin%ZBService %26source%3DAndroid %ZBLogin&plt=AKgnsbsuQS ch46q8PQJufaHe071GbgK8W6-0XyTzXWz1_3nSth5C_W VbcT3FfdPES30H908COAquJeJFCPpGPgm1up2eK61TOYXQ|LkG3K JXF76eBMugVCstfVK_gBXv5t6m-3 URVOhv2UB7uvi8|Y|20HuvyAg4iU8T IOthYBYL828k1q_g50me4GrHjB7v 6yprcOkijwsk78qsyQYmdi||t09NY NoO6_e403CT1YxX8 

ErrorDetai|=To access your account, you must sign in on the web. Touch Next to start browser sign-in.
