### ISSUE TITLE
No issue please read?

### ISSUE THREAD

**Issue by K1N6C0RY** [PokeBotPub/PokeBot-Android#277]
I just wanted to thank you guys/gal's for all y'all's hard work and I will continue to use this service for as long as it last, PS I have never had an issue with this service and that is awesome, thanks again....,!

**Comment by cj3n** [comment]
Oh yes, pay 10 bucks a month t get permanently ban if you don't know what you are doing. Idc waste your money. I call fake post above

**Comment by K1N6C0RY** [comment]
You mentioned PC bots were free, So my question to you is "What the hell are you still here for?"

                                                Thanks

**Comment by Pokebotter** [comment]
Good for you if you did not have any problems. I didnt even get a code but was atill charged. Also no reply from them when I sent them emails.
