### ISSUE TITLE
autocapcha not working plus ads

### ISSUE THREAD

**Issue by pokeguy23** [PokeBotPub/PokeBot-Android#278]
Autocapcha is not working fix every 3 min it says looting fail possiblesoft ban iam a speed 5 plus it said pay forno ads i still get ads

**Comment by officiallytook** [comment]
Bump

**Comment by PokeBotPub** [comment]
We forget ads in one place. We will delete it in new release. You can make more slow bot speed for looting fails. We are working on make better.

**Comment by cj3n** [comment]
There are still ads in 31 and no matter what speed you set you will get soft ban.
