### ISSUE TITLE
fix the problem people getting ban

### ISSUE THREAD

**Issue by pokeguy23** [PokeBotPub/PokeBot-Android#279]
I was checking on status the point jumps back and foward keeps going to the same poke stop please fix fast i pay for something that should work thanks

**Comment by ShairaMaex** [comment]
it was already posted about the bot risk, and its still on progress about
the bugs.

**Comment by pokeguy23** [comment]
Ok so is not safe to use it yet when would it be ready i got 2 accounts ban already

**Comment by ArthurPetrilli** [comment]
What!!!! You got two accounts banned using the latest bot (API .51)????  I have been using the latest bot for 3 days in a row now.

**Comment by cj3n** [comment]
It's risky so buy it, come on buy it, ha what a joke
