### ISSUE TITLE
An idea to avoid fleeing pokemon

### ISSUE THREAD

**Issue by localhost127001** [PokeBotPub/PokeBot-Android#28]
I think the best formula (for now) would be to get items at pokestop first, to check if you get softbanned so you can get unbanned. And only after that you collect nearby pokemon. just an idea

Thank for your great work

**Comment by PokeBotPub** [comment]
We will add few options on catch settings.

**Comment by localhost127001** [comment]
I'l try to give you my situation
I've been sniping for specific pokemons that require me to jump location
Everytime i did it, i got softbanned (as expected) and thus got the "the fleeing pokemon"
If only when the app start (for the first time only) it goes to nearest pokestop first instead catching the nearest pokemon it would help people that trying to snipe particular pokemon and saves up some pokeball and berries for others too
The rest of your code is perfect

**Comment by PokeBotPub** [comment]
Our PokeSniper application is release as soon. It will the greatest capacity Pokemon GO sniper application.

**Comment by localhost127001** [comment]
That would be amazing
I asked one thing and you gave me something better than my original request!
Keep up the amazing works
