### ISSUE TITLE
Charged for Code but no Code Received

### ISSUE THREAD

**Issue by Pokebotter** [PokeBotPub/PokeBot-Android#280]
I purchased the 1 month subscription code and after I was charged it showed me an error saying to contact pokebot2018@gmail.com. I sent you guys a message already (twice) but there's still no reply and still no code. I had been using pokebot for a while now and I hope I can still use it so please send me the code or at least refund me the money.

**Comment by ShairaMaex** [comment]
i thought have refunded it already? you comment at a previous issue post.

**Comment by PokeBotPub** [comment]
We are receive so many e-mail. Please attach payment proof in the mails.
Have fun!

**Comment by Pokebotter** [comment]
What payment of proof do you need? The confirmation email from google pay? And Shaira I did not post anywhere that I was already refunded.

**Comment by Pokebotter** [comment]
I sent an email with the google pay attachment now. Please check.

**Comment by Pokebotter** [comment]
Got the code. Testing it right now. Thanks guys.
