### ISSUE TITLE
pokebot not working

### ISSUE THREAD

**Issue by pokeguy23** [PokeBotPub/PokeBot-Android#281]
No pokemons keeps on going crazy back and foward please fix or refound money the hours are runing thanks i kno u guys r working hard but looks like HashBuddy service is not working good

**Comment by PokeBotPub** [comment]
Please try another location. We are detect 3000+ fake payments. Bot is better now.
Have fun!

**Comment by pokeguy23** [comment]
Still the same no pokemons change locations

**Comment by pokeguy23** [comment]
Working now had to reset pokebot
