### ISSUE TITLE
We need Pokebot free version.. pls 

### ISSUE THREAD

**Issue by BangMet** [PokeBotPub/PokeBot-Android#282]
Pls do something pokebot..

**Comment by officiallytook** [comment]
Yeah because paid version might as well be free with soft bans not catching Mons and auto capcha not working

**Comment by ShairaMaex** [comment]
we are not forcing anybody to buy it. so dont use it. and use pc bots. if u
like too. u have a choice.

**Comment by officiallytook** [comment]
I understand, but don't advertise the purchased feature, when it's not operating properly or sufficient ... so basically, don't pay until you guys get the kinks out... that's fine by me

**Comment by ShairaMaex** [comment]
We are doing the best to fix all the bugs within the bot, unfortunately
people are demading to release the bot earlier as we expected. so dont
blame us, and its optionally to use the bot amd bo
uy the key :)

**Comment by officiallytook** [comment]
Yeah but the capchas can you have them pop up within the bot, so we don't have to open Pogo?...


+my apologies, I didn't know folks were horny on the bots release...should have known lol...

**Comment by ShairaMaex** [comment]
I have that Noted.
thanks for understanding,

**Comment by BangMet** [comment]
I dont have PC.. just use android bots.. hemm we need free version.. hope u can release free version  soon.

**Comment by ShairaMaex** [comment]
we are not releasing the free version yet.

**Comment by aquibzafar** [comment]
@shairamaex so can we be assured that Sooner or later you guys would provide us with a free version of pokebot ? please !

**Comment by BangMet** [comment]
@ShairaMaex thats mean pokebot free version will release soon?? Thanks Pokebot.. 😘😘

**Comment by ShairaMaex** [comment]
no dates yet for free version of it so stay tune of it :)

**Comment by BangMet** [comment]
Noted..  will wait until Free Version Pokebot release.. Tq

**Comment by cj3n** [comment]
Let's pay for something that doesn't work properly, seems smart.

**Comment by cj3n** [comment]
There free version would probably either be a trial or so limited or pointless to even download.
