### ISSUE TITLE
Pokebot settings or screen of settings

### ISSUE THREAD

**Issue by freepomp** [PokeBotPub/PokeBot-Android#283]
Hello, how should I set up the pokebot program. How many hours a day should I run a bot. Anyone can email (fcukforpussy@hotmail.com) me the screenshot of the settings. Thank you

**Comment by freepomp** [comment]
Is there anyone who can help me?

**Comment by pokeguy23** [comment]
Iam using speed 4 distance 1150 and the last one 5000 turn off location to use bot. If u want to teleport to difrent place wait atleast 24 hours

**Comment by freepomp** [comment]
Thank you for the answer. How many hours run pokebot per a day.

**Comment by ShairaMaex** [comment]
7-8 hrs a day.

**Comment by Mtin096** [comment]
7-8hrs. a day using pokébot ??? :o

**Comment by cj3n** [comment]
Only 7-8 hours a day for 10 a month
