### ISSUE TITLE
Travel Path

### ISSUE THREAD

**Issue by ArthurPetrilli** [PokeBotPub/PokeBot-Android#284]
Can you include some form of boundary for the bot to travel within.  I want to hit the spawn spot in my area but the bot keeps going outside the area of the spawn spot.  For example, can it walk around the lake without deviating more than 50 feet from the boundary.

**Comment by officiallytook** [comment]
Bump NYC central Park lakes

**Comment by K1N6C0RY** [comment]
Like outline your neighborhood and bot stay's within that area...

**Comment by officiallytook** [comment]
Right or be able to read coordinates from a .txt file. Like long + lat only

**Comment by ArthurPetrilli** [comment]
Okay!!!!  Today, I went to the park b/c the freaking bot will not stay in the park to catch the pokemon at the spawn spot!!!!!   AAAggggghhhhh!!!!!  .....i have the distance set to min....of 500m.  It would be great if pokebot can record my actual trip around the park and run the path at a later time.....WISH LIST!!!  Make it happen!!!!
