### ISSUE TITLE
fix no pokemon

### ISSUE THREAD

**Issue by pokeguy23** [PokeBotPub/PokeBot-Android#285]
Bot works but no pokemon just poke stops fix please was working ok yesterday now only poke stops

**Comment by pokebothelp** [comment]
What is your key bro?

**Comment by pokeguy23** [comment]
I cant put the key here evryone would see

**Comment by pokebothelp** [comment]
Pokebothelp@gmail.com

**Comment by pokeguy23** [comment]
I send it

**Comment by pokebothelp** [comment]
Your key are valid,send me your setting

**Comment by pokeguy23** [comment]
Send

**Comment by pokebothelp** [comment]
Try to unstalle and reinstalle pokebot and clear cache.

**Comment by pokeguy23** [comment]
Did still just poke stops no pokemon

**Comment by pokebothelp** [comment]
Do you have ball?free storage? Allow bot to catch pokemon?

**Comment by ShairaMaex** [comment]
good day, Email your key for vaildation. viergeverola@gmail.com thanks

**Comment by PokeBotPub** [comment]
Don't send your keys anywhere. Support mail only pokebot2018@gmail.com !!! Pokebothelp@gmail.com is fake!!!
