### ISSUE TITLE
Softban

### ISSUE THREAD

**Issue by Damarul** [PokeBotPub/PokeBot-Android#287]
Hi i'm buy pokekey for pokebot, and i have always softban when i'm take the pokestop. It's normal? Can i have a ban with my account?

**Comment by pokeguy23** [comment]
Use speeds 5 if you go to fast you get softband and dont teleport difrent locations wait aleast 15hours to 24 to teleport or you get ban

**Comment by pokebothelp** [comment]
What is your key? Use 9 speeds and 1000range

**Comment by pokebothelp** [comment]
Try to unstalle and reinstalle pokebot and clear cache.

**Comment by BangMet** [comment]
@Pokeguy23 can u share pokebot setting?

**Comment by ArthurPetrilli** [comment]
I have used two different accounts on two different devices.  ran bot for about 10-15 minutes.  I have noticed the msg unban (3x) for a few pokestops.  I clicked on the stats and noticed the icon flying away from the designated location on both devices.  I stopped bot and shut down the device.

**Comment by ShairaMaex** [comment]
its ur speed causes the softban and ur distance make it lowest settings.

**Comment by ArthurPetrilli** [comment]
my speed was on 3 and i moved to 1.  My distance was 1500 for 4 days in a row.  Today, is the first time i am seeing these problems

**Comment by ArthurPetrilli** [comment]
Okay.  Still NO Go!!!!  My speed is at 1 km and distance is as low as can be.  I have tried a different acct.  My icon is still flying off to ....I do not know....the icon is going over water....this is alarming.  I had to shut bot down.

**Comment by ShairaMaex** [comment]
can give me a screenshot of it? send it on my personal email?
viergeverola@gmail.com. i might help u

**Comment by ArthurPetrilli** [comment]
screenshots sent.  I have used a total of 3 accts.  One acct managed to catch a few pokemon....then nothing.  Another acct collected from the pokestops but did not catch any pokemon.  3rd got nothing.  All accts eventually showed the bot travel more than the allocated distance allowed, 500 m.  I watched the stats window.  It look like i got in a car or plane and drove over the lake and traveled several miles from spawn spot

**Comment by ShairaMaex** [comment]
I got your email :) ll be replying soon. as possible. thanks

**Comment by cj3n** [comment]
You got soft ban because that's what bots do just like spoofing. No what speed or distance, guess what still soft ban. Whoever pays for this is wasting their money. I've been running a free pc bot for days now over 2 million xp in a little over a week and I also get mad candy and eggs done.

**Comment by pokeguy23** [comment]
Pokebot working good i open a new pokemon account yesterday iam on level 26 no problem yet turn off location to use bot iam using speed4 distance 1150 and the last one 5000.

**Comment by ShairaMaex** [comment]
becareful dont let ur acc be lvl20 in one day. it will be ban.

**Comment by ShairaMaex** [comment]
You're invited to my new group "PokeBot Help Desk:) users" on GroupMe.
https://app.groupme.com/join_group/27845062/82aI1u for further help :)

**Comment by ArthurPetrilli** [comment]
I forgot to say "Thank You" 
The issue was cleared up.  I am kinda wondering why i have to keep verifying my google account when i manually log into multiple devices when playing manually.  One of my accounts made me do a Captcha check....i thought pokebot had built in autocaptcha check in place.
