### ISSUE TITLE
PokeKey is Invalid

### ISSUE THREAD

**Issue by ArthurPetrilli** [PokeBotPub/PokeBot-Android#289]
What is going on???  I have Pokebot on 2 phones, 1 tablet, 2 laptops (Bluestacks emulation)

My laptop indicated an error with my account being removed from bluestacks and that i had to reset.  I reinstalled pokebot and discovered my PokeKey is invalid?????

Okay.....so i went back to playing on my cell phone and discovered that it too had an invalid PokeKey.

I am confused.  I thought that i was allowed to use my PokeKey on 5 devices.  What am I going to do if my 3 other devices have issues where i have to uninstall and reinstall Pokebot????  Now that i think about it, When i complained about the softban....i did uninstall and reinstall my pokebot (same PokeKey)

**Comment by ShairaMaex** [comment]
try to check valid ur key :) it happen to me :)

**Comment by ArthurPetrilli** [comment]
After i reinstalled Pokebot, i re-entered the PokeKey.  I have tried several times.  It says my key is invalid.  I wrote it down on paper.  I thought i wrote it down wrong....i checked my other cell phone, the one that still runs Pokebot, and i made no mistakes re-entering the code.

**Comment by ShairaMaex** [comment]
You're invited to my new group "PokeBot Help Desk:) UNOFFICIAL" on GroupMe.
https://groupme.com/join_group/27845062/82aI1u will have little chitchat.
about this

**Comment by Pokebotter** [comment]
It happened to me too. Just validate the pokekey again on settings and it should be fine.

**Comment by ArthurPetrilli** [comment]
Nope.  Did not work.  I can only run pokebot on 1 laptop (bluestack).  It use to be able to run pokebot on both laptops.

**Comment by PokeBotPub** [comment]
Hello,
Please payment proof forward to us.(E-mail invoice or payment screenshot).
E-mail : pokebot2018@gmail.com
Have fun!
