### ISSUE TITLE
Prem have timeout? 

### ISSUE THREAD

**Issue by AbiDez** [PokeBotPub/PokeBot-Android#290]
Hello pokebot devs, please tell me something... 
I would like to buy Prem, I take a look on the donate us app.. 
I read something about 10$ per month for Auto Captcha. 
1st is this app for actual Prem, too? 
2nd Every month 10$ for Prem, please explain, or I misunderstood something?

**Comment by ShairaMaex** [comment]
1. payment app or u can say as a donate app
2.10$ this the subscription for pokebot this the only way u can use the
bot. as for this moment.

-ShaireMaeX(VCS)

**Comment by AbiDez** [comment]
English is not my base language sorry. 
Ok, so the only way to use the bot atm is to pay with bitcoins? 
How can I pay for a running bot? 
With PayPal? With play Store app?

**Comment by ShairaMaex** [comment]
yes. u can pay with it paypal. app will directs to u paypal .:
