### ISSUE TITLE
I need donate every month?

### ISSUE THREAD

**Issue by rafaelsouzams** [PokeBotPub/PokeBot-Android#294]
I understand the motives of the pokebot need donation to work, but I wonder if I need to donate every month to access the app, or only once will allow me to always use the app?

**Comment by Mtin096** [comment]
you need to pay every month :/

**Comment by cj3n** [comment]
Money hungry for broken software

**Comment by ShairaMaex** [comment]
i can't bashing?

**Comment by ShairaMaex** [comment]
you can't stoo bashing? correction from my previous comment.
