### ISSUE TITLE
Pokemon Go has been updated

### ISSUE THREAD

**Issue by Mtin096** [PokeBotPub/PokeBot-Android#296]

**Comment by ArthurPetrilli** [comment]
Hmmmm, Google Play Store still only offers version 0.51.0.  When they update, i will stop using pokebot.  Thanks for the heads up.  I will be looking for the update.

**Comment by AbiDez** [comment]
Me, too... Good to see that... After 4 days botting comes new update... Shit

**Comment by ArthurPetrilli** [comment]
I have just logged in to pokemon go.  I am still running 0.51.0.  It has not forced me to upgrade to 0.53.  Does this mean i can still run pokebot?

**Comment by AbiDez** [comment]
I run it so long no update is needed.. Check every half hour of pogo because in Germany comes update 2h ago in Playstore

**Comment by pokeguy23** [comment]
0.53 out poke botters becareful dont use pokebot if u update to 0.53...  ... aslong u dont update u could use pokebot. Ban risk if u update to 0.53 thanks

**Comment by pokeguy23** [comment]
I update so now i have to wait for new update from the devs of pokebot

**Comment by ArthurPetrilli** [comment]
North America, the update the new version 0.53 is available in playstore.  Poke Go is not forcing the updates like in they have in the past....poke is still on

**Comment by Mtin096** [comment]
Yeah, still using pokebot

**Comment by AbiDez** [comment]
Update ... 
In Germany we have to update to new Pogo 0.53... Login not possible with 0.51...
So we need new bot? oO

**Comment by ArthurPetrilli** [comment]
Wow!!!  It's a good thing i do not run pokebot while i am sleeping!!!!  I woke up this morning @ 3:30 am.  Low and Behold......Niantic has forced the new update 0.53 the moment i ran pokego on my tablet.  
Orlando, Florida, USA
Time to stop using Pokebot until the new update

**Comment by Mtin096** [comment]
Thank you !!

**Comment by TigerTheDark** [comment]
Any update from the devs? Thanks in advance

**Comment by Ajoi1986** [comment]
need opinion from you guys
is this some sort of ban? I opened PoGo using my smartphone and I got a freeze screen with nothing to clicked just like this. I tried uninstalling and reinstalling PoGo few times and the same freeze screen keep happening. Any idea?

![8](https://cloud.githubusercontent.com/assets/24926002/22139532/8d22a4ae-df21-11e6-85b6-a606e88b1a13.png)

**Comment by ArthurPetrilli** [comment]
When i use to use the free version of Pokebot, A similar screen would pop up to prove that i was not a bot (manual captcha check).  Have you tried using a different device?  Did you upgrade to the latest pokemon go version on your phone, 0.53.1? In the past, Niantic sent me a clear msg that i was using 3rd party app and that i needed to stop.  You may also want to check your google acct updates on phone....suspicious activity....blah blah blah.....i would verify that i logged in with the device in question.

**Comment by pokeguy23** [comment]
There is a ban risk now but check ur internet turn off location and turn it back on again when using the bot make sure u have location off to prevent softban

**Comment by AbiDez** [comment]
Update...
