### ISSUE TITLE
R.I.P.

### ISSUE THREAD

**Issue by AbiDez** [PokeBotPub/PokeBot-Android#298]
Hello everybody, today is a bad day for us... 
One of us is going away.... Take a minute ^^
![screenshot_20170121-173025](https://cloud.githubusercontent.com/assets/21013947/22175962/55e63b38-e000-11e6-870e-4e10f9acb476.png)
![screenshot_20170121-173042](https://cloud.githubusercontent.com/assets/21013947/22175966/646535b0-e000-11e6-88f7-92822d8f31c0.png)

Backup... But one GPS jump, from one end of the town to other... I don't know.. Please devs check GPS because this was my 1st jump, but it's not so good when I walk in town, and the bot is jumping over a sea...

**Comment by Pokebotter** [comment]
Does that message mean its banned?

**Comment by AbiDez** [comment]
Definitely Yes ^^
I have this 1time since 7.7.16 and this was a Google account..
This account is last botting 3 days ago... My backup account, and he jumped I don't know why while boting over the sea.. 
Pam softban spinning 56 the wheel... 
Every other account runs fine

**Comment by ArthurPetrilli** [comment]
R.I.P
My 2nd strongest account (of 5) got the same screen.  I do not even feel like walking my main account around the park today!!!!!  Its strange....i ran 3 acct at the same time on different devices.....i only got manual captcha checks on the other two accts when i logged in manually.

**Comment by AbiDez** [comment]
It's bad that the log of Pokebot is so small, so we can't see what is going on in the past. 
For me I think it's the GPS jump, but it's only 1km jump... 
I'm a little bit confused how ghost happens.
Its better to use bot without GPS and WiFi (my way) 
Without GPS and mobile data 
Without GPS and mobile data + WiFi (that makes the jump I think?

**Comment by ArthurPetrilli** [comment]
R.I.P. Main Account....Level 36 had some kicks ass pokemon maxed out for that level.  Just like clockwork, I log pokebot in for about an hour a day.  I kept my eye on the gps to  make sure it was not bouncing around.  Today, I log in and i get that msg "Failed to get game data from the server."  Yet i have 2 minor accts Level 32 running on two other devices.  I do not understand why my level 36 acct was terminated and not my level 32's.  Without my main and 2nd accounts.....I am DONE!  Those were the accounts i had started back in early August.  My minor accts were started in December....I am surprised they did not terminate the level 32's.......
All said and done,  I am FREE from Pokemon Go!!!!!!!  I have lots of anime to catch up on....PlayStation games collecting dust,  BlueRay movies that are stacked in the living room, piratically building a wall behind the couch.  Losing my 2nd account was like losing a child.....Losing my MAIN acct was liberating!!!!!  Cause now i just don't give a Fxxk.

**Comment by xlenyskyline** [comment]
I definitely banned in my account, I recommend do not use pokebot now. I think our accounts has been terminated and locked permanently.

**Comment by ArthurPetrilli** [comment]
My kids were expecting me to take them to the park to play pokemon go.  Broke the news to my kids.  Daddy is done!!!!!  I have deleted Pokemon Go from 3 cell phones and two tablets....they happen to be all Samsung devices....Dontcha watch the news....the battery might explode :P

**Comment by ArthurPetrilli** [comment]
Haha.....there is a snitch in this room or Niantic is snooping.  I got on the wife's cell phone....turns out my other two minor accts....level 32....also banned.....i only ran the bot  for 10 minutes when i realized my main acct was banned.  The only acct not banned was the wife's.....yes.....ban her too so she can let this game go as well :P.  The wife was pist....she wants me to start a new acct.....not gonna happen.....i have played legit til level 28....Niantic let the cheaters go rampant for sooooo long before i started using the bot as well.  Niantic is never going to give players PvP battles, never gonna allow players to trade pokemon with each others....the game is broken.....holding out the possibility that it will keep improving the game....THANK YOU Niantic for freeing me of my obsession :) This is how i felt when Mafia Wars ended after 5 years of playing.....At least I did not play PoGo for 5 years

**Comment by ShairaMaex** [comment]
Good Day, Yes theres a snitch here frequently. comments in the post.

**Comment by peegee1985** [comment]
Umm...what did you expect? That you will cheat uncaught for ever? Niantic is a bunch of hungry asses but they know what they are doing. In general, cheating is wrong. You cheat-sooner or later u get caught. Like in real life. Stop complaining-cheated-banned. End of a story.

**Comment by Burkyman** [comment]
Too bad i payed 115 swedish kronor just to get 4 accounts banned within a week, including my kids main account he's been playing since early september. Just bought him a new lvl 30 account, so he's happy again though. :)
But to be honest, don't use pokebot at all, because you WILL get banned. :(

**Comment by OmegaMutant** [comment]
I am confused!!!!  I have read about the ban wave 6 months ago.  There were emails indicating that players were ban!  What is going on!!!!!  I can't log into my game and it has been almost a week.  There is no email ban from Niantic.  It's like Niantic is telling ppl to KISS OFF!!!!!  Is it possible that our accounts may be suspended for a period of time with a chance of reinstatement if we appeal????

**Comment by scottjerbi** [comment]
Once you get banned/suspended theres no such thing as niantic will
reinstate the account .

**Comment by AbiDez** [comment]
Arghhh... All 3 Accounts gone.... 
LV 27 yellow, 28 red, 35 red main (not bottet) 
These niantic craps.... Send email... No response... 
Send new email -_-
WTF.... Has niantic change their checks to Android ID or IP? 
Grmpf... Don't know what brings the future. 
But this cat and mouse game sucks...

**Comment by AbiDez** [comment]
Hm no edit possible... 
Best thing is, I write in Germany in German to niantic. 
Receive a standard mail in English... Bla bla cheaters, blabla. 
In the mail stands answer in the line above... That's not possible.... Ahhhhhhh.... Sorry I'm a little bit angry

**Comment by OmegaMutant** [comment]
I did not even get an email that i was ban.  This time I will not be personally invested in these accounts....meaning....my ass is not walking shit to no where for this fucking game.....bot all the fucking way.
