### ISSUE TITLE
I'm Prem and have Ad? 

### ISSUE THREAD

**Issue by AbiDez** [PokeBotPub/PokeBot-Android#299]
Hello devs... 
Please tell me, I purchase a 1month Prem... So I have Autocaptcha (We will see) and the ability to use the bot 1 month... (I hope not from 1st to 1st) because I purchased 13th day. 
I have disabled my adblock. I start the bot and see Ad... 
WTF? I found this is not ok... 
When a user is Prem so all things like ad or other limitations have to set disabled...

**Comment by PokeBotPub** [comment]
Fixed ADS problem. Please update to new version.
