### ISSUE TITLE
pokeBot-Android

### ISSUE THREAD

**Issue by OgaaaH** [PokeBotPub/PokeBot-Android#3]
After connected to the server, always disconect

**Comment by fokxy** [comment]
same here.. cant connect to server

**Comment by qithub** [comment]
We will update is soon.

**Comment by PokeBotPub** [comment]
We will release new version is soon.

**Comment by namecwarrior** [comment]
Sir, how to fix can't connect to server? Is the server down right now? Please help me. Thank you.

**Comment by PokeBotPub** [comment]
Pokebot server is down. We make big changes.  We testing and fixing bugs today.

**Comment by PokeBotPub** [comment]
New version is released.
