### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by K1N6C0RY** [PokeBotPub/PokeBot-Android#300]
App is crashing on start up

**Comment by ShairaMaex** [comment]
Advising you not to use the bot at this moment. ban waves are frequently.
reported from my feedbacks.

-ShairaMaeX.

**Comment by peegee1985** [comment]
Advising you to pay 10$ a month and not use the bot. Oh yeah.

**Comment by ShairaMaex** [comment]
not u again. cj.  ur still bashing up yeah.duration time left from your
subscription will be place as hold. then please screenshot and the reciept
from the payment.

**Comment by K1N6C0RY** [comment]
These people act like $10 is alot of money, get off the game and go get a job...

**Comment by ShairaMaex** [comment]
who are pointing at.
