### ISSUE TITLE
Stop using pokebot

### ISSUE THREAD

**Issue by pokeguy23** [PokeBotPub/PokeBot-Android#301]
Ban risk 80% i just lost my level 37 account this is the end for me iam not botting no more they said is antiban if u fallow the rules still got ban content://media/external/file/51759
content://media/external/file/51760

**Comment by pokeguy23** [comment]
Play only 10 mins

**Comment by pokeguy23** [comment]
Just found out why i got ban poke bot is running api 0.53.1 Niantic update the api pokemon go is now 0.53.2 becarefull dont bot today they maid the update

**Comment by PokeBotPub** [comment]
PokeBot updated.
