### ISSUE TITLE
Niantic trap to botters new update 0.53.2 new api

### ISSUE THREAD

**Issue by pokeguy23** [PokeBotPub/PokeBot-Android#302]
Niantic has updated there api again you didt get to force to update there been sneaky. 4 days ago update to 0.53.1 today 0.53.2 thats why accounts are been ban dont use pokebot till new update keep checking ur pogo to see if no new updates were install i got my level 37 account ban please becarefull

**Comment by AbiDez** [comment]
Well great news... Lost Lv 35...
FCKNTC

**Comment by OmegaMutant** [comment]
Did you lose the level 35 account even after updated pokebot to 1.33???
