### ISSUE TITLE
Pokemon go update from 0.53.2 to 0.55.0

### ISSUE THREAD

**Issue by OmegaMutant** [PokeBotPub/PokeBot-Android#303]
A new update!  Much sooner than i had expected.  I hope you guys have stopped using pokebot.  The Dev. Team has their work cut out for them....

**Comment by OmegaMutant** [comment]
Man......is this room dead or what?  I lost my best accounts in the last ban wave....i have started 3 new accounts.  Hopefully, I will pay more attention and reach level 40 this time!!!!!!

**Comment by ShairaMaex** [comment]
im still alive bruh

**Comment by OmegaMutant** [comment]
It's good to know that there is still someone still here :P

**Comment by BangMet** [comment]
Hav to stop bot? Not safe again?

**Comment by ShairaMaex** [comment]
its not safe.

**Comment by K1N6C0RY** [comment]
Never was safe, you have to be a ghost to use bots on Pogo...

**Comment by officiallytook** [comment]
Never safe I'm still lurking ... gotta check my ninja accounts...lvl 21-24 only have 4/5 of them will let you guys know...

Meanwhile if you have an HTC device and want to try out a theme... pre release...

spider htc qwen 
https://themes.htc.com/actions/theme/share/com.htc.theme.t4f677aa4-0b25-447a-a744-9b1b8d445657?token=cb0ae6c0-5aa0-414b-a85c-b3083ec344f7

**Comment by PokeBotPub** [comment]
New version released.
