### ISSUE TITLE
Item overload? 

### ISSUE THREAD

**Issue by AbiDez** [PokeBotPub/PokeBot-Android#306]
With new Accounts Items standard is 350, when reach level in real and you loot stop you don't receive items and see message bag full. 
Today I see my bag on test Acc is 795 items, so reach bot the item level the bot ignore this. I'm real it's not possible but because the breaks it? 
In Inventar settings is recycle items after 90% set. 
Is this my mistake or a possible problem?

**Comment by OmegaMutant** [comment]
You may have to tweak your settings.  I had noticed this too b/c my previous accts had 1000 item capacity.  I have reset my items where it throws out all potions and revives  I have lowered my pokeballs to 250 and raspberries to 50

**Comment by AbiDez** [comment]
Thanks... After reset item settings. And new save it works
