### ISSUE TITLE
Every minute transfer same Pokemon? Possible bug? 

### ISSUE THREAD

**Issue by AbiDez** [PokeBotPub/PokeBot-Android#307]
I have a problem on one of my backup accs... As you can see on the image, always same transfer... 
That's not possible because it's my buddy... Magicarp...

**Comment by OmegaMutant** [comment]
your really should not post this image here....there are snitches that come here....leaving an image is just asking for another banwave:(

**Comment by OmegaMutant** [comment]
If you added the Magikarp to your favorites (star), this might prevent that issue in future

**Comment by AbiDez** [comment]
Sorry OmegaMutant... Delete the pic... Thx for answer
