### ISSUE TITLE
Cant pay in donate us app 

### ISSUE THREAD

**Issue by TigerTheDark** [PokeBotPub/PokeBot-Android#309]
Hi guys, IM havin trouble tryin to pay with a Google code card, i added 10us to my wallet and when i try to spend it on donate ya app it says that an error has ocurred ... And i still hace the 10 us un my account.. please help team.
Thanks

**Comment by TigerTheDark** [comment]
Hi again, i managed to contact google's account help desk (call center) , they checked my account and verify that i had no trouble, they even let me to download a paid app and refund my money to verify.... So its up to you guys nos, why i cant hice you muy money XD.... Seriosly, why u.u , i want a code guys please help me out

**Comment by OmegaMutant** [comment]
I am getting the same error.  I have $10.01 in my account.  "Error processing your purchase."  When i try to run poke the msg is "The code is valid but expired???!!!!"  What does that mean?  I am trying to make the payment.

**Comment by TigerTheDark** [comment]
Still not able to purchase pokebot key with my Google play store account money.
Im getting message "Error processing your purchase" every time ive tried, and i dont have credit card to try another way of payment , just the 10$ un my account to purchase pokebot key (yes i bought a Google play money card just for you and you havent reply yet u.u ) please help .....

**Comment by AbiDez** [comment]
Hmmm... Not good... Have to pay in 3 days with Google... Hope that's not a problem? 
But curious you pay $10 but I pay €11
The problem is when I pay today will I lost my 3 days? When I don't lost my days I can make a test purchase?

**Comment by OmegaMutant** [comment]
Hmmm, Did Pokebot just die on us?#@%

**Comment by AbiDez** [comment]
Hmmm.... I'll wait so long with payment with come a response from the devs...
Has anybody sent a support mail?

**Comment by TigerTheDark** [comment]
I did twice, no reply yet, also asked in discord , no reply .....

**Comment by OmegaMutant** [comment]
Pokebot is DEAD and i am not even close to reaching level 40 :(

**Comment by TigerTheDark** [comment]
@ShairaMaex can you provide us some info?

**Comment by OmegaMutant** [comment]
I check this site everyday.  Why are we left in the dark.  I feel like we have been abandoned.  I can't make a donation.  ShairaMaex has deleted her involvement in the "PokeBot Help Desk" (Groupme)
Pokebot is dead R.I.P.  The signs are very clear at this point!  Everyone should look for a different Pokemon Bot :P

**Comment by AbiDez** [comment]
Bot is working with key. But when we unable to receive a new key. We can't use the bot :( that sucks

**Comment by ArthurPetrilli** [comment]
Wow!  Did the developers slip up?????  There is an error when a payment is sent in.  Thus, there is no key.  With no key, there is no pokebot.  I can't believe that this thread was started 5 days ago and the development team has not responded?  I have a real bad feeling about this.

**Comment by ShairaMaex** [comment]
Hi Guys?

**Comment by TigerTheDark** [comment]
Hi, any update información this issue?

**Comment by TigerTheDark** [comment]
*hi, any update info on this issue? (Auto corrector sorry)

**Comment by ShairaMaex** [comment]
im afraid. pokepub shut me down on infos and being scolded to stop being a
fraud chat support. and info from this project. im very sorry for the bad
news.

**Comment by AbiDez** [comment]
Hm... The snitches win? Last 60h then payment time.. That fucked me up... When you have some info Shaira please share it with us. Thanks anyway.

**Comment by ShairaMaex** [comment]
u cound me pm personally at my facebook account.  Xavier Geverola Add me up.

sorry i cant release yet any info about pokebot nor pokepub plans .

**Comment by BangMet** [comment]
Yup.. i just PM.. Xavier Geverola in massager.. fast reply & good info.. all of u.. just text him for update of pokebot.. Tq..

**Comment by AbiDez** [comment]
Any update about payment, it's possible?

**Comment by ArthurPetrilli** [comment]
Hey!  What gives???  I got the notification that version 1.36 is out.  I have upgraded my version.  I hae re-downloaded the "Donate Us" and i still can't pay :( .  When i send email.  Reply is "Send proof of payment!!!!"

**Comment by ArthurPetrilli** [comment]
I have not been able to use Pokebot since Feb 8!!!!!  What gives????

**Comment by ShairaMaex** [comment]
i could help please pm on a fb messenger :) Xavier Geverola

**Comment by ArthurPetrilli** [comment]
Hey Shaira, we already friends on facebook :P.  We chatted last week.

**Comment by peegee1985** [comment]
Haha.   Told ya. Accept money but don't give a shit about developing the app nore helping players with bugs. Everything that starts being "paid" is sooner or later crap anyways. I'm just curious why you guys thought that this fraud could be anything more than "cash up and flee". Long time ago. RIP.

**Comment by ShairaMaex** [comment]
another jealous user 😂. no money no play

**Comment by peegee1985** [comment]
yep. and thats why you suck.

Dne 20. 2. 2017 23:22 napsal uživatel "ShairaMaeX" <notifications@github.com

**Comment by ShairaMaex** [comment]
Lol 😂😂 too jealous

**Comment by uptome007** [comment]
hi

**Comment by AbiDez** [comment]
Hi^^
No one can buy a Prem at this moment I think.... 
The DEV don't need our money he's Richie Rich... 
17 days since start this topic.... 
It's no laughing matter. For me it was the 1st time and last time I pay for this App...
Time to say goodbye 👋

**Comment by ShairaMaex** [comment]
Abidez Goodbye.
