### ISSUE TITLE
Pokebot problem

### ISSUE THREAD

**Issue by alanwong5361** [PokeBotPub/PokeBot-Android#310]
Why it always shown ‘Posibbly PTC or Goggle server down , check server status’ whereas i still can run my Pokemon go very well. Help pls. Tq

**Comment by featherpiece** [comment]
Experiece the same. Can't log in.

**Comment by ShairaMaex** [comment]
its possible that is banned.

**Comment by featherpiece** [comment]
Uhm. But I can log in the game. I tried all accounts I have. All shown,  'Possibly PTC or Goggle server down, check server status.'

**Comment by BangMet** [comment]
Be careful.. Better stop using bot for a while.. wait for next update..

**Comment by AbiDez** [comment]
Update Online... 
Thanks to ShairaMaex for report to devs.

**Comment by PokeBotPub** [comment]
Fixed problem. Thank you.
