### ISSUE TITLE
Expired pokekey before time

### ISSUE THREAD

**Issue by KingdomAJ** [PokeBotPub/PokeBot-Android#311]
First of all why do I or any else one will pay every month 10 dollars for stupid and bug full bot. However I purchased one time and that also expired within 20 days.

**Comment by PokeBotPub** [comment]
Please send you Pokekey to pokebot2018@gmail.com

**Comment by KingdomAJ** [comment]
71001638
Enjoy it because it only worked for 12-16 days.
