### ISSUE TITLE
BanWave

### ISSUE THREAD

**Issue by ArthurPetrilli** [PokeBotPub/PokeBot-Android#316]

**Comment by AbiDez** [comment]
No one knows how Niantic is detecting us. It's a stupid cat and mouse game... In January lost all accs... I bot to come back to 35... Fact is they can see what we done since starting a account... I think they run a script with parameters to kick out the cheaters... And when make Ban appeal like me, a human is watching your account... Bam... And in this moment... RIP Account...

**Comment by ArthurPetrilli** [comment]
Its possible that Niantic has taken note of device id.  That may be my next step...change my android device id.

**Comment by AbiDez** [comment]
Yeah thinking about it the last weeks... But different devices = different id's... But when we discuss this in public so we give the snitches a way to make our life not easily.

**Comment by ArthurPetrilli** [comment]
i think nianic has already got that idea.  I need to change the ids for all my devices except 2 new devices i got recently....

**Comment by ArthurPetrilli** [comment]
there hardly was any talking in these room for a long time and niantic still got 4 of my accts

**Comment by ArthurPetrilli** [comment]
Pokemon Go is getting real lame.  I was really hooked when i did all that walking.  I will keep doing this until my money in google acct is used up.....then i will play pokemon go on Nintendo Switch....or 3DS pokemon sun

**Comment by ShairaMaex** [comment]
be silent too many snitch.

**Comment by ArthurPetrilli** [comment]
Problem:  My accts keep getting shut down 30-40 days after creation.
Hypothesis:  Reducing the frequency of softbans will prevent permaban.
- observation 1:  My level 28-31 acct have been banned.  
- observation 2:  Level 25-27 are still active using same methods as level 28-31
-observation 3:  Duration of activity - 2 session - each session 2 hours - 4-6 hours rest time.
Experimental design:
1) Run 2 accts - modify settings - Do not bypass softban
2) Control gp: - don't modify settings
3) Duration of activity: 45-60 minutes
