### ISSUE TITLE
Poké key no longer valid

### ISSUE THREAD

**Issue by fergatr0n** [PokeBotPub/PokeBot-Android#321]
I donated on 1st March 2017, the code I received worked and I was happy. It has been used on no more than 4 devices and today, 6th March 2017, when trying to start the bot, I get an error message saying invalid Poké key. Never again will I be donating! Be warned.

**Comment by gr3gerhoff** [comment]
I have same problem to. I have used it on same device all the time, but i have reset settings some times and needed to rewrite the code. What is the problem?

**Comment by ShairaMaex** [comment]
its not by month itd by hours so 499 hrs.

**Comment by gr3gerhoff** [comment]
It was over 300h left yesterday.

**Comment by fergatr0n** [comment]
I'm just glad it's not just me, let's home the dev gets their shit together soon.

**Comment by ShairaMaex** [comment]
allow me to contact the dev about this issue, hopefully we can fix this on
the future progress. ill get back to with you about this issue soon as
possible.

**Comment by gr3gerhoff** [comment]
Yes thanks ;)

**Comment by AbiDez** [comment]
Well Shaira please contact the DEV... 
My new Key buy on 3.3 is invalid, too...

**Comment by gr3gerhoff** [comment]
I bought mine on 26 February.

**Comment by ArthurPetrilli** [comment]
This is a sign that we should stop activity!!!!  I have done the math.  I have only been active for a few hours a day on multiple devices.  It only adds up to 5.6 days.  Let's wait for the developers to release 1.0.40.  I am in no rush to get caught in a 3rd banwave.

**Comment by gr3gerhoff** [comment]
It is very good if that's the problem. But it would have been nice if they informed about it in such cases.

**Comment by ArthurPetrilli** [comment]
i dont think they had much time.  Lot's of ppl have complained about losing all acccts....myself included.  i ran bot and shut down.  I forgot to record my exp earned....so i tried to start bot again....that is when i saw the invalid code msg.  I looked in playstore and saw the new update.  I think it is better that players get a little mad about not being informed than losing all accts again.  In my book.....losing all accts is way more serious than getting an invalid code.

**Comment by gr3gerhoff** [comment]
But is this how it is? Or you speculate just now?

**Comment by ShairaMaex** [comment]
Dont Worry, we are working it atm . now the dev team is working it asap
about this issue.

**Comment by gr3gerhoff** [comment]
Okey, thanks for info!

Den 6 mars 2017 11:58 skrev "ShairaMaeX" <notifications@github.com>:
