### ISSUE TITLE
Server Problem!

### ISSUE THREAD

**Issue by PokeBotPub** [PokeBotPub/PokeBot-Android#324]
Hello everyone,
Have a server problem. This problem is not caused by us. Have problem on datacenter side. 

We will add gift times for lost times. 

About purchases : If your make payment and not received PokeKey, please contact with us. 
E-mail : pokebot2018@gmail.com #

**Comment by maversa2** [comment]
Hi, i tried to use the bot it says my code key is wrong a donate i think 2 weeks from now, is still down the server?

**Comment by ShairaMaex** [comment]
Dev is still working on it atm.

**Comment by maversa2** [comment]
thanks, have to wait then...

**Comment by AbiDez** [comment]
We will wait.... Thanks for the Info

**Comment by PokeBotPub** [comment]
PokeBot server is back. 
Added 2 days gift time. 
Have fun!

**Comment by Ger11** [comment]
Good

**Comment by AbiDez** [comment]
Thx

**Comment by ArthurPetrilli** [comment]
Hi, pokemon go has been updated.  When will dev release the latest version?  All my devices are running the latest pokemon go from play store.  Anyone running prog with old api is asking for trouble (ban).

**Comment by AbiDez** [comment]
I don't bot since 2 days... Make update Thread 2 days ago... 
Closed by pokebot.... Without info :(
Update is in store since yesterday morning

**Comment by ShairaMaex** [comment]
Done, forwarding the issue to the dev team.
