### ISSUE TITLE
Actualización Pokemon go

### ISSUE THREAD

**Issue by Ger11** [PokeBotPub/PokeBot-Android#325]
Pokemon was updated, how will it affect the use of the bot? Do we have to wait for the new pokebot update?

**Comment by ShairaMaex** [comment]
Ill do a email regarding this.

**Comment by gr3gerhoff** [comment]
Email me too. I dont know if i should run the bot.

**Comment by ShairaMaex** [comment]
whats ur email.?

**Comment by gr3gerhoff** [comment]
"To: Pokebot2018 06:48
Pokemon was updated, how will it affect the use of the bot? Do we have to
wait for the new pokebot update?"


Den 7 mars 2017 1:50 em skrev "ShairaMaeX" <notifications@github.com>:

**Comment by ShairaMaex** [comment]
Okay, they working it atm

**Comment by gr3gerhoff** [comment]
Nice

Den 7 mars 2017 2:09 em skrev "ShairaMaeX" <notifications@github.com>:

**Comment by BangMet** [comment]
Nice..
