### ISSUE TITLE
I  going crazy!!!

### ISSUE THREAD

**Issue by ck44064** [PokeBotPub/PokeBot-Android#328]
What happened, why after 9 am today, was unable to use, I have, more than 2 days time, going crazy
![screenshot_2017-03-08-13-04-15](https://cloud.githubusercontent.com/assets/26267605/23690871/73eccfcc-038a-11e7-90cd-28a94d6b30ce.png)

**Comment by ShairaMaex** [comment]
Updating on our servers and the App.

**Comment by ck44064** [comment]
How much time do you need to update your program? Will compensation be
given to us?

2017/3/8 下午1:32，"ShairaMaeX" <notifications@github.com>寫道：

**Comment by ShairaMaex** [comment]
The Dev Team will decide. how long and hoe much compensation will be.

**Comment by ck44064** [comment]
Are you still updating the program? How long will it take?


2017/3/8 下午2:29，"ShairaMaeX" <notifications@github.com>寫道：

**Comment by ck44064** [comment]
Are you still updating the program? How long will it be done?

**Comment by ck44064** [comment]
Are you still updating the program? How long will it be done


2017/3/8 下午4:56，"天才" <ck44064@gmail.com>寫道：

**Comment by ShairaMaex** [comment]
Dev team will answer that in the moment.

**Comment by ck44064** [comment]
How long will it take to fix the program? I can use it for more than a day.
Will you make compensation?

2017/3/8 下午6:23，"ShairaMaeX" <notifications@github.com>寫道：

> Dev team will answer that in the moment.
>
