### ISSUE TITLE
About Crashing!

### ISSUE THREAD

**Issue by PokeBotPub** [PokeBotPub/PokeBot-Android#330]
Hello everyone,

All PokemonGo bots down. Niantic is changed few algorithms. We working on it. 

Have fun!

**Comment by Ger11** [comment]
I do not understand the message, all the bots down? Or did they fix it? I am doubtful because in the end they say that you have fun!

**Comment by ShairaMaex** [comment]
POKEBOTS ARE DOWN ALL THE BOTS EVEN NECROBOT IS DOWN. AND THE IVSTATS IS
DOWN EVEN MY LIVE MAP FOR THE POKEMON IS DOWN.

**Comment by ck44064** [comment]
How long will it take to fix the program? I can use it for more than a day.
Will you make compensation?

**Comment by ShairaMaex** [comment]
No Exact date yet will be release.

**Comment by ck44064** [comment]
How can you do the donation? Will you compensate or refund us?


2017/3/9 上午10:12，"ShairaMaeX" <notifications@github.com>寫道：

**Comment by ShairaMaex** [comment]
compensate the days will be gotten

**Comment by koyojax** [comment]
Just wait for it. The dev team work hard for us. Don't be rush
