### ISSUE TITLE
Incubators.

### ISSUE THREAD

**Issue by Tezzeret-NL** [PokeBotPub/PokeBot-Android#333]
Hello, just a quesstion about the incubator option. 

Is it working as intended or is there something wrong with?

Or do i use it the wrong way?

Greetings,

Tezzeret-NL

**Comment by ShairaMaex** [comment]
intended to work :)

**Comment by Tezzeret-NL** [comment]
Cause when i use the bot for a while and then stop it to see what i've got from the eggs i don't see anything. That'd why i'm asking.

**Comment by ArthurPetrilli** [comment]
If you speed is too fast, you will not get credit for walking.  Thank Niantic

**Comment by Tezzeret-NL** [comment]
Set speed to 1, and still did'nt hatch any egg lol

**Comment by ShairaMaex** [comment]
its new eggs cause bot doesnt notify if ur egg been hatched.
