### ISSUE TITLE
Pokebot stopped

### ISSUE THREAD

**Issue by Dillic23** [PokeBotPub/PokeBot-Android#336]
Just putting it out here.. Getting the same error as before the v1.0.40 update.

"Pokebot stopped" and if I close the message the application shuts down.

**Comment by ShairaMaex** [comment]
Yea if u change the dates it will force stop. bots are qalking fine

**Comment by Dillic23** [comment]
Change what dates?

**Comment by PokeBotPub** [comment]
We working on this error. New release is soon.

**Comment by ArthurPetrilli** [comment]
Hmmmm, did the development team implement a strategy to answer the warning ban msg....when you log in normally, you have to hit ok....Niantic might see this as a bot still working without pressing ok.....NOT GOOD

**Comment by AbiDez** [comment]
Yeah... Think the same... Eventually is that a reason why the bot stops after 2 minutes

**Comment by ArthurPetrilli** [comment]
After sleeping for a few hours, it has occurred to me that Niantic's ban warning is acting like a continuous captcha check.  captcha checks are use to tell if you were a bot or not.  Is Niantic's ban warning a form of a captcha check too?  You have to acknowledge it?  Yesterday, I ran the latest program 1.0.42 on a device that has a program.  I have not used that acct for 2 weeks.  It ran for 60 minutes without stopping.  One hour later, i ran the same poke acct on a clean cell phone.  The Ban Warning show up right away.  Wait another hour, i test 90% of acts on assigned devices.  They do not stop but i watch the icon on the map bouncing around.....NOT good!!!!!  Today, i will visit the park and log in normal pogo.  I suspect 90% of acct will have ban warning.
