### ISSUE TITLE
autonatic stop and cannot login after sometime botting

### ISSUE THREAD

**Issue by KeyzerEX** [PokeBotPub/PokeBot-Android#339]
Hello Pokebot
i have problem with my pokebot app, it won't let me login to pogo, i tried to install ur new version pokebot 1.0.42, the problem still. i can go botting if i run the newly installed pokebot app or if i clear the pokebot cache, but after sometime my pokebot app stop botting itself and then crash whenever i tried to bot.So now if i want to go botting i need to clear the cache 1st or uninstall then reinstall it again. Plz Help. This problem start when the new login algorithm has been fix.

**Comment by Wetterhex88** [comment]
The same issue.

**Comment by ArthurPetrilli** [comment]
yeah....your acct has been flagged.  If you log in normal for pogo, you will see a ban warning!!!  I do not believe pokebot has an algorithm to acknowledge "Got It."  If you keep playing, It will look like you bypass the acknowledgement and know for sure you are botting.  The development team came with version 1.0.41 and then 1.0.42.  I do not believe the development team has found a way around this and perhaps there will be a 1.0.43????  Either way, I would not use that acct until the ban warning goes away.

**Comment by AbiDez** [comment]
We all have it... Atm i say every account gets flagged when using bot at this version..

**Comment by KeyzerEX** [comment]
Ty for the replay, so if i stop botting and keep playing from the app will it unflag my acc? or if i use fakegps to play will niantic detect my fakegps if play within my area of reach?

**Comment by AbiDez** [comment]
Well on the last bann wave this message goes after 3 days... 
When you spoof your GPS I think you login to pogo and use joystick controls... That's more safer than a bot... 
When you see the message you can click OK... 
The bot don't click OK.... 
I think, stop botting.... I think Niantic has a surprise for us... And the bot devs run into a trap... And we, too...
