### ISSUE TITLE
PokeBot Keep Pokemon List Congif always in default values

### ISSUE THREAD

**Issue by aaronhernandez23** [PokeBotPub/PokeBot-Android#34]
The pokemon transfer setting's keep pokemon list keep resetting. I've tried to add pokemon, save it, and re-enter the configuration but its back to default values and my added pokemon was not listed anymore .

**Comment by crownoss** [comment]
yes, me too. it can't disable to transfer pokemon, i want to keep alls of my pokemon, but pokebot transfer its all. before update i can disable pokemon transfer and just for collect potion.

**Comment by crownoss** [comment]
update 1.0.12 stiil same problem, can't keep pokemom, when logining then the bot transfer pokemon.  for collect ball and potion over android, this is the best bot, pleas fix it for user who only need potion for gym. thanks

**Comment by luckytom333** [comment]
This is still happening even with new version 1.0.13.  Under the Pokemon Transfer section, "Keep Pokemon List" and "Transfer Filter List" will not save, always revert back to default settings.

**Comment by luckytom333** [comment]
I figured out how to get it to save.  Make the changes you want within "Keep Pokemon List" or "Transfer Filter List"  Click the "save" button inside those menus, however when you back out to the "Pokemon Transfer Settings" Menu, just use your back button to get out to the main menu, don't use the Save button from within "Pokemon Transfer Settings" menu.  Hope that makes sense.  

The "Save" button should be removed from the "Pokemon Transfer Settings" menu as it reverts your changes back to defaults.

**Comment by Clareonz** [comment]
Still revert to default, even after v1.0.15
