### ISSUE TITLE
Google servers down

### ISSUE THREAD

**Issue by Xeesemaster** [PokeBotPub/PokeBot-Android#342]
Hi, 
I'm having this message: Google servers down, reconnecting in 5sec. Anyone experiencing the same? 

;)

**Comment by Thesse57** [comment]
I have the same message with pokebot 1.0.44 thanks for seeing the problem

**Comment by pokeloris** [comment]
Same here since using 44

**Comment by ArthurPetrilli** [comment]
There is no telling what will happen.  All acct got flagged using pokebot 1.0.42.  There is a reason it jumped from 42 to 44.  What happen to 43?  If the developers did it right, we will continue with our accts.....If not...bye bye secondary accts

**Comment by KeyzerEX** [comment]
its not just google my ptc acc too

**Comment by Wetterhex88** [comment]
Same Problem

**Comment by Jajajuax** [comment]
El mismo problema

**Comment by Darthil** [comment]
Same problem

**Comment by ArthurPetrilli** [comment]
I think you should have been more descriptive.  One of my accts is getting the same msg ....[more descriptive now] "Google servers down, reconnecting in 5sec." Repeats several times in poke log.  I shut it down the moment i noticed the repetitive cycle.....I am giving the acct the day off.  Tertiary act step up :P

**Comment by Rico72** [comment]
Same problem here, Can not connect.

**Comment by PokeBotPub** [comment]
PokeBot 1.0.45 Released. Still have problem?

**Comment by Ger11** [comment]
Does anyone know what is happening? What is niantic doing that we have so much   with the bot?

**Comment by pokeloris** [comment]
Working again but on both my accounts got message to stop using 3th party sofware.  Si born in fridge die now and starten 2 new accounts hoor to get to 40 once.

**Comment by ccho2004** [comment]
The same problem. Has anyone can help to solve it? Thanks,

**Comment by Cadix1960** [comment]
Com o mesmo problema e o Google ou o PTC não conseguem ligar ao servidor desde hoje de manhã

**Comment by ccho2004** [comment]
The same issue.

**Comment by Rico72** [comment]
Now having log in issue's. ...

Op 24 mrt. 2017 17:38 schreef "ccho2004" <notifications@github.com>:
