### ISSUE TITLE
what's going on?

### ISSUE THREAD

**Issue by Ger11** [PokeBotPub/PokeBot-Android#344]
What is happening with the bot? Is it safe to use? When will we be free of risks to use them? That is occurring with quantum that the bone bot must be updated very quickly and we are going to be in version.45. What is the real drawback that is generating niantic bot?

**Comment by ShairaMaex** [comment]
At this moment, less than 40% get banned. about this.  data server is the
problem here.

**Comment by Thesse57** [comment]
C a risk to take me for the moment never lost tale

**Comment by PokeBotPub** [comment]
Pokebot 1.0.45 is working fine. (PokeBot 1.0.45 is using "PokemonGO 0.57.4") 

We created new PokemonGO account. Pokebot is working all days. Its 21 level (at moment), not received any 3rd party notice on original PokemonGO client.

So, bot looks safe. But have risk always. We try to make better everyday.

**Comment by AbiDez** [comment]
Ok good to hear that... 
But the most accounts are flagged atm... 
Do you have a bypass for the 3rd party apps warning?

**Comment by pokeloris** [comment]
Problems again on both my new accounts

**Comment by Sangputri2006** [comment]
My account problem in level 20, with happen is cannot niantic server, my reading star in pokebot

**Comment by Thesse57** [comment]
Thanks for your work pokebot works well for me nothing to report for the moment

**Comment by ArthurPetrilli** [comment]
Hey, When i was using pokebot 1.0.42....5 secondary accts got warning flags.  I created 3 tertiary accts using the same bot....none of them got the warning flags......Just b/c there is no warning flags using 1.0.45 does not mean you are not flagged......Niantic's MO lets players think they safe until they reach a certain level.....i no longer have clean acct that was not flagged by Niantic so i could not tell you if you get the warning flags using 1.0.45

**Comment by ArthurPetrilli** [comment]
Strange....one of my accts....i can log into pogo regular....but it runs for a few minutes on 1.0.45 and then can't connect

**Comment by Sangputri2006** [comment]
Me to friend.... My acc same with your acc don,t login in niantic serves,

**Comment by PokeBotPub** [comment]
Fixed problems. Please check and feedback. 

Thank you.

**Comment by ShairaMaex** [comment]
Dev team, Great job. but always run smoothly

**Comment by Thesse57** [comment]
Samsung s5, 6.0.1 Sounds good for me,  The bot behaves well, Level 24 speed, 5 radius 2500 meter
