### ISSUE TITLE
Can't connect to niantic servers...?

### ISSUE THREAD

**Issue by AcheronKaa** [PokeBotPub/PokeBot-Android#346]

**Comment by AcheronKaa** [comment]
Just wondering what's happening, as I can't not on any of my accounts.

**Comment by AcheronKaa** [comment]
*not sorry

**Comment by AcheronKaa** [comment]
Aaarrtggghhh bot

**Comment by ArthurPetrilli** [comment]
check your android notifications on your phone.  the msg is about suspicious activity.  you have to address it and you will login your google acct for that device.  few minutes later, bot works again....that is what i did to make mine work again

**Comment by PokeBotPub** [comment]
https://github.com/PokeBotPub/PokeBot-Android/wiki

* I got "Can't connect Google/PTC servers" error. What can i do?
> Its temporary bug on "PokeBot 1.0.45". If your change location settings, problem is solve. (Or change android language to English) We working on.

**Comment by maversa2** [comment]
it works. i had the same problem. tnx
