### ISSUE TITLE
Ban warning

### ISSUE THREAD

**Issue by maversa2** [PokeBotPub/PokeBot-Android#347]
Its my second lvl 27 acc that its flagged with ban warning both were boted by this way, and both are warned. is any way to take off the warning and continue boting with out risk of a hard ban? or should i start  a new account and let them sleep some time? Thanks

**Comment by AbiDez** [comment]
My sleeping accounts are lost by last ban wave ^^
The problem is we can't talk in public areas to solve the problem because(I think it's not to solve) there are many snitches here and they read our topics and report.... 
But it's possible that the DEV has an idea... 
Don't bot a flagged account... 
The bot ignore the flag and is botting without to click Ok the 3rd party apps warning... (So I know?)

**Comment by maversa2** [comment]
Tnx i think is time to leave pokebot then. I whish i could know how the
fuck niantics know that somebody la boting

**Comment by Thesse57** [comment]
For me it works well no problem

**Comment by ArthurPetrilli** [comment]
Hey, I really want an answer!!!!  Does pokebot 1.0.45 address the ban warning or NOT????  Does it click ok or does it ignore the warning?

**Comment by maversa2** [comment]
That is a great question

**Comment by ArthurPetrilli** [comment]
my level 27 acct is constantly having pokemon break out ....failure to capture.....softban????  Time for cryosleep ... wake me up in a 100 days

**Comment by AbiDez** [comment]
I play my lv27 in RL... But this fucking 3rd Party warning don't go away... What does it mean? ... Curious  gps Spoofer don't have that. My friend only spoof no warning... Only bots affected

**Comment by ArthurPetrilli** [comment]
I got this warning back in December.  All my accounts that got that warning got caught in the January ban wave.  I guess Niantic is giving people a chance to stop cheating...especially all those new players that recently started playing in another country.

**Comment by ArthurPetrilli** [comment]
your account has been marked for death and the reaper will collect next month 📦

**Comment by ShairaMaex** [comment]
chill lang therese said. skip botting for this month. i stopped to bot for
awhile waited for the go signal of dev team.   hi abezzzz. miss you.. yo
therese hit me up.

**Comment by AbiDez** [comment]
Hi Shaira ^^ Well I have deinstalled Pokebot to check is the app the problem... I've don't bot since last Sunday... 
Well when we can't Bot so I have paid 11€ for nothing... Lol

**Comment by ShairaMaex** [comment]
well its bad news. bot is not yet cause of this snitches lurking around.
and the new algorithm that pogo uses.
