### ISSUE TITLE
discord channel cant join

### ISSUE THREAD

**Issue by htcpecah2015** [PokeBotPub/PokeBot-Android#348]
i cant join the pokebot server
is it expired already?
or anyone have the invitation link?

**Comment by ShairaMaex** [comment]
Discord is dead.

**Comment by AbiDez** [comment]
Well everyday give us a new surprise 😲

**Comment by ShairaMaex** [comment]
Really Abe im still alive here and pokepub is too. no one is taking control
of discord group.

**Comment by Thesse57** [comment]
good evening would be well that it is a person to discord. Thanks for the up-to-date update

**Comment by Thesse57** [comment]
The link of discord no longer works c damage
