### ISSUE TITLE
[Issue] Xiaomi redmi note 3 Setting Locations

### ISSUE THREAD

**Issue by mizisahaja** [PokeBotPub/PokeBot-Android#35]
![tmpdoodle1473491441499](https://cloud.githubusercontent.com/assets/21066011/18408681/be4de578-7768-11e6-82a7-e9e7e4792af3.jpg)

hello ,please fix location setting not working for my mobile fon , when i try to setting locations , its keep crash or white screen then back to log in poke bot .thanks i hope will fix it!

**Comment by lowboydu02** [comment]
I've the same problem on my redmi note 3 pro ...
