### ISSUE TITLE
Failed to catch

### ISSUE THREAD

**Issue by ArthurPetrilli** [PokeBotPub/PokeBot-Android#350]
The development team needs to rework the item recycle.  I can only carry 350 items.  I select keep 50 berries.  Its a problem when the bot throws out all the rasberries and keeps those other new berries.  Ocassionaly, i will check the log and find the pokebot is wasting a bunch of pokeballs at some pokemon only to get msg about FAILED capture....about 15 times.

**Comment by ShairaMaex** [comment]
item recycle is being fix already and the pokemon catching is fine. failed
cuz the pokemon has low catch rate

**Comment by ArthurPetrilli** [comment]
The point is, b4 Niantic did an overhaul, i rarely saw catch FAILED b/c i had a bunch of raspberries.  The bot throws out the rasberries and keeps the new berries.  Thus, i have a ton load of FAILED catches b/c i have nnnnoooooooo raspberries.  This happens a lot with the level 27 and 28 accts

**Comment by ArthurPetrilli** [comment]
My level 26 accts have no problem catching the same pokemon in the same area :(
