### ISSUE TITLE
GPX File

### ISSUE THREAD

**Issue by TriNtoro** [PokeBotPub/PokeBot-Android#351]
hi admin
i had already paid your key,
working smoothly. 
can you add walking Human route, like Gpx file.

**Comment by ShairaMaex** [comment]
hey nintro send me the email of ur settings ty viergeverola@gmail.com

**Comment by TriNtoro** [comment]
i used default setting. 
no need change

**Comment by ArthurPetrilli** [comment]
ha!!!!  Might as well be on the wish list....i requested this two months ago....we still don't have it.....the best we can hope for is that the bot still even work after Niantic's updates
