### ISSUE TITLE
Any Freebies? like 1 month of free key? something like that?

### ISSUE THREAD

**Issue by MisterJohnHanke** [PokeBotPub/PokeBot-Android#353]

**Comment by ArthurPetrilli** [comment]
You are FREE to go to the store and purchase a $11 google card.  Think about the trade off.  You can walk around for hours, seven days a week.  The bot will FREE you of this burden for the low price of $11.  If you use the bot carelessly, Niantic will be happy to FREE you of your acct.  Niantic has FREED me of my obsession, 12 high level accts.   What are you waiting for?  Take the plunge!

**Comment by ShairaMaex** [comment]
plunge in bruhh. 😂

**Comment by Sangputri2006** [comment]
I do know... What happen
