### ISSUE TITLE
Watch Out !!!  new 0.59.1 PoGo version will come !!!!

### ISSUE THREAD

**Issue by KingSiquera** [PokeBotPub/PokeBot-Android#356]

**Comment by ArthurPetrilli** [comment]
My best acct are in a deep sleep since yesterday.  2nd tier acct getting some exercise.  When new update is forced or shows up in store, my 3rd tier (test acct) will run the night

**Comment by KingSiquera** [comment]
Great !!!.. a very experienced advice.

Thanks Arthur.
