### ISSUE TITLE
device ID compromised???

### ISSUE THREAD

**Issue by ArthurPetrilli** [PokeBotPub/PokeBot-Android#357]
Last week, i had complained about failed capture....that would repeat non-stop!  It was affecting my high level acct and now my low level acct 22 is doing the same thing on the same device.  My other devices will sometimes show failed capture but it is not continuous.

SYMPTOMS: 
1) same device (regardless of high level or low level 20's
2) Tries to catch 1 or 2 Pokemon (continuous switch attempts then tries to get the other Pokemon....goes in circle)
3) Settings indicate that i use 2 poke-balls per capture!!!!!!!!!!!!!!!!!!

WORKAROUND:
1) Manually shut down bot after i see a pattern, 5 failed captures for same Pokemon.  Restart pokebot and CAPTURE SUCCESS!
2) I am considering changing my device ID.  Have not tried this yet b/c workaround #1 seems to work so far.

SUGGESTION:
1) Modify inventory recycle.  There is no option to differentiate between which berries to keep.  I really need to keep my rasberries and throw out the other berries.  As it stands, I currently have 75 pinap berries and there are no other berries!!!!!
2) Program the bot to stop trying to catch the same weak pokemon after many "CAPTURE FAILED."
3) Tweak the bot's capture settings.  I have it set at two poke-balls per capture.  Some reason, it goes above and beyond trying to catch the same weak pokemon with an obesssion.  I could understand if it was a dratini/dragonair/dragonite with IV of 93 or higher!!!!

**Comment by AbiDez** [comment]
But when you change your device I'd, then you have the same problem like me... 
Key not valid...

**Comment by ArthurPetrilli** [comment]
Hehe, i do not plan on changing my device id until its time for payment again :)

**Comment by AbiDez** [comment]
👍

**Comment by ArthurPetrilli** [comment]
Yesterday, i went to my pokemon hunting grounds.  I brought all five devices.  The device i was complaining about  (possible device ban) could not farm from pokestops and all the pokemon would breakout of 1 ball and run away!  I login into a different device with the same google acct.....LOW and BEHOLD, i could farm from pokestops and catch pokemon......That clearly was a DEVICE BAN!!!!!!!!!

COMPARISON:  pogo and pokebot
When i play pogo, the pokemon break out and run....those pokemon are gone for good!!!!
When i watch the logs for pokebot, how the hell is pokebot trying to catch the same pokemon over and over and over (most i have counted was 15 FAILED attempts) before i manually stop bot!!!!

I am not surprised about device ban :(
