### ISSUE TITLE
Poke key

### ISSUE THREAD

**Issue by Izan69** [PokeBotPub/PokeBot-Android#358]
Is there any other way that i can get  poke key for free?

**Comment by ArthurPetrilli** [comment]
That will not be FAIR.  If this guy gets a fee pokekey, I want one too.  If i can pay my $11/month, this guy can too.  He just does not want to use pokebot bad enough.  When you get tired of walking several hours a day, seven days a week, you will come up with $11 / month.  There are other websites that charge less than that!  Just take the plunge
