### ISSUE TITLE
 Pokemon go updated yesterday, will the new version of the pokebot be updated when i am using the old pokebot safe?

### ISSUE THREAD

**Issue by ck44064** [PokeBotPub/PokeBot-Android#359]
Pokemon go updated yesterday, will the new version of the pokebot be updated when i am using the old pokebot safe?

**Comment by ArthurPetrilli** [comment]
DO NOT USE POKEBOT!!!!!!!!  
Wait for the develpment team to release an updated version.  You bot will not update on its own.  Just like the rest of us, we need to download and install ourselves.  Even with the new bot, you must test it out with a weak acct for any bugs....(couple days to a week)  Niantic are a bunch of BIOTCHES!!!!  I logged in POGO the regular way.  2 of my 5 devices crashed and rebooted on their own!  They have the new version number of POGO 0.59.1.  F....ing thank you Niantic.   Please, ask me if i want an update, NOT!!!!  There was no prompt on my end if i wanted to update

**Comment by ShairaMaex** [comment]
update sucks definitely.

**Comment by ck44064** [comment]
How long will it take to complete the update? Will we get time to compensate?


2017/3/24 下午6:19，"ShairaMaeX" <notifications@github.com>寫道：

**Comment by ck44064** [comment]
How long will it take to complete the update? Will we get time to compensate?


2017/3/24 下午6:23，"天才" <ck44064@gmail.com>寫道：

**Comment by ShairaMaex** [comment]
same procedures just wait

**Comment by Scribsink** [comment]
I hope it will be soon. Cant login to google service right now.
