### ISSUE TITLE
connect account 

### ISSUE THREAD

**Issue by majinkrys6** [PokeBotPub/PokeBot-Android#360]
not possible

**Comment by Sangputri2006** [comment]
Do not connect account, why??

**Comment by Scribsink** [comment]
It does not connect.... can login but cant start farming.

**Comment by majinkrys6** [comment]
Now its running but its said impossible to connect to the server ptc ... reconnect in 5s

**Comment by Scribsink** [comment]
Reconnect reconnect please update this shit i didnt pay 11 euro for nothing
