### ISSUE TITLE
Update!!!

### ISSUE THREAD

**Issue by Scribsink** [PokeBotPub/PokeBot-Android#361]
Please update the app asap!

Cant login into google account anymore since like 2 hours.

And diff api?

**Comment by pokeloris** [comment]
Same here in Holland, no login possible on all accounts

**Comment by Scribsink** [comment]
Im from holland too. Almere haha.

**Comment by mrdonkeyv** [comment]
Need update please

**Comment by Scribsink** [comment]
Omg yes we need a update.

How long takes a update regular?

**Comment by ArthurPetrilli** [comment]
Check your devices for msg from google.  It will tell you have suspicious activity on your acct and will require you to login to your device.  See if you can log in to your regular pokemon go acct.  I just checked my 1st & 2nd string acct....they all login just fine.  2 of 5 devices crashed on me this morning when i logged in normal POGO.  Niantic somehow made my devices crash and update automatically to new version of POGO 0.59.1.  I did not think that was possible.  With that said, you really are taking a huge change of loggin into pokebot (older API) while you may very well have the new version of POGO on your phone.

POKEBOT update is a waiting game for us.... just gonna have to wait like the rest of us until the development team does their thing.

**Comment by ccho2004** [comment]
I follow your instruction to check my acct.. But still has the problem.

**Comment by Scribsink** [comment]
Both accounts can login on pogo. Not at pokebot....

**Comment by ArthurPetrilli** [comment]
ccho, when you try to login to POGO, did you get a msg "Can't Find Data?"  That is PERMABAN
You could try login to a different device to be sure you dont have permaban....it could be a ISP or device id ban (temp....i think...)  One of my device got the device ban lasted like for every!!!!  :(

Scribsink, Don't login to pokebot anymore until developers release update pokebot.

**Comment by ArthurPetrilli** [comment]
One more advice:

When the update is released, DO NOT, under any circumstance, use your best acct!!!!!  That is how i lost my best accts in January ban wave.  

Use weak accts to test the update for any weakness....the developers are good but they are not perfect.

**Comment by Scribsink** [comment]
My best account is 29, lost a 39 acc when i was using pokiimap.

Now i have 2 accounts. A 29 and 22.

29 pokedex full (only 2 babys) (flagged third party warning)
22 test account but already hitting 200 pokemons in pokedex. (No warning so far, 3 days old acc).

Maybe ill go with the 22. Of maybe ill make another new account.

But please update!!!

**Comment by Scribsink** [comment]
Ohhh im so not patient!!! Waiting for hourssss

**Comment by ArthurPetrilli** [comment]
Played PoGo while i am waiting for Pokebot!!!!!  I'm not patient either.....now i am too tired to get worked up :P I see that there is no update yet.  No surprise.  I rather have development team take as much time to put out the best bot with as few updates as possible.  If the development team rushes.....the consumers will suffer in a big way!!!!

**Comment by Scribsink** [comment]
Pffffff

**Comment by Scribsink** [comment]
I hope we het comparisation for the hours we cant bot......

**Comment by Jajajuax** [comment]
Como va el proyecto?. Tenemos futuro?.
GRACIAS

**Comment by maversa2** [comment]
Calculo que no, ya perdi algunas cuentas y el resto salvo una flaguedas... el proximo ban wave perdi todo
