### ISSUE TITLE
Pokemon has been updated for two days, why pokebot has not been updated so far? How long will it take to complete the update? We have two days dare not use pokebot, how long will we have to wait?

### ISSUE THREAD

**Issue by ck44064** [PokeBotPub/PokeBot-Android#363]
Pokemon has been updated for two days, why pokebot has not been updated so far? How long will it take to complete the update? We have two days dare not use pokebot, how long will we have to wait?

**Comment by ShairaMaex** [comment]
probably month or so

**Comment by ck44064** [comment]
Will it compensate us for the loss?

**Comment by Scribsink** [comment]
A month??? Its a paid program!!!! Need to fix within 24hrs!!!!!!

**Comment by AbiDez** [comment]
Lol

**Comment by ShairaMaex** [comment]
Lol tell it to the dev team

**Comment by Scribsink** [comment]
Lmaoooooo haha i do not pay for fucking nothing bruhhhhhhs imma sue this shit the hell out of it 😂

**Comment by ShairaMaex** [comment]
im here to recieve complains then redirect to theq dev team.

**Comment by Scribsink** [comment]
Oh well, intresting shaira.

Please tell them to hurry uppppp hahahah

**Comment by ArthurPetrilli** [comment]
i have downloaded 7 versions of pokebot during march 1 thru march 16.  plz put out the best bot with fewer updates as possible..
