### ISSUE TITLE
If pokebot is not safe to run, we will apply for a refund with google play to protect our interests!

### ISSUE THREAD

**Issue by ck44064** [PokeBotPub/PokeBot-Android#365]
If pokebot is not safe to run, we will apply for a refund with google play to protect our interests!

**Comment by ArthurPetrilli** [comment]
If you wanted to protect your interest, you would not use a 3rd party app.  While you complain to google, don't forget to mention that you are using a 3rd party app to cheat!  Yes....CHEAT.  You are a CHEATER like the rest of us in this room.  

I for one will not be asking for a REFUND!!!!  No matter which bot you find, your accts will always be at risk.  I said it before and i will say it again.  If you are using a bot, you need to be prepared for the day those acct get PERMABAN!!!!  The question is:  How far can you go before Niantic discovers you are cheating????

**Comment by hongheng08305** [comment]
It's really not safe I already 3weeks never use

**Comment by ArthurPetrilli** [comment]
How do you know bot not safe????  Please share your insight

**Comment by ArthurPetrilli** [comment]
3 more days to catch those shiny Magikcarp/Garados.
I was soooo tempted to use the bot on a low level acct.  1 of 5 devices experienced a temporary device ban.  This time it might be permanent :P Gonna have to go to the park and try to catch them manually....day 3....sooo far.....nooooo freaking LUCK!!!!!!!!!!!!!!  An updated bot will increase my chances....HINT HINT....DEVELOPERS

THREE DAYS AGO, 2 of 5 devices mysteriously crashed while i was playing PoGo with flagged accts.  I wonder if Niantic thought i was using the bot at that time and forced an upgrade..........sure glad i was testing all my accts to see if i still had the 3rd party app warning!!!!! Still have it.....Bright side....I no longer have the device ban

HYPOTHESIS:  If Niantic thinks your botting/spoofing - Anyone still running the older API on PoGo 0.57.4 will trigger CRASH and update your (flagged accts) device to latest API 0.59.1.....If your bot (API 57.4) is still running/restart after your device updates....Niantic will catch cheaters hook, line, & sinker. [THIS IS NOT FACT, ONLY A GUESS]

EXPERIENCE:  Lost 1st string accounts in January ban, lost 2nd string accounts in February ban

You ever hear that saying?  Quite while you're ahead.  I should have quit botting at level 35 :(

**Comment by Scribsink** [comment]
- a option in the bot to choose a beginner pokemon, nickname and team at the required level.

This in need that you dont ever have to login with a new account in the regular pokemon go app. You can start a new account and start botting instantly. Nickname filled in into the bot and when you reach like level 7 you could choose your team..

In that way you could have a safe account if you stop botting when a new api rolls out.

**Comment by ArthurPetrilli** [comment]
You must be new to the bot.  Trust me, i was careless with the bot a few times.  Even if you use a beginner acct through pokebot, Niantic can still give temp ban on ISP/WiFi.  Push come to shove, a device ID ban....very noticeable....especially when running bot.... 1 out of 5 devices constantly had "FAILED CAPTURE" repeat non-stop

I am more careful now....by all means...give it a try and share your story after 1 week....assuming you level 25 and over...

using a starter account does NOT indicate any problems until you either run the bot too long or level up too fast and reach level 25

**Comment by Scribsink** [comment]
I already wasted 3 acc on perm bans.

I never ever used any other phone then my galaxy s4. I never switched ids or so.

I can login to pogo.

Im lvl 27 with a warning (because of spoofing with another bot), and a 22 fresh only going in pogo for picking pokemon and choose a team. The 22 i only used with pokebothubandroid and i turned the bot off a day before new release of pogo.

But for now im curious when this app will be updated... there are other bots that working again and are free to use... but i have faith in this one because it was running so smooth and i have invested in this one.

**Comment by ArthurPetrilli** [comment]
Hmmmm, I lost 13 acct to PERMABAN.
I have 12 more acct that have the 3rd party warning....3 accts flag free..   

when update is out...i will use my level 25-27 to test bot....No guarantees....i may very well lose those 5 accts in a weeks time......that is what happen when i lost my strongest accts (6) back in January ban wave......you dont get the ban right away......Niantic lets you go for about a week and BAM

I was sooo pist about losing my best accts that i practically did not take caution when my 2nd string accts were used after pokebot was updated February.....i got careless and i was still sore about January loss.....2nd string accts level 27-30 gone

Started over fresh.....will not be the same until i get to at least level 35 with a shit load of strong pokemon...

Losing accts is getting old.....part of me is ready to let it go and play Pokemon Sun on Nintendo 3DS
