### ISSUE TITLE
Any news?

### ISSUE THREAD

**Issue by Scribsink** [PokeBotPub/PokeBot-Android#366]
Are the developers on holiday or can we receive a message about development from them, like something they're on it.... its a hard descission to change from bot... because i like how this works on my android.

In hope for some answer...
My pokekey is from 720hrs back to 640 and can't bot anything... its like 1/10 loss so far, 1 euro.

**Comment by ArthurPetrilli** [comment]
I usually get a text msg from developers that update is available and we get credit for sooo may days.....personally, i have never seen them give more than 2 days of credit per pokebot update.....we are on day 3 that bot has not been used

**Comment by AbiDez** [comment]
Hi Arthur, 
Ok you got a message from devs, Update available, that was 16h ago.... 
Update?

**Comment by Scribsink** [comment]
He did not get that message yet.

But im waiting for 3 days now!

**Comment by ArthurPetrilli** [comment]
I am still waiting for update.  I have kept records of my bot use.  I am on day 4 - no bot....This will be interesting....how many days will we get ?  There are only 2 days left for Magikarp/Gyarados SHINY!!!!!  Too tired to walk around pokemon stomping grounds.....long day at work :(

**Comment by AbiDez** [comment]
I have a shiny Magicarp but with WP 10 oO That sucks :(
But a friend said i evolve a Red Garrados... Hmmm...

**Comment by ArthurPetrilli** [comment]
Yeah, that makes sense.  Just like santa Pikachu.....evolved into santa Raichu.
I walked around for 3 days and still did not find a shiny....and if i did.....low IV's i transfer....dont care for a shiny with low IV's
