### ISSUE TITLE
No update, we dare not use!

### ISSUE THREAD

**Issue by ck44064** [PokeBotPub/PokeBot-Android#367]
Since pokebot is a toll program, it should be updated with the pokemon go update, a few days ago pokemon go updated, but did not see the pokebot update, even if it is a plug-in, programmers are also obliged to pay in the more secure circumstances Run pokebot, no update, we dare not use!

**Comment by Scribsink** [comment]
Please update asap 😢

**Comment by pinkha8er9989** [comment]
👆👆💯💯💰💰

**Comment by Scribsink** [comment]
Pffffff

**Comment by pinkha8er9989** [comment]
?
