### ISSUE TITLE
Shiny Pokemon with low IV's

### ISSUE THREAD

**Issue by ArthurPetrilli** [PokeBotPub/PokeBot-Android#368]
I am still waiting for POKEBOT to release an update so that i may TEST out my HYPOTHESIS

Hey, will pokebot be able to handle the shiny pokemon with low IV's?????  My bot settings indicates that i transfer all pokemon with IV's less than 93%.  Niantic algorithm includes extra steps so players do not accidentally transfer a shiny pokemon.  Will the pokebot be able to adapt to those changes????

I don't know about the rest of you guys.  4 of 5 test accounts will not transfer any pokemon while bot is running.  I will have 1 of 5 as my standard test that will continue transfering pokemon.

I suspect that unless Pokebot has an answer to transfering shiny pokemon with low IV's, my account will probably be flagged for suspicious behavior......Then, PERMABAN

**Comment by Scribsink** [comment]
Update asap damn

**Comment by ArthurPetrilli** [comment]
The last time i used the bot is March 23, 2017.  It has been 5 days now!!!!  What is the story team???  Are you guys really working on the update or are you waiting for the crap to HIT the FAN???

Man....I guess Pokebot is expecting late payments in APRIL!!!!  I can save my money and buy Pokemon Sun for the Nintendo 3DS XL

**Comment by Scribsink** [comment]
Lol
