### ISSUE TITLE
About Last Week

### ISSUE THREAD

**Issue by PokeBotPub** [PokeBotPub/PokeBot-Android#369]
Hello everyone,

Someones say "Pokebot is not safe". That is bullshit. No proof, just rumors. PokemonGo not forced update to 0.59.1. (Niantic seems to changed few algorithms in 0.59.1) 

We working on Pokebot 2.0.0. (Shared few screenshot on discord channel) Its more perfect than Pokebot 1.0.x releases. 

Added 3 days gift to all pokekeys.

Do not panic, we are here :+1:

**Comment by ArthurPetrilli** [comment]
The last time i used the bot is March 23, 2017. It has been 5 days now!!!! 

3 days of gift time is BULLSSHIT!!!!!

I still do not see updated pokebot.  How are you going to say we get 3 days....that is bull....you should be giving more days when you finally release the 2.0 pokebot

Those are not fucking rumors.  You are pisting me off!!!!

I got 6 great acct banned in January
I lost 6 more decent accts in Febuary

Who are you telling that there is no fucking evidence!!!!!

**Comment by ArthurPetrilli** [comment]
Forcing update....2 of 5 devices crashed after they were acting weird.  I never update myself.  Somehow, i had the updated versions on two tablets Samsung G2 and Samsung Pro when i went into settings to clear cache.

My Samsung phones still have 0.57.4

How do you suggest collecting proof on that????

Experience has taught me that if i use the bot after PoGo has been update....and i lose acct in January, then in February....Why the hell would i think its fucking safe to use in MARCH?????? Not safe my ass

**Comment by ArthurPetrilli** [comment]
![2017_01_20_22_19_24](https://cloud.githubusercontent.com/assets/24369857/24434503/f533ecae-13fd-11e7-9ea5-e7123c6501b5.png)

**Comment by ArthurPetrilli** [comment]
i was careless to use the bot after pogo update....6 accts in January and 6 accts in Februray get this screen.  Niantic practically laughed at me when i tried to appeal one of my accts.

**Comment by ArthurPetrilli** [comment]
To be fair.
When PoGo was updated in January....i waited for Pokebot to update before using it.  Shortly afterwards, i ended up with 6 banned accts.   Lets be fair here.  You guys fucked that one up.  I was careless to think pokebot had their shit together and eventually changed the way i used pokebot.  Now i use test acct to check your sloppy ass work.....i would not want to get anymore high level accts banned in March....just b/c you say it is SAFE!!!!!

**Comment by ArthurPetrilli** [comment]
![2017_03_28_22_09_11](https://cloud.githubusercontent.com/assets/24369857/24435493/a466bfe4-1403-11e7-8f8d-888f5aa87804.png)

I have a total of 12 accts that got this msg this month.  Pokebot is safe???  I have 12 more acct that are potentially on the chopping block!!!!!!  Is this not evidence that Pokebot is not safe to use.  What safeguards did pokebot have in place to prevent this from happening?????????  I run the bot every other hour on 5 different devices.

**Comment by KingSiquera** [comment]
No person who does not upset when their accounts got banned,even me.
But from there we can take lessons to improve our "XP" . in botting.

When we are upset, we forget that we already play DIRTY.  

So stop upset , just Move on.

**Comment by ArthurPetrilli** [comment]
Shut up King!!!!! 
The first line of this strand:
Someones say "Pokebot is not safe". That is bullshit. No proof, just rumors

I was chill until he said that shit!!!!!!

Yes, We are all cheaters!!!!  But dont fucking tell me this shit is safe and its fucking rumors

**Comment by ArthurPetrilli** [comment]
You want more proof
From March 1 to March 16....i have downloaded 8 version of pokebot.....Its safe to say that you are very sloppy with your work.  get your shit right the first time and you wont have soooo many updates!!!!

![pokebot download record](https://cloud.githubusercontent.com/assets/24369857/24437202/c29a974c-140d-11e7-9f7c-052b157dff45.png)

**Comment by ArthurPetrilli** [comment]
first ban wave - lost 6 accts from January 20-26 something must be wrong with update Jan 20
2nd ban wave - lost 6 accts February 25-26 must be something wrong with update on Feb. 20

Yes, everyone....Pokebot is safe......there is no fucking proof....b/c i am anal and i keep track of all things i do with pokebot and pokemon!!!!!!!!!!!!!!!!!!!!!  I even have a dialy XP exel spread sheet for all my accts

**Comment by Scribsink** [comment]
Oh my god arthur shut up asap bruh about al your lost accounts and your theoretic things about it. Fuck it. Everyone loses accounts. Get over it or go cry out loud by mommy.

Im happy to hear something from development

Thanks! Seeing forward to download 2.0!

**Comment by Scribsink** [comment]
Really arthur the only thing i was reading about this week was the loss of your fucking 9 account.

If you have ever opened more acc than 3 you a fucking moron. I only have 4 acc 2 lost 2 still running. Botting since day 1.

So i dont fucking know what you doing but please shut up and if you wanna cry about 3 days or your lost accounts or theory why you lost account shut up and email to them. But dont fxking cry here how fucking old you are little shit

**Comment by Scribsink** [comment]
Thankyou pokebotpub! 

Really cant wait!

**Comment by ArthurPetrilli** [comment]
Fuck you Scribsink...you fucking scrub!!!!!
Don't act like your shit don't stink....reread your fucking post....you think i am the only one...fucking loser!!!

**Comment by ArthurPetrilli** [comment]
I am a customer!  I paid my money and have every right rant to about the quality of the product and i am sick and tired of shade thrown on customers.

If consumers do not voice their displeasure, development team will be HAPPY to take your $11/month.  It is up to each and everyone of us to put a fire under the development team to deliver a better product after PoGo updates.

**Comment by Scribsink** [comment]
Oh my godddd arthur go cry out loud fuckboi

**Comment by ArthurPetrilli** [comment]
Scrub is back....go fucking buy more devices and then we talk

**Comment by ArthurPetrilli** [comment]
i bet you don't like being called scrub...poor ass

**Comment by Scribsink** [comment]
I need my pokemon i need 12 accounts i have lost all my accounts aaahhwwww

I have 5 phones running aaaahw how cute

What are u a 12 yr old kid 😂 lmao you are fucking retarded

**Comment by ArthurPetrilli** [comment]
liar....i have read your post....your a poor ass that uses a shitie S4

**Comment by ArthurPetrilli** [comment]
Aaaahhhh...you can't afford an up to date device....go get some unemployment

**Comment by Scribsink** [comment]
Scrub lol fuck call me whatsver you like. Surname is scribs so dont know what u doing 

Arthur rofl this name.... 😂😂😂😂😂😂 fuck my lifeeee bruh i fucked yo mom

**Comment by ArthurPetrilli** [comment]
haha....you thought it was my mome but it was your uncle

**Comment by ArthurPetrilli** [comment]
SCRUB

**Comment by Scribsink** [comment]
Lol i dont need a updated device because im switchin phones every 2 weeks you dont no what u talkin about crying kid

Go to school while your mom put my dick in her mouth while daddys workin

**Comment by ArthurPetrilli** [comment]
did you even get past 6th grade

**Comment by ArthurPetrilli** [comment]
Again....your fantasy r lame....get some glasses....your uncle packs it for you every night kid

**Comment by ArthurPetrilli** [comment]
next in line is your grandad

**Comment by Scribsink** [comment]
My uncle rofl thats the best u can 😂

Bye bye arthurboyyyyy 😊 all your theoretic scenes are going to niantic thanks for your lovely spectalutions.

**Comment by ArthurPetrilli** [comment]
later loser

**Comment by ArthurPetrilli** [comment]
so you the snitch???

**Comment by Scribsink** [comment]
Hope u get terminal cancer fuckboi like ya mommie get within a month

**Comment by Scribsink** [comment]
No because u spread it here and they not foolish you fucking moron

**Comment by ArthurPetrilli** [comment]
Try and delete your comment SNITCH.  
![pokebot snitch](https://cloud.githubusercontent.com/assets/24369857/24448286/a8e2ff18-1441-11e7-9847-247a5242ac13.jpg)

**Comment by Scribsink** [comment]
Fucking MORON 12 ACC. Wtf u doing with your life lmaooooo you really got no wife 😁😂 doing al this kiddy stuff

**Comment by ArthurPetrilli** [comment]
I'm done with you SNITCH...you can turn your head ans spit or swallow...matter not to me....

**Comment by Scribsink** [comment]
I dont ever delete somsthing lol what u wanna do.

**Comment by Scribsink** [comment]
Go cry out loud fuckboi hope you lose all ya acc with your stupid theoretic fantasies

**Comment by ArthurPetrilli** [comment]
I'm done with you SNITCH...you can turn your head and
![pokebot snitch](https://cloud.githubusercontent.com/assets/24369857/24448380/f9dcb404-1441-11e7-8d48-314d1734d925.jpg)
 spit or swallow...matter not to me....

**Comment by Scribsink** [comment]
Fuckboy i skullfucked ya mom

**Comment by ArthurPetrilli** [comment]
Give it up SCRUB....you already hinted enough information that your are a SNITCH
![pokebot snitch](https://cloud.githubusercontent.com/assets/24369857/24448502/653bde5a-1442-11e7-9083-2a472fca87e2.jpg)

**Comment by Scribsink** [comment]
LOL. Because niantic cant read this shit you post every day all day. Go get a life damn bruh

**Comment by ArthurPetrilli** [comment]
Give it up.....you thanked me for my speculations....you're a fucking snitch ... DELETE that BIOTCH!!!!!

![pokebot snitch](https://cloud.githubusercontent.com/assets/24369857/24448668/e1f7b3e2-1442-11e7-95c4-0bd06d2567cf.jpg)

**Comment by Scribsink** [comment]
Damn get a life 😂 you speculations are nothing.

**Comment by ArthurPetrilli** [comment]
Give it up.....you thanked me for my speculations....you're a fucking snitch ... DELETE that BIOTCH!!!!!
Try and clean that shit up....you did not even try to deny it the first time or 2nd time,  i called you out.  Working for Niantic must be a hard job for you :P

![pokebot snitch](https://cloud.githubusercontent.com/assets/24369857/24449097/51460932-1444-11e7-9230-15c4ca266ba3.jpg)

**Comment by ShairaMaex** [comment]
This why pokepub is behind

**Comment by Scribsink** [comment]
When 2.0.0 will be released? We will be waiting for days!

**Comment by PokeBotPub** [comment]
We are trying to do best. You can use Pokebot or don't. Pokebot is working with PokemonGO 0.57.4 version.

**Comment by pokepup12** [comment]
No problem, ptc or google. 

Bot started pre 0.57.1
Bot started on 0.57.4
Bot started on 0.59.1

All bots run on pokebot.
All bots open in Pogo

**Comment by Scribsink** [comment]
Im going further with my second account. When 2.0.x comes i will open a new acc to test it first before botting my main account.

**Comment by Scribsink** [comment]
Im going further with my second account. When 2.x comes i will open a new acc to test it first before botting my main account.

Will there be pokemon inventory check option in 2.x? And deleting manually?

**Comment by pokepup12** [comment]
Use it, don't use it, whatever but STOP FUCKING MOANING. If it bothers you that much why don't you go and write your own bot?

**Comment by OmegaMutant** [comment]
PokeBotPub 
We are trying to do best. You can use Pokebot or don't. Pokebot is working with PokemonGO 0.57.4 version.

That is very irresponsible of you.  Shame on you PokeBotPub!!!  You apparently do not care about your customer's accounts!  When Niantic decides to force the upgrade and you are using the bot at the time, bye bye account!!!!!  TERMINATED.  Were you going to warn your customers of this eventuality?  You could always blame the customers.  You cheated!!! That is life.  But this is a prime example of your negligence and the customers should be mad!!!!!

**Comment by OmegaMutant** [comment]
pokepup12
"No problem, ptc or google.

Bot started pre 0.57.1
Bot started on 0.57.4
Bot started on 0.59.1

All bots run on pokebot.
All bots open in Pogo"

You are wrong for this!!!! Using the bot on those older version can get you flagged with 3rd party warnings!   Were you going to tell customers this or let them think it was okay?  JUst because the bot runs does not mean there are no dangers.  If anything, your chances of getting your account AXED has increased.

You guys really need a PR person because you apparently do not have the skill set for this!!!!!

**Comment by pokepup12** [comment]
Dry your eyes and either shut up or go somewhere else. I check here for legitimate issues and get multiple listings of you cunts moaning and I'm fucking sick of it.  You take your chances and if you get caught you man up and start again. What you don't do is whine like a bitch and blame others.

**Comment by OmegaMutant** [comment]
Like i said, you don't have the skill set for this job.  Hire someone with skills

**Comment by pokepup12** [comment]
I don't have any affiliation to pokebot other than running it. I have presented you with ACTUAL FACTS about how my accounts have run.

No third party warnings, no bans, not even a softban. I'm presenting you with FACTS about how my bots run so with all respect in the world, who the fuck do you think you are to tell me that's wrong? While you've been here whining like a schoolgirl I've been testing bot variants to see what gets flagged and what doesn't. I figured this was of more use to the bot community than moaning. Untill you come up with a more constructive idea then the best suggestion I have is that you go fuck yourself. It might not help but at least we'll get peace for around 30 seconds before you cum in your spiderman pants. 
Grow the fuck up.

**Comment by pokepup12** [comment]
You're right, I don't have the skill set (neither do you) so I pay my monthly fee and trust it to people who are smarter than me (and quite clearly you) to do the legwork for me.

**Comment by OmegaMutant** [comment]
You are beneath me, TRASH.  Move on

**Comment by pokepup12** [comment]
Lol, got called out for making a cunt of yourself and let's move on. You had plenty to say before? 🤔

**Comment by OmegaMutant** [comment]
"Dry your eyes and either shut up or go somewhere else. I check here for legitimate issues and get multiple listings"
"I don't have any affiliation to pokebot other than running it. I have presented you with ACTUAL FACTS about how my accounts have run."
Those are your quotes.  You are tripping over yourself.  Get lost, give the job to someone who know what to do.  I even have more skills than you do when it comes to presenting an argument.....yawn....get lost TRASH

**Comment by pokepup12** [comment]
You clearly don't because, and I'll make it real simple......I DONT WORK FOR POKEBOT.  They're not quotes, they're FACTS about how my bots have run over the last week. You can't even construct a proper sentence let alone present a valid argument. You have incorrectly blamed me for development issues, offered nothing constructive and your best argument seems to be "you are trash". I'm sure debate teams are queing around the block to get you on board. 😂

**Comment by OmegaMutant** [comment]
you lost and look very foolisih....you need a straw....u gotta suck it up and move on...TRASHJ

**Comment by pokepup12** [comment]
Another well made point. 😂 lost? Lost what?

**Comment by OmegaMutant** [comment]
Don't confuse your FACTs with your feeble understanding of PoGo Algorithms.  You are trying too hard.  your handle is too similar to PokeBotPub.  Don't share your information.  It is misleading others who do not know better!  I know better and i called you out on your shit!!!!  You are very ill-informed and should not leave your information without a disclaimer...That you don't know shit!!!

**Comment by OmegaMutant** [comment]
TRASH

**Comment by pokepup12** [comment]
I opened the accounts on the bot and they worked - fact. I opened them on the app and they worked -fact.
They are not banned - fact
I have not received a softban - fact I haven't once tried to explain any po go algorythm or make any claims, Just telling you what I've found over the last week. Yes it COULD get you flagged and I never said it was safe, Just that this is how mine have run. Can you actually read?

**Comment by Scribsink** [comment]
Since pokebot is up and running i got 2 new account.

One lvl 26
One lvl 17

Both no warning, no softban and its working like a charm.

But i get it that one day ill be banned again.

So what? New account new adventutes

**Comment by OmegaMutant** [comment]
I am curious.  How do you know that you did not receive a softban....Mr. Fake Facts.....Trumps's Fake News :P....

Pokebot is automatically set to bypass softban....

![2017_03_30_15_56_17](https://cloud.githubusercontent.com/assets/25358852/24523824/61e2bb86-1562-11e7-92cf-85d16f03a02d.png)

**Comment by pokepup12** [comment]
I switched auto bypass off you fucking retard.

**Comment by OmegaMutant** [comment]
Sure you did.

**Comment by OmegaMutant** [comment]
you still making false facts

**Comment by OmegaMutant** [comment]
Wanna Be Beta Test....wow....that would be a GREAT JOB, NOT!
Are you that guy they have been talking about with 47 Accounts in the next strand - The Simple Truth???? I was wondering who that was....i am going on a limb and guessing that You're THAT GUY.....Too funnah!!!

**Comment by OmegaMutant** [comment]
Here is a FACT for you....keep using pokebot, and eventually you will get banned :)

**Comment by pokepup12** [comment]
No I'm not, you're wrong AGAIN. incidently I Am a beta tester for websites. I sit down and operate them under an eye scanner and them provide feedback to improve their sites based on that. You've really made a cunt of yourself there. 😂

**Comment by OmegaMutant** [comment]
"I've been testing bot variants to see what gets flagged and what doesn't."

That would require you have been testing that as well.....or is that not a FACT

**Comment by pokepup12** [comment]
Do you get paid to test websites you fucking chump.

**Comment by OmegaMutant** [comment]
"I've been testing bot variants to see what gets flagged and what doesn't."

That would require you have been testing that as well.....or is that not a FACT

**Comment by OmegaMutant** [comment]
yeah....just as i thought.....partial fact.....i bet you did not even change the setting....now you can suck my DICK

**Comment by OmegaMutant** [comment]
hook, line, and sinker....another chump bites the DICK

**Comment by OmegaMutant** [comment]
By the way, if you ever need a lawyer....

call me....BITE D's NUTZ

**Comment by pokepup12** [comment]
No, that's a hypothesis.

**Comment by pokepup12** [comment]
If I need a lawyer I'll get one that's articulate, can construct a proper sentence and that can gather their thoughts into one constant argument and present actual facts rather than than mashing the keyboard and sees what comes out. Unfortunately as you fail to meet any of this criteria I'd rather take legal advice from a crack addled chimp.......at least that would be more coherent.

**Comment by OmegaMutant** [comment]
"I've been testing bot variants to see what gets flagged and what doesn't."

That would require you have been testing that as well.....or is that not a FACT
Your statement is not a hypothesis....you said it.  Which is it?  Did you test those variants where the auto bypass was deselected by yourself or were you just pretending to be a BETA TESTER?

**Comment by OmegaMutant** [comment]
Your argument is flawed and you are a FAKE wanna Be Beta Tester

Bite Dz Nutz Biotch

**Comment by OmegaMutant** [comment]
I WANNA BE A BETA TESTER :p
I WANNA BE A BETA TESTER :p
I WANNA BE A BETA TESTER :p
I WANNA BE A BETA TESTER :p
I WANNA BE A BETA TESTER :p
I WANNA BE A BETA TESTER :p
I WANNA BE A BETA TESTER :p
I WANNA BE A BETA TESTER :p

**Comment by OmegaMutant** [comment]
Hey man!  You win!  I admit defeat!

Where do i sign up to be a Beta Tester :P

**Comment by OmegaMutant** [comment]
PokePup12, since you have been following me around, i started digging around the closed files and a bit confused about some of the things you have to say :)

![pokepup12 23 days ago ban warning all accts](https://cloud.githubusercontent.com/assets/25358852/24586413/1f100c92-176e-11e7-85d9-a00bb83b849a.jpg)

That sounds like a different person with the posting you made in here 4 days ago

![pokepup12 4 days ago no ban warning all accts lol](https://cloud.githubusercontent.com/assets/25358852/24586419/37a28654-176e-11e7-8e87-1b3e79d2d4cf.jpg)
