### ISSUE TITLE
Can't disable Pokemon Transfer and catch

### ISSUE THREAD

**Issue by crownoss** [PokeBotPub/PokeBot-Android#37]
when i use the 1.0.10 version, i can disable pokemon transfer duplicated with uncheck it and uncaught pokemon with uncheck it and just collect potion and balls.
after i use the 1.0.11 version, i can't do that again, all my pokemon duplicated has transfered. :(
i use the the 1.0.12 and its still same :( all of my account was lost duplicated pokemon, then how i can fight om gym?
please give the disabling menu for pokemon catch and transfered.
now i only have 1 units of all pokemon :(

**Comment by aryaputrapande** [comment]
Yes.. please fix this problem soon.
Btw... your app is great.

**Comment by VINORKMEN** [comment]
Same here. I have tried to disable the autotransfer but it stills transfer all my dup pokemon. Also tried to enable autotransfer option but keeping 15 dup pokemon at max option, but again, stills transfer all my dup pokemons. Thanks a lot for an excellent app and thanks in advance for give us a solution for this issue. n.n

**Comment by Freshink808** [comment]
When you open transfer list and press save and press back dont press the save button. Basically if i open pokemon upgrade then click on upgrade list and change it to my licking,i then press save at the bottom but now when you press back do not press save again at the bottom. It will reset what was done in the upgrade list.
