### ISSUE TITLE
Thanks to programmers again, thank you!

### ISSUE THREAD

**Issue by ck44064** [PokeBotPub/PokeBot-Android#371]
Hello everyone, for a few days ago I am online on the program development team staff questioned and criticized, I gave a hundred thousand points on the apology, because pokemon go update, so that we are disturbed when running pokebot, thank the development team Efforts to hope that the development team staff in each game update, notify the pokebot users, whether to update, so that we can determine whether to suspend the operation waiting for updates, and finally, thanks to programmers again, thank you!

**Comment by OmegaMutant** [comment]
Hey man!!! Don't apologize.  You pay money to use their bot.  If anything, they need to apologize to the customers.....yes, you and I are customers.  You pay money monthly, right?  You're a customer.  If pokebot does not deliver or they are negligent about warning us, then we should be ready to walk away from this program and pursue other bots.  If anything, pokebot team needs us.  

Don't take it from me.  Read the other threat, "About Last Week."

PokeBotPub:
"We are trying to do best. You can use Pokebot or don't. Pokebot is working with PokemonGO 0.57.4 version."

Me:
"That is very irresponsible of you. Shame on you PokeBotPub!!! You apparently do not care about your customer's accounts! When Niantic decides to force the upgrade and you are using the bot at the time, bye bye account!!!!! TERMINATED. Were you going to warn your customers of this eventuality? You could always blame the customers. You cheated!!! That is life. But this is a prime example of your negligence and the customers should be mad!!!!!"

**Comment by ShairaMaex** [comment]
When you paid for the services of Pokebot, they gave you access to their
software for a certain number of days, actually it was listed in hours. And
it is just a simple count down timer. So, the fact that any time there is
an issue, and the Pokebot team issues us all 2-3 Days extra time, is, in
fact, a gift. Because NONE OF US LOST ANYTHING. You still have the same
amount of time remaining no matter how long it took them to re-invent the
wheel and get their Cheat System back functioning. Just because you don't
use the system for 1, 2 5, or 10 days, for whatever reason, you don't lose
a single minute of the TIME you paid for. They are not Required to credit
us with anything, they do it as a customer service, and I appreciate it.

like what this guy comment with thebother thread. .. if u dont like the
service dont fucking use itm and dont try it again. we are appreciate what
dev team did for us. w

**Comment by OmegaMutant** [comment]
Show some initiative.  You are just regurgitating what was already said by someone else.  Do you even have an original thought of your own.  I suppose your above comments speaks for itself.

Your a FAKE Customer service person.

**Comment by ShairaMaex** [comment]
Who said im a customer service support wtf?. I just repeat what the other
guy said in thebother thread wtf i did not copy wtf

**Comment by ShairaMaex** [comment]
i do personal emails to the dev team. just get out here snitch.

**Comment by OmegaMutant** [comment]
I know who you really are Xavier G.  You're a fake

**Comment by OmegaMutant** [comment]
reread your response to my post.  You have low intelligence for a Pinoy

**Comment by ShairaMaex** [comment]
LOL THIS IS MY IGN NAME. what a idiot fucker. my real name xavier g

**Comment by OmegaMutant** [comment]
duh...u cant real either.  I just called you out on your name b4 u said it

**Comment by OmegaMutant** [comment]
reading is fundamental....you are beneath me....get lost

**Comment by OmegaMutant** [comment]
Pokemon GO Bot – CrazyBot for OS X/Windows – now Free
SIGN UP - customers should not take the abuse they get here!!!!
http://fandomfare.com/2017/02/12/pokemon-go-bot-crazybot-for-os-xwindows-now-free-2/#comment-3803

**Comment by ShairaMaex** [comment]
YOU GET LOST. YOU KEEP CRITICISING POKEBOT AND ITS DEV TEAM.

**Comment by OmegaMutant** [comment]
I call it like i see it.  your just a fake pinoy with low esteem b/c your life suck

**Comment by OmegaMutant** [comment]
Dont act like you did not say bad things about the develop team....you phonie

**Comment by OmegaMutant** [comment]
your the one that gave me the scoop on how they really operate....thanks for that....chump

**Comment by ShairaMaex** [comment]
Bye Dick 👋

**Comment by OmegaMutant** [comment]
always complain on how they do not give you enough money....how they called you a FAKE customer service person

**Comment by OmegaMutant** [comment]
Yeah....i get it....BREATHE.....the truth hurts

**Comment by ShairaMaex** [comment]
hahaha bye dick. u snitch. no one likes a snitch bitch

**Comment by OmegaMutant** [comment]
what does that make you.....telling me all that crap about pokebot

**Comment by OmegaMutant** [comment]
that is an informant....that is same as SNITCH

**Comment by OmegaMutant** [comment]
Take a hard look in the mirror.....did you see the SNITCH

**Comment by OmegaMutant** [comment]
he wears your face

**Comment by ShairaMaex** [comment]
Oh really i just said only  dont wont pay me for chatsupport i dit. wtf u
fucking snitch. never told secrets about pokebot idiot fucker.

**Comment by OmegaMutant** [comment]
Yes, feeble attempts to clean it up....too late for that!  You let several lines go without a proper defense....you let your anger get the better of you....SNITCH    FAKE SUPPORT

**Comment by OmegaMutant** [comment]
It's gonna be okay.  Just have to admit that you don't have the skill set to be part of this project.  The soooner you get to that the sooner you can suck my DICK

**Comment by ShairaMaex** [comment]
who said im a official support of pokebot? your the fucking idiot .

**Comment by OmegaMutant** [comment]
aaaaaahhhhhh....did you forget who i am.....

**Comment by OmegaMutant** [comment]
hahahahahahaha

**Comment by ShairaMaex** [comment]
Really snitch? stop complaining go back to your man cave.

**Comment by OmegaMutant** [comment]
go back to the hole in the banana trees

**Comment by OmegaMutant** [comment]
Yup....low intelligence for a Pinoy....did you even finish 6th grade?

**Comment by OmegaMutant** [comment]
See???? you have no skill set as a customer service chat support....that is why development team should not pay your sorry arse

**Comment by ShairaMaex** [comment]
lol are u a customer even. 😂😂

**Comment by OmegaMutant** [comment]
haha....now how would that look.....if i am not a customer and you told me all those things about pokebot.....SNITCH

Pokemon GO Bot – CrazyBot for OS X/Windows – now Free
http://fandomfare.com/2017/02/12/pokemon-go-bot-crazybot-for-os-xwindows-now-free-2/#comment-3803

**Comment by OmegaMutant** [comment]
send your resume....you can use me as a reference....i will tell them that u suck dick

**Comment by OmegaMutant** [comment]
For a few gift cards, you might throw in a surprise

**Comment by ShairaMaex** [comment]
which one hahaha?

**Comment by OmegaMutant** [comment]
Wow...Greedy....you want them both....my left nut or right nut or both.....tea bag

**Comment by OmegaMutant** [comment]
i am giving you a new pet name...."Tea Bag"

**Comment by OmegaMutant** [comment]
YAWN.....gonna spend time with my other whore....PlayStation....later chump....dont be talking about pokebot anymore

**Comment by pokepup12** [comment]
I hope you die horribly you worthless piece of shirt.

**Comment by OmegaMutant** [comment]
Hey development team!  "Pokepup12 is a wanna be BETA TESTICLE that needs a job....Can you give him a HAND 📦 
AAAAaaaaaahhhhhh, that is sssoooooo cute!  I got a stalker fan.....every thread i interact in....he is like a puppy dog that wants to eat my shit.  In a few minutes....That steak i ate the other day will show up in the next bowel movement....i will get a bowl out for you.

You really should consider a career change - night school on the corner street in the red district.... It is clear that your LIFE sucks.

Apparently, you do not have anything constructive to add to this thread, Thanks Programmers, you will have to go back and BETA TEST that porn website to place an order for that DILDO that you have been eyeing for the past month? Take the plunge....Don't be a hypocrite....you know you wanna..

I see that you are fantasizing about me AGAIN
pokepup12 posted, now closed thread,"I hope an aids ridden biker fucks you in the eye you worthless leeching piece of shit ." Did you visualize yourself as the A.I.D.S. ridden biker boy or am I the biker boy?

It's very flattering that you followed me to this thread. Did you miss me?

Here is a THOUGHT!!!! Start your own thread and i will visit you like:P  Lights on or off..you decide

**Comment by pokepup12** [comment]
Ha ha ha, obsessed much? What a wanker. 😂

**Comment by OmegaMutant** [comment]
PokePup12, You can stop following me around!
You follow me, its only fair i lay out more bread crumbs....

![pokepup12 23 days ago ban warning all accts](https://cloud.githubusercontent.com/assets/25358852/24586505/c4e7211c-1770-11e7-96a5-4aad7cb739da.jpg)

I bet you like your "SHITTY" TACOS crunchy

![pokepup12 4 days ago no ban warning all accts lol](https://cloud.githubusercontent.com/assets/25358852/24586509/f4de61b4-1770-11e7-87af-d9dd4ef2320a.jpg)
