### ISSUE TITLE
Dev team need IMPROVE on NIANTIC's TRAP 

### ISSUE THREAD

**Issue by KingSiq** [PokeBotPub/PokeBot-Android#372]
Dev team said Pokebot is safe , YES it is SAFE WHEN the algoritm is MATCH with the current PoGo version.

But as my opinion, Niantic send the Trap for Us.
Update Trap and Non Update Trap.

**Update Trap,** of course we are know when PoGo update , please wait pokebot also update. but this also we do not know about the update from pokebot already match or not, like before pokebot update many times to match the new PoGo version.

**Non Update Trap**, this like pokemon wearing hat or shiny pokemon or "GOT IT news" or others.... it is means PoGo change something in their app even they not update. like this pokebot also need to update match the different.

I suggest Pokebot have to FORCE CLOSE if Niantic make a TRAP with change something, this to protect your Customers.
Also my opinion if you already get in a Trap,, maybe they still let you GO but this about of time or a certain high level to BAN you. Directly.

Thats all my opinion, sorry if I'm wrong , no need to FIGHT because of all the CHOICE depends on YOU to use pokebot or not.

And also the last, this is your choice to cheat or not.

THANK YOU.
.

**Comment by ck44064** [comment]
well said!

**Comment by OmegaMutant** [comment]
I don't care what the others say about you.  I like you King!  You give enough information to make an informed decision.  I agree with all those things you have said.....Unfortunately. i am shocked that the development team is not jumping on this before you.  I am sure they have an excellent explanation for us

**Comment by OmegaMutant** [comment]
Hey.....crystal ball says...."you can use it or don't....It's your choice."

**Comment by OmegaMutant** [comment]
The trap will definitely trigger between level 25-26

**Comment by OmegaMutant** [comment]
Its a decision tree.....too many soft bans.....fall into trap.....FINISH HIM - FATALITY (Mortal Kobat)

**Comment by pokepup12** [comment]
Omegamutant. I hope an aids ridden  biker fucks you in the eye you worthless leeching piece of shit .

**Comment by OmegaMutant** [comment]
Pokepup12, you are such a FUCKTARD!
You wanna be a BETA TESTA for Dildo's!

Did you want to add your two cent to this thread or do you wanna place an order for your DILDO?

**Comment by OmegaMutant** [comment]
Pokepup12, you are such a FUCKTARD!
You wanna be a BETA TESTA for Dildo's!

Did you want to add your two cent to this thread, Niantic's Trap, or do you wanna place an order for your DILDO?
