### ISSUE TITLE
Safety Snipe

### ISSUE THREAD

**Issue by masztron** [PokeBotPub/PokeBot-Android#373]
It will be this option to safety snipe?

**Comment by pokepup12** [comment]
It might be, stop being a pussy and try it.

**Comment by OmegaMutant** [comment]
Pokepup12, you are such a FUCKTARD!
You wanna be a BETA TESTA for Dildo's!
How in the world is this guy gonna test a feature that does not exist in pokebot, MORON!!!

It seems to be that masztron might have limited English
I think he is asking if pokebot has a safety snipe feature?  I have read articles dating back in August 2016.  There was a feature that allowed trainers to decide which pokemon to catch by showing each pokemon's IV stats.  As far as i can tell, there is no such feature in the current pokebot version.  It would be nice to have in the upcoming pokebot version.  I could use one device (bot acct) to show me where the desirable pokemon is and use a clean phone (no bot) to walk over and manually catch them.  As it stands, anyone using a stand alone poke snipe got their acct banned.....i never got the chance to use one....that was before i was even playing this game.

**Comment by Scribsink** [comment]
Its safe if you not abuse the bot. Im a level 27 now only using pokebotpub no softban no ban warning nothing. Just use the bot till you reach 100.000 stardust. Then wait 24hrs and do it again. And again and again.

**Comment by LuciferHawk** [comment]
Safety Snipe?
I wish!

Pokemon Capture Settings: masterball and ultraball are set at 98%.  It would be nice if we had an option for the regular pokeball.  

I want to skip all the weak pokemon so the bot can move towards the high IV (98%) ASAP.

**Comment by LuciferHawk** [comment]
My new account is now level 22.  Looks good after 2 days.  Will wait 24 hours and run my level 37

**Comment by Scribsink** [comment]
Yeah i like how it is now. I hope they keep it updated as soon theres a new api.

**Comment by krakmh** [comment]
I was using Pokemon [Fly GPS](https://bestforandroid.com/fly-gps-apk/) before and it was causing a lot of bans for me. Is there any ban issue with Pokebot?
