### ISSUE TITLE
Lost Connection, lost connection again, and again,and again

### ISSUE THREAD

**Issue by AbiDez** [PokeBotPub/PokeBot-Android#375]
ATM i lost every minute the connection... What the hell is going on?
Next thing, pokebot is updated to 59.2 ... Ok great, but in my county is no 59.2 available in store

**Comment by Sangputri2006** [comment]
In Places is the same, the connection is not stable, within an hour could be fifteen times re-connect

**Comment by mungiaman** [comment]
Okay it gets worse. It kept doing the reconnect thing. Then it said it was out of.pokeballs when I had like 50. The strange thing was there was no possible soft ban warning peppered in as it usually does. I am worried. I was just trying to build up my kids accounts. They love this Pokemon go but have so little free time to play it. I hope I didn't screw everything up for thier accounts. Has anyone else had it acting screwy like saying you were out of things and you had them in your pokebot inventory bag. When do you figure they upgraded. How long does it take for a account to be pulled. So far no notice in my email accounts. Any info would be helpful thanks.

**Comment by AbiDez** [comment]
Yeah I had this, too... But only 2-3 times, the pokemon is fleed... We ran out of Pokeballs... Surprise, surprise oO
But have many Pokeballs ^^

**Comment by OmegaMutant** [comment]
mungiaman,
You will NOT get an email notice if you are PERMABAN.  Niantic may have done that back in August....not anymore...

I would stop using pokebot on your kid's account!  Have you noticed "Re-connecting in 5 seconds?"  If Niantic decided to force update (0.61) and your bot is attempting to run 0.59 API....You're gonna get "Roasted!"
