### ISSUE TITLE
PoGo 0.61.0 FORCED UPDATE

### ISSUE THREAD

**Issue by OmegaMutant** [PokeBotPub/PokeBot-Android#376]
Niantic released a new version of PoGo in Google Play Store.

I logged into PoGo.  No forced update.  The 3rd party flag I had 3 weeks ago is gone ('bout time).  I would not be surprised if they were tracking my behavior for later CORRECTIONS....just because the 3rd party flag is gone....I know I am still under the radar.  Going to play PoGo manually until PokeBot releases an update.  PLEASE..... don't make us wait 8 days this time .... LOTS OF LUV

**Comment by OmegaMutant** [comment]
Wow!!!!! I am slipping!!!! I got a msg that my phone had updated PoGo to latest version 0.61.  When i created a 2nd account on my phone, I did not tweak my settings .... "Do Not Update Manually"

**Comment by Scribsink** [comment]
Update asap!!!!!!

**Comment by LuciferHawk** [comment]
Update has been forced,  Pokebot, it is time to roll out that update.

![2017_04_08_16_30_421](https://cloud.githubusercontent.com/assets/26841844/24832320/7a9f7dc4-1c7b-11e7-920e-31176c41d16a.png)

**Comment by LuciferHawk** [comment]
Update has been forced.  I am going to WAIT for Pokebot to release update before I use the bot again.

![2017_04_08_16_30_421](https://cloud.githubusercontent.com/assets/26841844/24832346/05387292-1c7c-11e7-8a08-527622532d9e.png)

**Comment by OmegaMutant** [comment]
AWESOME!
Thank You Development Team!  Going to run my starter account on it first.
