### ISSUE TITLE
maj 1.0.49 impossible 

### ISSUE THREAD

**Issue by majinkrys6** [PokeBotPub/PokeBot-Android#377]
hi impossible maj 1.0.49

**Comment by OmegaMutant** [comment]
It works on my phone!
What do you mean by "impossible?"

**Comment by majinkrys6** [comment]
I can cancel the maj but not install the download this fact but can not open the file

**Comment by majinkrys6** [comment]
its good juste bug my phone srry

**Comment by OmegaMutant** [comment]
I suggest loading it "sideways."  This happen to me too.  You need APKPURE or an APK installer.  That is how i got my file to work and run on my phone.
