### ISSUE TITLE
Is it safe to use bot?

### ISSUE THREAD

**Issue by Ger11** [PokeBotPub/PokeBot-Android#378]
Have you used the Bot yet? Any good or any problem?¿Is it safe to use with the new update?

**Comment by AbiDez** [comment]
??? Will you repeat the same question on every update? 
It's safe, so long you work as human... 
Everybody has its own settings... 
Slowly.... Slowly... That works (mostly)

**Comment by OmegaMutant** [comment]
Ger11
REALLY???!!!!!  How many threads you gonna open on the same issue???
LISTEN!!!!  
Open a starter account.  Give the bot a whirl/spin/tryout.....make sure you get past level 27

Just like AbiDez said, "work as human."  Run the bot without breaks may be construed as bot activity.  I do not know about you, I refuse to walk around for 8 hours straight without a break and a lunch!!!!!
