### ISSUE TITLE
Can't connect to Niantic Server - Ban Hammer

### ISSUE THREAD

**Issue by OmegaMutant** [PokeBotPub/PokeBot-Android#379]
I noticed the repeating message and shut down pokebot.  Both devices have their own internet.  This started at the same time.

Pokebot just will not work and i made my payment yesterday :(

**Comment by OmegaMutant** [comment]
Yup!
I suspect its a Ban Hammer!!!!
"Unable to authenticate.  Please try again."
I have been working on those two accounts for about two months and got to level 28

Level 17 account works with pokebot

I hope my level 30 account is okay....i have not used pokebot on it for 1 month

**Comment by KingSiq** [comment]
CONFIRMED... BAN WAVE START...

**Comment by OmegaMutant** [comment]
Ha....Just like in December....3rd party warning....ban in January
3rd party warning last month.....ban this month

Hmmmmm my level 17 & 19 accts was not touched and i used a bot.

So far....
At first, i ran bot in 3 hour increments (Dec-January

2nd go, i ran the bot in 1 hour increments (March-April)

The only common denominator that i see was not going past level 25 and i did not get banned.

Well, my next project is to use pokebot to strictly collect high IV pokemon by sniping to the location once a day

There does not seem to be any point to level up....sniping is my new focus.

Eventually, harvest those pokemon for later, legit accts.

**Comment by Scribsink** [comment]
It does not matter what u will do. Everything uses third party login for pogo will get banned.

I lost all my accounts lvl 15 - 35 today and yesterday. No matter how u will do it, when cheating you will lose it.

**Comment by OmegaMutant** [comment]
Scribsink, 
I still have a level 29 acct that still works 2 days in a row.  This account got the 3rd party warning 3-4 weeks ago which was a surprise.  I stopped using a bot with that acct back in January's ban wave [one of my original accts since October

After the 3rd party flag, i created 2 starter accts...ey never got the 3rd party flag and are now level 15 and 19.  Still works

My other 2 accts that i had on cold sleep since the 3rd party flag are ban.  I must have used pokebot at the time of the warning.
I stil use IV FLY to check my pokemon's IV's.....level 29 acct still works
