### ISSUE TITLE
To BOT or NOT BOT?  That is the question

### ISSUE THREAD

**Issue by LuciferHawk** [PokeBotPub/PokeBot-Android#386]
If you use Pokebot, there is a high likelihood that your account(s) will get terminated.  My main acct is the only one i have left.  All my side accts are permanently terminated.  These past 4 months i have tried various bot strategies on various accts (now banned).

All my recent acct got the 3rd party warning....It is a matter of time before those accts become inaccessible.

I have been waiting patiently.  I do not see any evidence that the pokebot is able to avoid detection.  Even if you run the bot "human-like" Niantic still brings the BAN.  Pokebot can't hide from Niantic.  Pokebot CAN NOT stop the ban.

It is plain insanity to keep throwing money at this obsolete bot!  You might as well make the bot free again!

Several options to consider:
1) Find a different bot (ninja)
2) stop payment and Wait for pokebot 2.0 (I am incline to select this choice)
3) quit cold turkey

**Comment by AbiDez** [comment]
Well the truth is, stop botting.... It's a cat and mouse game and we are the loosers... I lost every account when botting, and I play human like... 
The last account have a 3rd warn flag after last ban wave, I don't bot it again and my account is still alive..... Warn flag is gone....There's other solution, not only botting...

**Comment by LuciferHawk** [comment]
Last month, i had the warning flag go away.  I did not use bot after the warning flag.  about 2-3 weeks after the flag went away, my 3 accts got banned.  Since i played human like, i attempted to appeal.  Email said that they i broke the TOS.....not much else was disclosed in email.  I only earned 40-50k exp daily.....Its not like i was trying to slam dunk to level 40 in 1 month!!!!!

I have 3 recent acct created near the end of last month.  The warning flag went away for 2 of them.....i just got a warning flag on the 3rd acct.....WHY????  I stopped botting when my other 2 accts got the flag....Niantic must be slow.....I suspect that they are running security check software once a week.

All said and done.  It will be like last month.  Even though i stopped the bot and l log in normal to play a little a day on 3 different devices....i will still get the BAN....after weeks of normal play.

**Comment by pokepup12** [comment]
It's coming. 3rd party warning, special event, ban wave. Seems to have followed that pattern over the last six months or so. I suspect some accounts will disappear next seek.

**Comment by LuciferHawk** [comment]
It is starting to feel like i am spinning a wheel in a hampster cage.  Make accts...lose accts... No mo $ for pokebot until they can develop a viable bot that can avoid detection...make bot free again

**Comment by LuciferHawk** [comment]
Hmmm, 4 days ago i have read that there was a pokebot 1.50. Today, there is a pokebot 1.51. I have paid 4 months subscription. Plz make bot free again. If i can get to level 35 without getting ban...play human like...luv to give money....these last few months....i get ban for reaching level 28 - 29...human like play.... 2 months to get to those levels
