### ISSUE TITLE
more pokemon catch

### ISSUE THREAD

**Issue by jccompagnon** [PokeBotPub/PokeBot-Android#388]
it would be nice to have an option to move and stay within x meter of original location.
like if you hang at a park and just want to hang around that park for a nest

**Comment by PokeBotPub** [comment]
@jccompagnon Pokebot 2.0.0 is in the development phase. We increase pokemon radar to 3x. (In the case of theoretical, not tested yet)

**Comment by jccompagnon** [comment]
yes but that does not prevent the player from walking away.
I would like my trainer to stay within 50 meter of where I drop it for example

**Comment by LuciferHawk** [comment]
Hey!!!!  That has been on the wishlist for at least 5 months now.....i want my trainer to walk around the perimeter of the lake so that i can increase my chances of catching dratini or lapras......NO......it walks into the city for an hour
