### ISSUE TITLE
gmail problem

### ISSUE THREAD

**Issue by RevanStark** [PokeBotPub/PokeBot-Android#389]
I keep getting logging problems, if i use gmail i get
 Problem to authenticate your account. Please try again
I have tried the trainer way but cant login there eather? 
What am I doing wrong? 
Thank you for your time
Revan

**Comment by PokeBotPub** [comment]
https://github.com/PokeBotPub/PokeBot-Android/wiki/How-solve-%22Needs-Browser%22-problem%3F
