### ISSUE TITLE
The app work slowly... 

### ISSUE THREAD

**Issue by djvrasna** [PokeBotPub/PokeBot-Android#393]
Hello i just bought a key. I need 3min to log in with my Google account. 5 min to do one step... The app just don't work..... Someone for help???

**Comment by reiki2017** [comment]
Same problem .the app is so slow.... Damn!

**Comment by lemmzz** [comment]
Here the same what is going on the bot doesn't work

**Comment by lemmzz** [comment]
Bot Works Again fast ty alot
