### ISSUE TITLE
can't farming

### ISSUE THREAD

**Issue by leecg** [PokeBotPub/PokeBot-Android#396]
i was login to poke bot app use phone Android 7 ,  use google account.  but take long time to connect to google account, after connected , press play, but show start farming,  was  not  moving,     
Thanks if you got time  can u  help to  look what is the problem,   i was ban more than one month, alot of mom i can't see and catch!!   i was  pay n receive code yesterday
Thanks  you  very much

**Comment by djvrasna** [comment]
Same problem .the app is so slow.... Damn!

**Comment by reiki2017** [comment]
Same problem .the app is so slow.... Damn!

**Comment by lemmzz** [comment]
Here the same bot doesn't work or walk slow

**Comment by leecg** [comment]
Thanks  Bother,  see  like  okay  now,  Thanks  you so  much
for your  Hard work  👍 
Thank  You 👍

**Comment by lemmzz** [comment]
Yea bot Works Great Again ty alot 🤗

**Comment by djvrasna** [comment]
Yeah seems better today. Thanksss 😃

**Comment by leecg** [comment]
BRO,did u play world of warship?
Thnaks
