### ISSUE TITLE
Can't login 

### ISSUE THREAD

**Issue by kayoes098** [PokeBotPub/PokeBot-Android#400]
Hello the app was working last night and now today it won't run  wondering what I can do 
Using Google account

**Comment by kayoes098** [comment]
Same with ptc accounts can log in but the program wont run

**Comment by TYTBOOM** [comment]
Same problem started this morning😞

**Comment by TYTBOOM** [comment]
Hope their a better update coming up!

**Comment by dajukz** [comment]
i have the same issue with the screen stuck on "Connecting ptc account" (cause i have trainer club)

**Comment by TYTBOOM** [comment]
I have 3 phones on Google accounts and all of them are not working,😭

**Comment by aldodan17** [comment]
Dont run in my account :(
Please fix this :(

**Comment by TYTBOOM** [comment]
Finally working give it a day and it should work,

**Comment by aldodan17** [comment]
Ready?:(

**Comment by aldodan17** [comment]
It Stoll does nota work ,someone work The app?

**Comment by gumby420** [comment]
Does it need an update with the pokemon new update cause its not working and only a week into the full month that was paud for. Have a great number of the spoofing community in my group of 22k wanting a review and like to give them a good one. It will just not connect to any google account last couple days.

**Comment by pkmntopdresseur** [comment]
Nous avons besoin d'une mise à jour 
 Je continue de payer ce bot fonctionnel et efficace (lvl38 sans BAN ) , mais depuis quelque jours le bot ne commence pas la récolte. Il peine a la connexion au compte google
