### ISSUE TITLE
Stuck on connecting Google accounts 

### ISSUE THREAD

**Issue by made4la** [PokeBotPub/PokeBot-Android#405]
As the sub says I stay stuck on "connecting Google accounts " with just the spinning wheel.

**Comment by TYTBOOM** [comment]
Same stuck on connecting Google account since yesterday

**Comment by TYTBOOM** [comment]
At the worst time possible right after I get my Pokemon go account back from being banned for 2 weeks for boting

**Comment by TYTBOOM** [comment]
Working now yay!!!

**Comment by gumby420** [comment]
Back to not working tue oct 17 hope it runs come halloween event

**Comment by pkmntopdresseur** [comment]
Me too :/

**Comment by pkmntopdresseur** [comment]
Nous avons besoin d'une mise à jour 
 Je continue de payer ce bot fonctionnel et efficace (lvl38 sans BAN ) , mais depuis quelque jours le bot ne commence pas la récolte. Il peine a la connexion au compte google

**Comment by made4la** [comment]
I know I've been banned. I have not received an email from niantic but I have searched the error I'm getting when I try to log onto the game with my account. (Failed to load data). Permaban.

**Comment by pkmntopdresseur** [comment]
shit. What error did you make? I received the warning banner this morning

**Comment by pkmntopdresseur** [comment]
Personne ne répond sur pokebot2018@gmail.com 😭😢

**Comment by kingkrush47** [comment]
ouais ça me soule aussi j ai payé 10€ la clé et pour avoir un plantage automatique a chaque fois que je veux me connecter !!

**Comment by dodemans** [comment]
Mine is stuck again how to fix

**Comment by angelxprovip69** [comment]
Yes Ian make a video With this froud Ian upload to Youtube

**Comment by angelxprovip69** [comment]
Yes Ian make a video With this froud Ian upload to Youtube 
![screenshot_2018-07-09-07-34-58](https://user-images.githubusercontent.com/41025612/42481879-9c1e56a6-83b2-11e8-949e-049e6469f226.png)
