### ISSUE TITLE
UNFORTUNATELY PokeBot HAS STOPPED error

### ISSUE THREAD

**Issue by tomczukowy** [PokeBotPub/PokeBot-Android#406]
i see this error after trying to log to PokeBot. i try everything: reinstall app, stop the antivirus etc. first day when error shows was 15th Oct.  please, do something with this. i like your app and i don't want to make any chargeback.
i don't have any ban on my google/pokemon go account

**Comment by kingkrush47** [comment]
hi , i have the same problem !!! please help us we are pay for this .... 10$ for nothing because has stopped :/

**Comment by elviscaveres** [comment]
I also have the same problem, everything is set up and when I start the pokebot, I sell a black screen and then return to the same start screen

**Comment by sander021** [comment]
Queria meu dinheiro de volta  botpkernao pega só dá err o

**Comment by paul1590** [comment]
i have pay and cant use this app pls solve the problem and give us more time

**Comment by silvia1976** [comment]
Je paye 10 euro par mois pour pokebot et ça fait une semaine que l'application se ferme impossible de la faire marcher et j'ai payer 10 euros pour rien comment faire ?

**Comment by hakuxs** [comment]
I having same probl3m said sever down or what they doing wait 2 day for them respond back email them for the code even show them proof I bought it and nothing imma bought take this to court sue thier ass for stealing money.

**Comment by silvia1976** [comment]
Pourquoi pokebot ne marche plus je paye et rien du tout c'est pas normal on reçoit même ma le code d'activation

**Comment by hakuxs** [comment]
English I didn't understand what ur saying at all if it not working I want
refund back.
