### ISSUE TITLE
Ban Warning

### ISSUE THREAD

**Issue by DuffyMcGhee** [PokeBotPub/PokeBot-Android#408]
I haven't used Pokebot for at least 4 months.

But that doesn't matter, I was informed this morning that my account was terminated for breaching the rules, and more specifically (they used a longer explanation) for using a Bot.

This is the only one I have EVER used.

So brace yourselves, it is coming.

![pogoban](https://user-images.githubusercontent.com/26755002/34488616-2b419528-efa7-11e7-8f75-ae53ecbaabc9.PNG)

**Comment by xdreamboat1919** [comment]
I have heard this before a year ago, pokebot team can;t fully insure about the ban, its about the risk using the bot itsself a risky decision. 4 out 5 my accounts didnt recieve the ban warning. there is a limit using the bot and certain limit area can the bot moves and farm pokestops. and limitation of pokestop too.
