### ISSUE TITLE
On start connecting to google account stuck issue

### ISSUE THREAD

**Issue by Nana869** [PokeBotPub/PokeBot-Android#411]
when i press start button it gets stuck to "connecting google account". Please help, i only got 29 days left and haven't played once after payment.
![screenshot_2018-05-02-11-49-59 1](https://user-images.githubusercontent.com/38904803/39517140-485f21b4-4dff-11e8-96ea-b54fa39c0cd7.png)

**Comment by madbot09** [comment]
I have the same issue

**Comment by thebull123** [comment]
I am having the same issue just payed for a key and nothing works

**Comment by Mambeast15** [comment]
I'm having the same problem

**Comment by jameswonder18** [comment]
Hello everyone greetings 
My name's James I live I am 18 years old and live in a rural area my all day is spend working and looking for my ill mother I don't have enough time to play it in the beginning I used to use pokebot which was really help full my younger brother just turned 10 now he is a big fan of Pokémon but from the time it is has turned paid I have stopped using it now I heard from a friend that trade comes out I really wanted to play and caught more as generation 3 is also added but could not becaue I can't pay its even hard to pay the rent of our home and the expenses of my mother medicine if any one could help me it will be his greatness may God bless him in this world and afterlife all my prayers are with you have a happy day guys

**Comment by jamester80** [comment]
Did u guy figured how yo fix it
