### ISSUE TITLE
stuck in connecting to google account

### ISSUE THREAD

**Issue by clippe07** [PokeBotPub/PokeBot-Android#412]
![screenshot_20180701-102246](https://user-images.githubusercontent.com/40728056/42131082-d94c71bc-7d2b-11e8-9ecb-7dc559335b79.png)
any way to fix dis?

**Comment by Alexyk77** [comment]
Me too!I have already lost a day.Refund or extension?!They say you can donate but you also must pay for the service.Then call it a paid service not  a donation.

**Comment by jamester80** [comment]
Stuck on that shit too just both the key and cant log in wtf

**Comment by SrlokyS2** [comment]
Também não consigo conectar minha conta do Google :/

**Comment by fatkid75** [comment]
Same issue here. Don't waste your money. Had almost a month and it has never connected.

**Comment by jamester80** [comment]
Same
