### ISSUE TITLE
Leave Best IV instead of Best CP

### ISSUE THREAD

**Issue by emddummi** [PokeBotPub/PokeBot-Android#44]
Hello, 

is it possible to priotize IV above CP for transferring?

**Comment by kenjfujma** [comment]
Yeah,i want it too,i fogot to setting it i lost my 100% magicrap

**Comment by JTM0701** [comment]
This would also be an amazing feature.

**Comment by localhost127001** [comment]
Since this feature is not implemented yet.
How if I trick it by renaming the mon by adding "+" at the end of its name?
But I'm not sure how your app decide which mon that get transfer,  is it by names or id numbers?

**Comment by JTM0701** [comment]
I'm honestly not sure how it decides. It always keeps highest cp. I could send a screen shot.

**Comment by localhost127001** [comment]
I was asking @PokeBotPub ;)
