### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by ricardojulio** [PokeBotPub/PokeBot-Android#45]
Both Google and PTC cant connect. The white box stays there forever after login, and making the configs, and pressing start. 
Shutting the app down and starting again doesnt show differences.
Android  Moto X

**Comment by PokeBotPub** [comment]
Still have problem? Can you check again?

**Comment by GGlaucon** [comment]
Hello !!

just trying to get and appears that the summer has been updated to 1.1.

But I believe you have a problem with downloading , which is not installed, it seems to be corrupted .

Verify pleae

**Comment by PokeBotPub** [comment]
Sorry, we make mistake on version update system. We fixed.

**Comment by ricardojulio** [comment]
It have been updated (previously there where a problem with the download) and I can configure the account. 
Still, the connectiong dialog keeps in screen, after pressing the start button.
![screenshot_2016-09-15-08-03-50](https://cloud.githubusercontent.com/assets/21310656/18547668/0138f8d6-7b1b-11e6-97f1-10a26c9177d9.png)

**Comment by purpleshep045** [comment]
Yes i have the same issue

**Comment by tagata** [comment]
same here ...moto x phone

**Comment by hafizg827** [comment]
Need new update..fix it..😢
