### ISSUE TITLE
Auto update fails

### ISSUE THREAD

**Issue by luckytom333** [PokeBotPub/PokeBot-Android#46]
Today it's trying to auto-update, it fails on Download with Access Denied error when trying to download APK.  Download Error: (java.io.filenotfoundexception:/ storage/emulated/0/download/pokebot_1.1.apk: open failed: EACCES (Permission Denied).

**Comment by Lololaye** [comment]
I have this same issue as well. Hopefully they'll get around to posting the link to 1.1 soon

**Comment by TriNtoro** [comment]
Please. Make option menu. 
Autoupdate : true/false.

**Comment by PokeBotPub** [comment]
Problem fixed, sorry guys. Just is mistake, not update.
