### ISSUE TITLE
SETTING ISSUE

### ISSUE THREAD

**Issue by AZZREYNAZARETH** [PokeBotPub/PokeBot-Android#49]
your bot setting and features are too complicated.. there is many thing need to setup.. im admin of POKEMON GO MALAYSIAN COMMUNITY.. Almost my group community using your bot...but after new update since 1.0.11 there are too many complaint about setting and also transfer problem..if you still go on with what your bot have now please make language translation.. if you have problems to do translation pls give us string so we can translate on behalf of you

**Comment by PokeBotPub** [comment]
We will make basic settings and advanced settings feature. 

Transfer bug is fixed on 1.0.13.

If you want to help us for translation, you can use [forTranslators.xml](https://github.com/PokeBotPub/PokeBot-Android/blob/master/forTranslators.xml). After send to pokebot@inbox.ru mail address.

**Comment by AZZREYNAZARETH** [comment]
done email
