### ISSUE TITLE
Possible softban

### ISSUE THREAD

**Issue by Sloefkeuj** [PokeBotPub/PokeBot-Android#57]
Hi guys, constantly i get Possible to softban, yesterday i played  a hole day on pokebot without problems. Can you fix it? Thanx allot

**Comment by JeffJr99** [comment]
Did you go over the Pokemon or stop limit? Only can catch and soon so many a day. Do the research.

**Comment by SuperSandro2000** [comment]
In Settings under "Speed adn Delay Settings" you need to alter:
- Max. Speed: 10
- Delay between player action: aroound 2000

You get softban because you move to fast, loot to fast and catch to fast nothing else. I use these settings since one week every night and it works flawelessly.
