### ISSUE TITLE
Device ID 

### ISSUE THREAD

**Issue by parind** [PokeBotPub/PokeBot-Android#6]
Hey I need to ask what Device ID does this use.

**Comment by parind** [comment]
@PokeBotPub Does it use a same Device ID for everyone. Or it uses the Devices Original Device ID

**Comment by qithub** [comment]
Random generate device id. Its different every device.

**Comment by parind** [comment]
Can I use my own Device ID

**Comment by parind** [comment]
And what is the server request sent by. Device IP

**Comment by qithub** [comment]
All request send to on your device. Not have any proxy server. (Mobile data and wireless support)
Can't use your own device id. We add advanced settings on next version.
