### ISSUE TITLE
Google account

### ISSUE THREAD

**Issue by Dominican2013** [PokeBotPub/PokeBot-Android#62]
Cant sign in with google account 

[Lorg.apache.http.Header;@400303d 

Error=NeedsBrowser Url=https://accounts.goog|e.com/ signin/continue? sarp=1&scc=1&continue=https:// accounts.goog|e.com/o/ android/auth?hl%3Den_us %26xoauth_disp|ay_name %3DAndroid%ZBLogin%ZBService %26source%3DAndroid %ZBLogin&plt=AKgnsbsuQS ch46q8PQJufaHe071GbgK8W6-0XyTzXWz1_3nSth5C_W VbcT3FfdPES30H908COAquJeJFCPpGPgm1up2eK61TOYXQ|LkG3K JXF76eBMugVCstfVK_gBXv5t6m-3 URVOhv2UB7uvi8|Y|20HuvyAg4iU8T IOthYBYL828k1q_g50me4GrHjB7v 6yprcOkijwsk78qsyQYmdi||t09NY NoO6_e403CT1YxX8 

ErrorDetai|=To access your account, you must sign in on the web. Touch Next to start browser sign-in.

**Comment by PokeBotPub** [comment]
You need to disable two-factor auth.
