### ISSUE TITLE
Pokebot 0.15

### ISSUE THREAD

**Issue by chieuvang** [PokeBotPub/PokeBot-Android#66]
Hi,
Thank you for making this happen. It has been helping me a lot, I do not need to ride my kid around to catch poke-mon anymore. It was so smooth on the 0.13, there was rarely softban issue. But in this 0.15, I even cannot catch any, I choose starting location as my local, but it does not work at all, just retry for softban. I am using an Android 6.0 Lenovo. Could you help? 

Thank you,
Bill

**Comment by chieuvang** [comment]
I got it fixed. I adjusted the settings in Speed and Delay.
Speed -> 10
Delay -> 2500

Thank you.

**Comment by mbtrading88** [comment]
I set speed2-3 range 500-1000 delay 2000
Safety at the moment..level30+
