### ISSUE TITLE
Never Transfer List - Add pokemons does not work

### ISSUE THREAD

**Issue by ubermey** [PokeBotPub/PokeBot-Android#67]
Hello, since 3 versions ado I have this issue.

Poke transfer duplicates is set to auto, but I try to add pokémon to the never transfer list and it keeps traansfering the duplicates. 

Am I missing something? ty

**Comment by macinmn** [comment]
posted in issue #42 thread:
"...workaround is to save each Filter and Keep list, but NOT press save on Transfer Settings, as this will reset them to default"
