### ISSUE TITLE
Stop iv 

### ISSUE THREAD

**Issue by mbtrading88** [PokeBotPub/PokeBot-Android#68]
Use back 0.13 patch 
Many issue 0.14 and 0.15

**Comment by macinmn** [comment]
can't make progress going back to old version when you don't say what your problems are.

**Comment by mbtrading88** [comment]
Since iv started.. 
I have 5 magikarp 210 209 207 201 197
Bot catches 107 magikarp then transfer my 197.
197 iv82.3% transferred
107 iv47% in my inventory

**Comment by mbtrading88** [comment]
I set transfer list (max 5)
Mostly all Pokemon minimum CP701
But all below cp700 still inside inventory.

The only success is (keep Pokemon list) whatever you set that list, it won't be transferred.
