### ISSUE TITLE
Player XP

### ISSUE THREAD

**Issue by kamzo123** [PokeBotPub/PokeBot-Android#72]
Firstly, thanks to the creators of this app, very well done.

I started yesterday from level 1 and now I am at 21, just a question on XP:

My player XP is 288 410, and the level 22 XP requirement is 85 000, with my XP showing as 288 410, shouldn't I be at a higher level? Or does the XP below the player mean something else?

Thanks

**Comment by macinmn** [comment]
XP total is cumulative total, not incremental for your level

see this:   http://i.imgur.com/Zq2KJLB.png

**Comment by kamzo123** [comment]
Cool, thanks for the feedback.
