### ISSUE TITLE
Bug+suggestion 1.10.15

### ISSUE THREAD

**Issue by Stl2egaX** [PokeBotPub/PokeBot-Android#75]
Bug report 1.0.15 Android6.0.1

-Bot won't walk indoor (eg. Shopping mall), it always walk and loot pokestop along road and sometime it freeze when face water edge.
-You can add something to auto-transfer list but can't delete them!
-Use xxball below catch probability isn't work, when set a value it always reset to 0.
-When you press stop button, bot stopping popup won't disappear and need to force close.

Suggestion

-manually create a route for botting
add a rest at pokestop (or anywhere) option after some period of using
-multi walking speed (eg. Walk at speed 1 for 30sec. then walk at speed 2 for 30sec.)

Thanks for your great work!!

**Comment by PokeBotPub** [comment]
Auto-transfer list bug fixed.
We will add GPX Path. 
We can add wait time on random on walk.
We still working on stop button problems, we make some changes on algorithm.
I seen xxball below catch probability bug now. We will fix is soon.
Thank you :+1:
