### ISSUE TITLE
Catching Pokemon?

### ISSUE THREAD

**Issue by Freshink808** [PokeBotPub/PokeBot-Android#8]
Does pokebot only farm pokesrops? I noticed it don't catch any or hardly any Pokémon.

**Comment by Freshink808** [comment]
Nvm it just started to catch more.

**Comment by Freshink808** [comment]
Does pokestops hold priority over catching Pokemon?

**Comment by SuperSandro2000** [comment]
I think yes because the bot catshes one Pokémon and than harvests a huge ammount of pokestops.
