### ISSUE TITLE
Yandex Map Sux

### ISSUE THREAD

**Issue by fella7** [PokeBotPub/PokeBot-Android#80]
Yandex Map Sux , is slow, and you cant pin on the map were exactly you need to be. Google maps is much faster better ... How many people is using Xiomi Devices?

**Comment by monopardz** [comment]
agree..
how can I run previuos version with google map? without updating to the latest version.

**Comment by macinmn** [comment]
Google map wasn't very friendly for emulators I know, haven't used this one long enough to say much, but it seems stable.

**Comment by monopardz** [comment]
how about including both maps and let users set thier preferred one.

**Comment by Laievskaia** [comment]
I've a xiaomi device... Google Maps was woriking very good.
Yandex cant keep in the street and jumps inside houses.

**Comment by localhost127001** [comment]
You can pin by long press, but yeah overall suck
And yes..I'm a #xiaomimasterrace

**Comment by ericlay925** [comment]
After updated to version 1.0.18, pokebot app shows the wrong language in showing the google map while selecting the location. please help to fix this problem. The language I used is zh-tw.

**Comment by Freshink808** [comment]
Bot also goes through buildings now, which if traveled to fast through it will raise niantic flags. Dev pls fix.

**Comment by luckytom333** [comment]
yes, new map sux, bring back the Google map.  Plus on the 2 phones I have, you are no longer able to choose a location using your fingers.  You have to cut and paste in the lat/lon coordinates.

**Comment by Laievskaia** [comment]
Please, bring back googl map.
