### ISSUE TITLE
Google connecting to account

### ISSUE THREAD

**Issue by Destroyermec** [PokeBotPub/PokeBot-Android#82]
Hi i saw that this is an  amzing pokemon bot but for some reason when i push the start button and it loads forever i tried everything pls help

**Comment by aureliecpz** [comment]
ca on tablet does not work, it always loads when one starts

**Comment by Destroyermec** [comment]
I am on a phone and  i tried everything i even waited 10 mins and still was on 'conecting to google acc'

**Comment by cbittar** [comment]
Be more specific what phone?

**Comment by Destroyermec** [comment]
Samsung galaxy grand neo plus.

**Comment by aureliecpz** [comment]
IPhones me and galaxie tab 9
