### ISSUE TITLE
Possibility to automatic transfer pokemon under tot IV 

### ISSUE THREAD

**Issue by alelast** [PokeBotPub/PokeBot-Android#85]
Please add this option

**Comment by encikhakim** [comment]
Yes for switching between iv or cp transfer please, and bring back the old google map api(yandex sux keep on jumping and make softban!).

**Comment by macinmn** [comment]
criteria for pokemon to meet a minimum CP or IV would be nice. (ie. keep if duplicate monster is over 800CP or 85IV, user set levels of course, but would discard if neither was met)

**Comment by alelast** [comment]
<a href='http://postimg.org/image/f5cmz5auh/' target='_blank'><img src='http://s12.postimg.org/v3lcpa52l/Screenshot_20160925_173436.png' border='0' alt='Screenshot_20160925-173436'/><br /><a target='_blank' href='http://postimage.org/index.php?lang=italian'>upload</a><br /><br />

Like this
