### ISSUE TITLE
Bot moves to fast.

### ISSUE THREAD

**Issue by Freshink808** [PokeBotPub/PokeBot-Android#9]
Any way to slow bot down to avoid soft ban. As of now the bot is moving way to fast to be human like. Thanks

**Comment by JeffJr99** [comment]
Yes can you please fix the walking speed issue? I also find it too fast and can get soft banned easily. Perhaps can make a future version configurable for walking speed and perhaps with more configurable options? Thank you.

**Comment by SuperSandro2000** [comment]
Add an option for that, please.

**Comment by SuperSandro2000** [comment]
I tested the bot for a couble nichts now. The first nicht he ran 7 hours without soft banning but the second night hr got soft banned after 4 hours and the third night after 5. 
I think he got soft banned because he moved to fast or he looted way to much poke stops. Sometimes he lots 3 or even more in minute.

**Comment by rodion-azael** [comment]
It would be nice to have more options. Like using Lucky egg yes or no, speed walking, etc.
I usted it yesterday and I día not like that it hatch eggs, wasted my Lucky eggs, etc, without even asking. I stopped using it, but I think this is a great project and I'm looking forward to have a more configurable version. You are doing a great job, keep it like that.

**Comment by JeffJr99** [comment]
Still seems to hop around great distances still even with newest patch and set for like walking speed 10. Almost like it teleports you on the map. Afraid of the ban due to this.

**Comment by SuperSandro2000** [comment]
Almost all bots to teleports to save api calls and bandwidth. I assume that the vanilla app does similar things to reduce the stress on their servers. 
So far I only think that to many poke stop loots got my account soft banned for eight hours. If you don't believe me just create a fake account and test it out for yourself.
