### ISSUE TITLE
check boxes - pokemon list

### ISSUE THREAD

**Issue by fosca1984** [PokeBotPub/PokeBot-Android#93]
it would be better to set up the pokemon filter list, if you put check boxes, instead of a list to click in the name. Then you go back to the list, and click another one.
with the check boxes, would be faster and easyer.

**Comment by crisperfx** [comment]
If you are well knowed with android files, maybe you can edit the "pokebot.db" file. With sqleditor apk you can edit the file and add all pokemons bij name if you like. Also change anything you want. After changing open the game.
