### ISSUE TITLE
I can't log in with my Google account 

### ISSUE THREAD

**Issue by Kevsw** [PokeBotPub/PokeBot-Android#99]
![screenshot_20160923-061712](https://cloud.githubusercontent.com/assets/22398409/18792503/b1746d6a-816b-11e6-9287-c8cdfd8ea756.png)

I just change my password of my Google account, and when I tried to log in to the app with my new pass appears the message attached on the image, can someone help me what to do please?

**Comment by mbtrading88** [comment]
U set up 2nd security settings.. off it.

**Comment by mbtrading88** [comment]
Account.Google  
Off the 2nd step security..
Try off it and login again..
